### ISSUE TITLE
OpenAPI 3 caches results, so if API changes, it does not reflect the changes

### ISSUE THREAD

**Issue by Robot8A** [spec-first/connexion#1001]
### Description
It seems to be similar to
https://github.com/swagger-api/swagger-js/issues/792

When I query some data to the API several times in a short time period the data is only generated once and I get the cached result the following times. I've discovered it because most of my API calls return a file (via Flask send from directory) and the file timestamp doesn't change throughout calls, even though it should generate a new file every time (the call code creates a new file, writes on it and then sends it). This is a problem because the data in my database changes every couple minutes, so the result is sometimes wrong because it doesn't reflect the last data in the db.
Also, changing the called function code in Python and restarting the server does nothing, as it still serves the cached data even though the code has changed and the resulting data should be different.

### Expected behaviour
Executes python code every time a call is made to the API.

### Actual behaviour
Does not, returns cached data if available.

### Steps to reproduce
Request the same API call with the same parameters every time. If the parameters change the code is run and newest data is returned, if parameters are the same as a previous call the code is not run and cached data is returned.

### Additional info:
Werkzeug/0.15.2 Python/3.6.8 Connexion/2.3.0 Flask/1.1.1
openapi: "3.0.0" in yaml file

**Comment by RobbeSneyders** [comment]
I'm assuming this is related to `swagger-ui`, and that issue seems to be fixed.
