### ISSUE TITLE
Nested object not part of schema when using allOf

### ISSUE THREAD

**Issue by buotex** [spec-first/connexion#1006]
### Description
Some simple usecase using allOf
```
openapi: 3.0.0
paths:
  /test:
    post:
      operationId: app.test
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
            
             
      responses:
        "200":
          description: OK


components:
  schemas:

    Item1:
      allOf:
      - type: object
      properties:
        prop1:
          type: string
          example: Item1
    Task:
      type: object
      properties:
        test_items:
        $ref: "#/components/schemas/Item1"
```
I'm doing a POST with a requestBody containing
```
{
"test_items": {"prop1": "Item1"}
}
```
### Expected behaviour

Using POST, the function call app.test should receive the full requestBody

### Actual behaviour

- Warning that `Body property 'test_items' not defined in body schema
- Empty body `{}`

This gets fixed when removing the allOf part in Item1

### Steps to reproduce
Launching the yaml file with connexion and using POST with the provided example

### Additional info:

Output of the commands:

- `Python: 3.7.3`
- `connexion: 2.0.0`

**Comment by RobbeSneyders** [comment]
Cannot reproduce, seems to be fixed.
