### ISSUE TITLE
connexion with swagger UI for url encoded form data is not rendered correctly

### ISSUE THREAD

**Issue by jairaju** [spec-first/connexion#1015]
### Description
I am trying to use anyOf feature in OAS 3.0 with connection 2.3.0 and swagger-ui-bundle 0.0.5
on a flask application.

My requestBody for a POST request is url encoded form data, so I define them as below
   "components": {
        "requestBodies": {
            "customEventBody": {
                    "content": {
                            "application/x-www-form-urlencoded":{
                                   "schema": {
                                        "anyOf": [
                                             {
                                                "$ref": "#/components/schemas/Interrupt"
                                             },
                                             {
                                                "$ref": "#/components/schemas/injected_val"
                                             },
                                             {
                                                "$ref": "#/components/schemas/document"
                                             }
                                           ]
                                           }
                                    }
                            },
                       }
           },
           "schemas": {
              "Interrupt": {
                 "title": "Interrupt event",
                 "type": "object",
                 "properties": {
                        "Interrupt": {
                                 "type": "boolean"
                             }
                     }
               },
              "injected_val": {
                 "title": "Injected value",
                 "type": "object",
                 "properties": {
                        "injected_val": {
                                 "type": "string"
                             }
                     }
               },
              "document": {
                 "title": "document",
                 "type": "object",
                 "properties": {
                        "document": {
                                 "type": "string"
                             }
                     }
               }
            }
     }

### Expected behaviour
when I do the tryout option to try one test with a requestbody
'Interrupt'='true'
it should give me a curl request as follows:
curl -X POST "http://xx.yy.zz.ee:8080/api/v1/calls/54544/js" -H "accept: /" -H "Content-Type: application/x-www-form-urlencoded" -d "interrupt"="true"

### Actual behaviour
curl -X POST "http://xx.yy.zz.ee:8080/api/v1/calls/54544/js" -H "accept: /" -H "Content-Type: application/x-www-form-urlencoded" -d "0='&1=I&2=n&3=t&4=e&5=r&6=r&7=u&8=p&9=t&10='&11=%3D&12='&13=t&14=r&15=u&16=e&17='"

### Steps to reproduce
It is reproducible with the above json file content

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by RobbeSneyders** [comment]
Cannot reproduce. If you still encounter this issue, please open an issue at swagger-ui-bundle.
