### ISSUE TITLE
Wrong type, expected 'integer' for requestBody parameter (OpenAPI 3.0)

### ISSUE THREAD

**Issue by insideshell** [spec-first/connexion#1022]
### Description

I use `formData` parameters to describe request bodies (see [Describing Request Body → Form Data](https://swagger.io/docs/specification/describing-request-body/)).
It is convenient since this generates a ready to use form:

![image](https://user-images.githubusercontent.com/4362224/63356880-d0497180-c368-11e9-8888-c5d885f282fc.png)

In this simple example, I just added two `formData` parameters on your [helloworld example](https://github.com/zalando/connexion/tree/master/examples/openapi3/helloworld).

### Expected behaviour

The `email` field cannot stay empty during form validation (it should shake and get a red background).
The `fav_number` field can stay empty during form validation (since it is not required).

### Actual behaviour

Even if the `email` field is required, it is not checked during form validation. I investigated and this comes from a bug in Swagger (see issue [#5181](https://github.com/swagger-api/swagger-ui/issues/5181)) and this is not related with Connexion.

But now if the `fav_number` is empty, here is the error returned by Connexion:

```json
{
  "detail": [
    "Wrong type, expected 'integer' for requestBody parameter 'fav_number'"
  ],
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

And it happens only for integer parameters. Change `fav_number` to string and it will work as expected.

*EDIT:* actually it happens for all non string parameters (ipv4 format, boolean type, etc.).

### Steps to reproduce

1. Download the [helloworld example](https://github.com/zalando/connexion/tree/master/examples/openapi3/helloworld).
2. Add two `formData` parameters (the `requestBody` section):

```yaml
openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: http://localhost:9090/v1.0

paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: hello.post_greeting
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello dave!"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            type: string
            example: "dave"

      # ----- BEGIN: Add two formData parameters ----
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                fav_number:
                  type: integer
              required:
                - email
        # ----- END: Add two formData parameters ----
```

3. Go to http://localhost:9090/v1.0/ui/ and send the form as it is.
4. You'll get the error mentioned above.

### Additional info:

Output of the commands:

- `python --version` : 3.6.8
- `pip show connexion | grep "^Version\:"` : 2.3.0

**Comment by dtkav** [comment]
Can you reproduce this without the swagger-ui component?
If you can provide a curl command that is able to trigger this, I'd be able to look into it.
At the moment it sounds like swagger-ui might be passing a string even when you believe the field is empty (maybe a space or something).
