### ISSUE TITLE
gunicorn connexion and "Transfer-Encoding: chunked" header

### ISSUE THREAD

**Issue by AviranAbady** [spec-first/connexion#1027]
When running the app using gunicorn, requests containing the header `Transfer-Encoding: chunked`
are being processes as if the request has no body.
Which soon results in a validation error by the openapi validator.

python 3.6.8
connexion 2.3.0
gunicorn 19.9.0

**Comment by RobbeSneyders** [comment]
Please provide a minimal  reproducible example.
