### ISSUE TITLE
app add mutiple swagger yaml files，throw blueprints that are created on the fly need unique names.

### ISSUE THREAD

**Issue by septyy** [spec-first/connexion#1032]
### Description
app = connexion.App(__name__, specification_dir='./swagger/')
app.add_api('v2.yaml')
app.add_api('v2_auth.yaml')

v2.yaml
openapi: 3.0.1
info:
  title: xxx
  description: xxx 
  version: 2.0.0
servers:
  - url: /v2
tags:
  - name: xxx
    description: xxx

v2_auth.yaml
openapi: 3.0.1
info:
  title: xxx
  description: xxx 
  version: 2.0.0
servers:
  - url: /v2
tags:
  - name: xxx
    description: xxx

When I start app, it throws "A name collision occurred between blueprints <flask.blueprints.Blueprint object at 0x7f2379580810> and <flask.blueprints.Blueprint object at 0x7f2379580a90>. Both share the same name "/v2". Blueprints that are created on the fly need unique names."

So I would like to know if the servers.url can't be repeated in different swagger files? If so, Is it possible to load both files by modifying the code? 

### Expected behaviour
Run successfully.

### Actual behaviour
A name collision occurred between blueprints <flask.blueprints.Blueprint object at 0x7f2379580810> and <flask.blueprints.Blueprint object at 0x7f2379580a90>. Both share the same name "/v2". Blueprints that are created on the fly need unique names.

### Additional info:

Output of the commands:

- `python --version`  2.7.5
- `pip show connexion | grep "^Version\:"`   2.3.0

**Comment by marek-danel** [comment]
I had the same error. Adding base_path to add_api call fixed it for me:
```
cxn.add_api('v1/swagger.yaml', base_path='/v1')
cxn.add_api('v2/swagger.yaml', base_path='/v2')
```
