### ISSUE TITLE
Slowness in resolving controller

### ISSUE THREAD

**Issue by niciqy** [spec-first/connexion#1034]
### Description
In New Relic, I am seeing my app spending 50% of it's time in getting to the controller. Is this something that is experience by other people?

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by dtkav** [comment]
Hey @niciqy - maybe you could provide more information about your test setup?
Does your API require deserialization of large inputs? I'd love to know more about what is slow (validation , deserialization, etc)
