### ISSUE TITLE
Connexion App is not accepting the celery instance even after setting the context manually

### ISSUE THREAD

**Issue by pilayar76** [spec-first/connexion#1048]
### Description
While trying to add the celery instance with Connexion Flask Context, its not getting added due to which we are unable to register the tasks.

### Expected behaviour
App context should accept Celery Instance as well.

### Actual behaviour

Not accepting the celery instance to the context of Connexion app.

Kindly advise whether connexion framework has the capability to accept celery instance and also if you can provide an example, it would be great.

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by dtkav** [comment]
It's hard to help with just the information you provided.
Are you using the underlying flask app?

**Comment by pilayar76** [comment]
Yes we are using connexion.app which tries to set the context with celery

**Comment by dtkav** [comment]
can you provide a [minimal working example](http://www.sscce.org/) please?

**Comment by ragyibrahimRNA** [comment]
i am using the below example

```python
import connexion
from celery import Celery

app = connexion.FlaskApp(__name__,
                         specification_dir='./')
app.add_api('api.yaml')


def make_celery(app):
    celery = Celery(
        app.import_name,
        backend=app.config['CELERY_RESULT_BACKEND'],
        broker=app.config['CELERY_BROKER_URL']
    )
    celery.conf.update(app.config)

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery


app.config.update(
    CELERY_BROKER_URL='redis://localhost:6379',
    CELERY_RESULT_BACKEND='redis://localhost:6379'
)

celery = make_celery(app)


@app.route('/')
def my_app():
    pass


if __name__ == '__main__':
    app.run(host='0.0.0.0',
            debug=False)
```

Now in another module i am importing celery `from anomaly_server import celery` and im having the same issue with error `circular import`

**Comment by RobbeSneyders** [comment]
Please use the underlying Flask app, which you can access via `app.app`.
