### ISSUE TITLE
Using Connexion with an OpenApi spec impossible if installed from conda

### ISSUE THREAD

**Issue by sveme** [spec-first/connexion#1053]
### Description
When installing Connexion from the conda-forge channel, the OpenApi support is not available as the dependency openapi-spec-validator is not available on conda-forge. I know that this is probably not your issue to solve, but something to keep in mind for your developers. 

### Expected behaviour
The package openapi-spec-validator should be available on conda-forge so that connexion works with Open Api via Conda (and subsequently so that Constructor works with Connexion).

### Actual behaviour
An OpenApi spec cannot be validated

### Steps to reproduce
Install Connexion via conda-forge, try running an OpenApi spec with it.

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by dtkav** [comment]
#936 may help with this, as switching to a pure jsonschema validator would allow us to drop the dependency.

**Comment by RobbeSneyders** [comment]
Fixed by #936
