### ISSUE TITLE
JSON responses with NaNs cause a silent "no response from server" error 

### ISSUE THREAD

**Issue by arel** [spec-first/connexion#1068]
### Description

I upgraded an internal subsystem of my API, and I started seeing occasional "no response from server errors" that seemed to affect _some_ responses and not others. After tracking down the issue, I learned that my subsystem was (unintentionally) occasionally returning `nan` values, and connexion was failing cryptically when generating the response.

I understand that `NaN` is not a valid JSON value, but _Python's_ JSON implementation (at least for Pythons 3.6 and 3.7) _does_ accept `NaN` values (for whatever reason).

When an API response contains a `NaN` value, connexion responds with the cryptic error:

```json
{
  "error": "no response from server"
}
```

Also, I found no useful debug information in the logs to isolate the problem. I would expect that connexion should throw an exception when encountering `NaN` values, with a helpful error message, rather than a silent error.

I just spent a couple of hours tracking down this bug. Hopefully, this saves other people some time.

### Expected behavior

I would expect:

1. the API should return a validation error when the JSON response is invalid.
2. the API should return a response rather than nothing
3. the connexion logs should report the error (especially, at `DEBUG` level---though I would expect it to be at `ERROR` level)
4. the API logs should not display a 200 status code for the response (even though the server returns no response)
5. the API should return a 4xx or 5xx status code

### Actual behavior

Even with `DEBUG`-level logging settings, the logs are indistinguishable between a response containing `NaN` values and one without one.

The Connexion UI returns: 

### Response Body
```
no content
```
### Response Code
```
0
```
### Response Headers
```json
{
  "error": "no response from server"
}
```

### Steps to reproduce

Note how python handles `nan`/`NaN` values in JSON:

```
In [1]: import json

In [2]: j_nan = json.loads('{"position": [NaN, NaN], "score": 0.3}')

In [3]: j_ok = json.loads('{"position": [0.4, 0.5], "score": 0.3}')

In [4]: j_nan
Out[4]: {'position': [nan, nan], 'score': 0.3}

In [5]: j_ok
Out[5]: {'position': [0.4, 0.5], 'score': 0.3}

In [6]: json.dumps(j_nan)
Out[6]: '{"position": [NaN, NaN], "score": 0.3}'

In [7]: json.dumps(j_ok)
Out[7]: '{"position": [0.4, 0.5], "score": 0.3}'
```

In a connexion controller function that returns a JSON response:

```python
# fails
return {'position': [nan, nan], 'score': 0.3}

# works
return {'position': [0.4, 0.5], 'score': 0.3}
```

### Additional info:

Output of the commands:

- `python --version`  **Python 3.7.0**
- `pip show connexion | grep "^Version\:"`  **Version: 2.4.0**

**Comment by RobbeSneyders** [comment]
Can no longer reproduce
