### ISSUE TITLE
SecureOperation class mimetype is burnt in to be application/json

### ISSUE THREAD

**Issue by tamasSzentandrasi** [spec-first/connexion#1107]
### Description
connexion/operations/secure.py, get_mimetype() seems to be unimplemented. 

Personally, I've needed to return a text/plain response, it got serialized and escaped and returned as application/json.

### Expected behaviour

Set the RequestResponseDecorator to the appropriate mimetype according to what's written in swagger.yaml.

### Actual behaviour

The value is set to DEFAULT_MIMETYPE, which is set to application/json regardless of the mimetype given.

### Steps to reproduce

So far, it seems any mimetype of the response that is not set to application/json is not doing what is expected. 

### Additional info:

The fix I've added into the local fork is just a rough workaround:

```
@property
    def _request_response_decorator(self):
        """
        Guarantees that instead of the internal representation of the
        operation handler response
        (connexion.lifecycle.ConnexionRequest) a framework specific
        object is returned.
        :rtype: types.FunctionType
        """
        if (self.request_body == {}):
            mimetype = self.get_mimetype()
        else:
            mimetype = self.request_body.get('content').keys().__str__()[12:-3]
        return RequestResponseDecorator(self.api, mimetype)
```

This solved the issue, although its tailored to the current needs of my application.

Output of the commands:

- `python --version`
Python 3.8.0
- `pip show connexion | grep "^Version\:"`
Version: 2.4.0

**Comment by dtkav** [comment]
Hey @tamasSzentandrasi , can you provide a minimal reproducible example (spec, application, and test case that show the bug)?

I can't tell exactly what you're trying to do. `secure.py` is mostly used as a base class, and so get_mimetype() and mimetype handling is performed elsewhere for most routes.

Connexion isn't great at working with multiple content-types at once (it was mostly built with json in mind, this is a known bug), but this is something I'm actively working on, so your example could be helpful.

**Comment by tamasSzentandrasi** [comment]
Hi @dtkav, yes, i can:

Lets say the endpoint is supposed to do this according to swagger.yaml:
```
paths:
  /example:
    summary: Test Endpoint
    post:
      tags:
      - Internal
      operationId: test_endpoint
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        "400":
          description: Malformed input
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        default:
          description: Successful operation
      x-openapi-router-controller: swagger_server.controllers.internal_controller

```
Its not really useful, but shows the issue. At the controller, lets return some string:
```
def test_endpoint(body=None):  # noqa: E501
    """test_endpoint

     # noqa: E501

    :param body: 
    :type body: dict | bytes

    :rtype: str
    """
    if connexion.request.is_json:
        body = str.from_dict(connexion.request.get_json())  # noqa: E501
    return 'A string with tabs\t\t and newline\n'

```
This is what happens when i try out the endpoint. As you can see, the mimetype defaulted to application/json instead of the expected text/plain, and all the escaped characters remained.

![image](https://user-images.githubusercontent.com/6174230/71072299-7cb42c80-217e-11ea-8955-34cf55194814.png)

Now with my modification, the output is the following:

![image](https://user-images.githubusercontent.com/6174230/71072468-dfa5c380-217e-11ea-993d-7768f1606c6b.png)

As you can see, i correctly parsed out the response mimetype, and now it functions as intended.

**Comment by dtkav** [comment]
I see. thanks for the example, it's much clearer.

**Comment by RobbeSneyders** [comment]
This was reworked for Connexion 3, which will be released tomorrow. Feel free to reopen if you still run into this issue.
