### ISSUE TITLE
Add type annotations and mypy validation

### ISSUE THREAD

**Issue by hjacobs** [spec-first/connexion#1111]
As we only support Python 3 now, we can safely use type annotations (`typing` module) and use [mypy](http://mypy-lang.org/) for validation, e.g. like here https://github.com/hjacobs/kube-resource-report/blob/master/Makefile#L11

This is a follow-up to #2.

**Comment by cclauss** [comment]
`mypy --exclude '/(__init__|api|api.pets|app|hello|orm|resty)\.py$' --install-types --non-interactive .` --> #1405
