### ISSUE TITLE
Response keys should be strings

### ISSUE THREAD

**Issue by patrickkwang** [spec-first/connexion#1112]
There are a handful of yaml schemas with something like:
https://github.com/zalando/connexion/blob/f31ac615bfc8a3c696c5ebe53f3c57e5234ff6f8/examples/openapi3/helloworld/openapi/helloworld-api.yaml#L15-L16
pyyaml interprets these keys as integers, while the OpenAPI specification requires that they be strings:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#format

The above should be replaced with
```yaml
      responses:
        '200':
```
[openapi-spec-validator](https://github.com/p1c2u/openapi-spec-validator) does not validate this, but instead coerces `int` keys to `str`.

**Comment by dtkav** [comment]
I think the support for coercing `int` to `str` is from swagger2.
