### ISSUE TITLE
Accessing connexion context throws AttributeError exception

### ISSUE THREAD

**Issue by drubinMeta** [spec-first/connexion#1134]
We are using after_req hook that among other things checks presence of
token_info in connexion context by calling:
connexion.context.get('token_info')

Issuing GET request that does not requires security auth causes the following exception:

> File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
return getattr(self._get_current_object(), name)
File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 307, in _get_current_object
return self.__local()
File "/usr/local/lib/python3.6/site-packages/connexion/apis/flask_api.py", line 252, in _get_context
return getattr(flask._request_ctx_stack.top, 'connexion_context')
AttributeError: 'RequestContext' object has no attribute 'connexion_context'"

> 

What would be the proper way to check whether connexion_context set.
Thanks

- python version: 3.6
- connexion version: 2.5.1

**Comment by RobbeSneyders** [comment]
This should be fixed in Connexion 3, which will be released tomorrow.
