### ISSUE TITLE
Issue with getting multiform data

### ISSUE THREAD

**Issue by svkmdl** [spec-first/connexion#1147]
### Description
Hi, I have a multipart-form data described in my requestBody for a post method in openAPI spec. It looks like :

requestBody:
        content: 
          multipart/form-data: # Media type
            schema:            # Request payload
              type: object
              properties:      # Request parts
                param1:            # Part 1 (string value)
                  type: string
                param2:       # Part2 (string)
                  type: string
            encoding: 
              param1: 
                contentType: text/plain
              param2:
                contentType: text/plain

### Expected behaviour

The post method arguments, on being called are populated by the multipart data encoded in the post call

### Actual behaviour

The arguments remain empty even though the right method gets called. Also the model body's deserialize methods aren't called.

Anyone knows how to ensure that my post method's arguments are populated by the passed mutiform data?

### Additional info:

Output of the commands:

- `python --version`
Python 3.6.9
- `pip show connexion | grep "^Version\:"`
Version: 2.2.0

**Comment by RobbeSneyders** [comment]
The `requestBody` is currently not parsed for OpenAPI 3, but passed in as the `body` parameter. You can overwrite the name of this parameter with `x-body-name`.
