### ISSUE TITLE
Problems with connexion, gunicorn. 

### ISSUE THREAD

**Issue by ratsoft2** [spec-first/connexion#1151]
Hello I am currently using flask, gunicorn and nginx, all that works well for me. This is an example of my current template on the server.

from flask import (Flask, render_template)
app = Flask (__ name__, template_folder = "templates")
@ app.route ('/')
def home ():
     return render_template ('home.html')
if __name__ == '__main__':
     app.run (debug = True)

But when I want to use connexion and swagger, with a file like this, it works on my local PC. But when I upload it to the server with gunicorn and nginx, right there it doesn't work on the server

from flask import render_template
import connection
app = connexion.App (__ name__, specification_dir = '. /')
app.add_api ('swagger.yml')
@ app.route ('/')
def home ():
     return render_template ('home.html')
if __name__ == '__main__':
     app.run (host = '0.0.0.0', port = 5000, debug = True)

Is something missing in the second configuration?
sorry for the language

- python 3.`
- connexion 2.6

**Comment by dtkav** [comment]
Have you configured gunicorn to use `app.app`? `app` is the connexion application, whereas
`app.app` is the flask application.

**Comment by ratsoft2** [comment]
Hello @dtkav I could solve my problem, thanks.
