### ISSUE TITLE
Should `None is not of type 'object'` be friendlier?

### ISSUE THREAD

**Issue by mihai-dinculescu** [spec-first/connexion#1152]
### Description
When an endpoint that expects a body is called without one, `None is not of type 'object'` is returned. Would you agree that a friendlier message would be preferable?

### Expected behaviour
A friendlier message saying something along the lines "A request body is required".

### Actual behaviour
`None is not of type 'object'`

### Steps to reproduce
- Endpoint expecting a request with a JSON body
- Call it without providing a body

### Additional info:
N/A

**Comment by Abdullahabid3691** [comment]
Yes, this error message should be updated specifically when the request's body is passed null. This error message is so confusing instead of being helpful.
