### ISSUE TITLE
How can I disable automatic routing and instead use Flask-Restful custom routing?

### ISSUE THREAD

**Issue by caffeinatedMike** [spec-first/connexion#1153]
### Description
Since I can't completely migrate to an OpenAPI 3 spec yet due to validation issues (#963) ([comment](https://github.com/zalando/connexion/issues/963#issuecomment-585899100)) I'm going to port over my current Swagger 2.0 spec from Flasgger to Connexion for the time-being, 

However, before I can even do that I need to know if there is a way to disable Connexion from attempting to automatically route paths in the Swagger spec to Flask routes. The reason I want to disable this until I am able to port my entire API codebase over to Connexion is because I already have all routes defined in a single file (`routes.py`) that associate each `Flask-Restful Resource` entity to their respective routes.

## Plan
- Stage 1: 
  1. Port over Swagger 2.0 spec from Flasgger to Connexion, so basic validations can still take place
  2. Disable automatic routing, leaving Flask Restful routes in place
  3. Password-Protect Swagger UI, so it can be used for testing
  4. Serve OpenAPI 3 spec using [ReDoc](https://github.com/Redocly/redoc) for better public presentation
- Stage 2:
  1. Once #963 is addressed I'll make the necessary routing adjustments and start utilizing `MethodViewResolver`

**Comment by RobbeSneyders** [comment]
This is not supported.
