### ISSUE TITLE
Disable response validation for a specific route 

### ISSUE THREAD

**Issue by Heiss** [spec-first/connexion#1156]
### Description
I want to enable the response validation for all routes, but currently connexion does not support any binary responses like send_file, so i want to deactivate the validation for this routes. I did not find any decorator or shortcut for this use-case.

I do not want to write a custom validator only for one route, the content and mimetype of the served file is not relevant for my application.

Thank you for your help.

**Comment by RobbeSneyders** [comment]
Streaming responses are no longer validated, see https://github.com/spec-first/connexion/pull/1259.
