### ISSUE TITLE
date-time validation and parsing?

### ISSUE THREAD

**Issue by mnylen** [spec-first/connexion#1159]
### Description

Connexion does not seem to validate the format of query string parameters described using OpenAPI 3.x.x as `{ type: string, format: date-time }`. In addition, it would be helpful if Connexion could automatically parse the values to python datetime.

### Expected behaviour

If invalid value is provided:

400 Bad Request because the value for `since` parameter was not valid RFC3339 date-time.

If valid value is provided:

Handler is passed the `since` parameter parsed as `datetime.datetime`

### Actual behaviour

Request validation passes, handler is passed the parameter value as string.

### Steps to reproduce

Excerpt from the spec:

```
openapi: "3.0.0"
paths:
  /get_with_datetime_parameter:
    get:
       operationId: get_with_datetime_parameter
       parameters:
         - name: since
            required: true
            in: query
            schema:
              type: string
              format: date-time
...
```

### Additional info:

Output of the commands:

- `python --version`: 3.7.6
- `pip show connexion | grep "^Version\:"`: 2.6.0

**Comment by anis-campos** [comment]
Seems related to #476, not about the same format, but it definitely has the same origin

**Comment by hsgreen** [comment]
Yes, the suggestions in #476 worked for me to resolve this same issue.
Simply install `strict-rfc3339` prior to running your server.
