### ISSUE TITLE
Incorrect type hint on FlaskApp.add_error_handler()

### ISSUE THREAD

**Issue by macdjord** [spec-first/connexion#1164]
### Description
`FlaskApp.add_error_handler()` has an (old-style comment) type hint which claims its call signature is `(int, FunctionType) -> None`. This is incorrect; the correct signature is `(Union[int, Type[Exception]], Callable[[Exception], Any]) -> None`

### Additional info:

Version: `connexion==2.6.0`

**Comment by Sinclert** [comment]
+1
