### ISSUE TITLE
validate_cookie_parameter is using a non-existing ConnexionRequest attribute

### ISSUE THREAD

**Issue by mzapotoczny** [spec-first/connexion#1168]
### Description
When requesting a path with a cookie as one of it's parameters, we end up with the following error:
```
"connexion/decorators/validation.py", line 331, in validate_cookie_parameter
    val = request.cookies.get(param['name'])
AttributeError: 'ConnexionRequest' object has no attribute 'cookies'
```

### Expected behaviour

Cookie parameter should be validated

### Actual behaviour

An error is raised

### Steps to reproduce

api.yaml:
```yaml
openapi: 3.0.1

info:
  title: TestAPI

paths:
  /test:
    get:
      operationId: test.cookie_test
      description: Test op
      parameters:
        - in: cookie
          name: session
          schema:
            type: string
      responses: {}

```

test.py:
```python
import connexion

def cookie_test(session):
    return session

app = connexion.App(__name__, specification_dir='./')
app.add_api('api.yaml')
app.run(port=8080)
```

Invoke method `/test`

### Additional info:

Output of the commands:

- `python --version` Python 3.7.5
- `pip show connexion | grep "^Version\:"` Version: 2.6.0

**Comment by noirbee** [comment]
Bare-bones fix in PR #1209, tested with Flask
