### ISSUE TITLE
Any way to stop logging Validation Errors?

### ISSUE THREAD

**Issue by fvcaputo** [spec-first/connexion#1169]
### Description

When using `strict_validation` on my app the validation works correctly and returns a 400 Bad Request, however this error is logged and eventually appears on Sentry (where we are logging our errors). Is there a way to stop the logs on these cases? They aren't exactly server errors - a client is making an invalid request, so I'd like to stop logging these as errors in the application.

**Comment by niksauer** [comment]
I have the same issue. Very annoying to see this output in the unit tests.

**Comment by RobbeSneyders** [comment]
Looks like this was fixed.
