### ISSUE TITLE
Allow FlaskApp to accept flask specific kwargs so that it can be passed to the Flask constructor

### ISSUE THREAD

**Issue by tahalukmanji** [spec-first/connexion#1172]
### Description
We use connexion for REST API purposes and also use the Flask app object to setup the web GUI endpoints. Great but the problem is there seems to be no way to pass flask-related constructor arguments. This issue arises as we use py.test to test our REST and web endpoints and because the way how py.test sets the current working directory, it does not load the templates directory as Flask uses relative default path to load the templates.

### Expected behaviour
I can provide a quick fix for it. The FlaskApp constructor [from .apps.flask_app import FlaskApp] can accept another argument called flask_kwargs which can then be passed to the Flask object in create_app. I will submit a fix for it. I think it will be very beneficial for a lot more people.

### Additional info:

Output of the commands:

- `python --version`
python3 --version
Python 3.7.4
- `pip show connexion | grep "^Version\:"`
python3 -m pip list | grep connexion
connexion                     2.4.0

**Comment by RobbeSneyders** [comment]
You can do this via the `server_args` parameter.
