### ISSUE TITLE
OAuthResponseProblem token_response always None

### ISSUE THREAD

**Issue by mnylen** [spec-first/connexion#1198]
The exception handling documentation https://github.com/zalando/connexion/blob/master/docs/exceptions.rst states that the `OAuthResponseProblem` contains `token_response` property:

> This exception is thrown when there is a validation issue from your OAuth 2 Server. It contains a token_response property which contains the full http response from the OAuth 2 Server

In my testing however the `token_response` is always set to `None`. From the implementation it seems that in the three places (all in security.py) that `OAuthResponseProblem` is being raised, the `token_response` keyword argument is always set to `None`.

Is the documentation incorrect, or should the implementation pass the `token_response`?

**Comment by RobbeSneyders** [comment]
This has been removed from the documentation.
