### ISSUE TITLE
Endpoints without parameters return 200 when passed a parameter

### ISSUE THREAD

**Issue by jeremyschiemann** [spec-first/connexion#1207]
### Description
Endpoints that dont have any parameters specified (for example a health check) return a 200 code even when passed a parameter, it should return a 4XX code like endpoints with parameters when strict_validation is set to True

### Expected behaviour
return 4XX code when wrong parameter is passed

### Actual behaviour
returns a 200

### Steps to reproduce
create endpoint without any parameters and then call it with parameters while strict_validation is True

### Additional info:

Output of the commands:

- `python --version` 3.8.1
- `pip show connexion | grep "^Version\:"` 2.6.0

**Comment by RobbeSneyders** [comment]
Fixed in https://github.com/spec-first/connexion/pull/1610
