### ISSUE TITLE
Question: How can one install their own jsonifier object?

### ISSUE THREAD

**Issue by ddurham2** [spec-first/connexion#1220]
Question: How can one install their own jsonifier object?  I would like to decode some custom types on the incoming request and need to use a customized call to json.loads().  
I see possible mention of supplying a custom one in [#846](https://github.com/zalando/connexion/issues/846#issuecomment-453729705) (and datetime is also one of my concerns), but no explanation of how.  TIA

As a followup question, if I were to install my own jsonifier, and customize loads() to, e.g., parse date-time strings as datetime.datetime objects, it seems that validation would happen after this and fail because it's not of a string type.  Is this something that can be handled more elegantly?    Otherwise, I'm going to have to invoke a conversion function at the beginning of each handler to convert datetimes.  

Should connexion, using the 'format: date-time' data-type hint, automatically create datetime objects out of these strings before invoking the handler (which would break older code, but perhaps a good feature for a future major version which can break compatibility)?

**Comment by RobbeSneyders** [comment]
This can now be passed to your app or api in Connexion 3, which will be released tomorrow.
