### ISSUE TITLE
Authentication pop dialog missing

### ISSUE THREAD

**Issue by FrankCRoth** [spec-first/connexion#1224]
### Description
The authentication popup is not shown in connexion if you use authentication.

### Expected behaviour
If you use security section in swagger file the authentication dialog should be shown if you did not enter any information.

### Actual behaviour
There is no popup in swagger ui and just 401 is displayed

### Steps to reproduce
any authentication example, like connexion/examples/openapi3/basicauth/openapi.yaml

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by RobbeSneyders** [comment]
Cannot reproduce
