### ISSUE TITLE
weird passing of aiohttp middlewares no more needed

### ISSUE THREAD

**Issue by p4l1ly** [spec-first/connexion#1226]
### Description

As of #1173 , the middlewares can be passed to aiohttp via the `server_args` parameter. Messing them with the connexion options is therefore no more needed.

### Expected behaviour
```
    app = connexion.AioHttpApp(
        __name__,
        port=8080,
        specification_dir='.',
        server_args={"middlewares": [add_uuid]},
    )
```

### Actual behaviour
```
    app = connexion.AioHttpApp(
        __name__,
        port=8080,
        specification_dir='.',
        options={"middlewares": [add_uuid]},
    )
```

### Additional info:

These lines can be therefore removed:
https://github.com/zalando/connexion/blob/master/connexion/apis/aiohttp_api.py#L105-L106

Output of the commands:

- `python --version` `Python 3.8.2`
- `pip show connexion | grep "^Version\:"` `Version: 2020.0.dev1`

**Comment by RobbeSneyders** [comment]
Outdated since #1491
