### ISSUE TITLE
How can I pass objects to be used by my resources?

### ISSUE THREAD

**Issue by timbrnbrr** [spec-first/connexion#1232]
### Description

Before, when I used flask_restful i did the following in my `create_app` function:

```
my_scheduler = ThreadPoolExecutor(max_workers=2)
api.add_resource(Test, '/test/<int:id>', resource_class_kwargs={'my_scheduler ': my_scheduler })
```
This way, I could access the same `my_scheduler` object in each function call of the `Test` Resource. Now I am trying to do the same with Connexion, but can't find a solution.

What's the right way to do this using Connexion?

**Comment by RobbeSneyders** [comment]
This is not possible on a function level, but since Connexion 3, you can do this on a class level using the `MethodResolver` or `MethodViewResolver` ([docs](https://connexion.readthedocs.io/en/latest/routing.html#methodresolver))
