### ISSUE TITLE
How to find current user is not documented

### ISSUE THREAD

**Issue by SpoonMeiser** [spec-first/connexion#1312]
### Description

If security is implemented somehow, connexion makes the current user available as `connexion.context['user']`, but this doesn't appear anywhere in the documentation; it's only mentioned as a point in "New in Connexion 2.0" in the README, and even then only as a difference to the previous undocumented behaviour.

This also introduces the concept of `connexion.context` which doesn't appear to be documented anywhere either.

### Expected behaviour

All of connexion's features to be discoverable by reading the documentation

### Actual behaviour

Some of connexion's features are only discoverable by reading the source code.

**Comment by RobbeSneyders** [comment]
This was added to the documentation in #1764 and #1747
