### ISSUE TITLE
Is it possible to use connexion with https?

### ISSUE THREAD

**Issue by xiaochaowu** [spec-first/connexion#1319]
### Description
"However, Connexion doesn't provide an ssl_context parameter. This is because Flask doesn't, either--but it uses **kwargs to send the parameters to the underlying werkzeug server."

I don't understand. Is it mean if I need https then I have to give up Connexion? Or I must use something like Gunicorn to provide the https part?

Thanks!
Xiaochao Wu

**Comment by coltenkrauter** [comment]
You can totally use HTTPS along with connexion. I use [Traefik](https://doc.traefik.io/traefik/) reverse proxy and I have it configured to use LetsEncrypt... So the proxy does all of the HTTPS/TLS stuff before any requests ever get to my connexion app.

**Comment by xiaochaowu** [comment]
Thanks!
I used gunicord and it is OK now.
