### ISSUE TITLE
Which OAuth flows are supported exactly?

### ISSUE THREAD

**Issue by NobbZ** [spec-first/connexion#1350]
### Description

In the [documentation about security](https://connexion.readthedocs.io/en/latest/security.html), it is written "Connexion supports one of the three OAuth 2 handling methods", but it is not mentioned which flow exactly this is.

In a 2 year old example in the repository I found that the example uses the `implicit` flow, so is this the only supported flow or am I missinterpreting the available information?

### Expected behaviour

Explicit documentation about which flows are usable with `connexion`

### Actual behaviour

Documentation is not clear about it it.

**Comment by RobbeSneyders** [comment]
The security documentation was recently updated and this line was removed (#1764). The different Oauth flows should be supported. Feel free to open an issue if you run into any troubles while using a certain flow.
