### ISSUE TITLE
Boilerplate generator contribution

### ISSUE THREAD

**Issue by robertoberto** [spec-first/connexion#1354]
### Description
I did not found Boilerplate generator on Connexion.

So I write one. You can find it here https://github.com/robertoberto/connexion_boilerplate_generator

Maybe you can use it on connexion/connexion/cli.py

**Comment by briankinney** [comment]
I think that https://github.com/swagger-api/swagger-codegen has a code generation option that generates code that does roughly the same thing.

**Comment by RobbeSneyders** [comment]
Hi @robertoberto 

Looks neat. I don't think we should include it in connexion since the file structure of an API is quite opinion based, but I would be open to an "Ecosystem" section in the README / docs that links to it (and other useful connexion-related tools).

**Comment by robertoberto** [comment]
hi thank you for your email and link

Em seg., 5 de jul. de 2021 às 13:38, Robbe Sneyders <
***@***.***> escreveu:

**Comment by RobbeSneyders** [comment]
[editor.swagger.io](https://editor.swagger.io/) also contains a boilerplate generator for Connexion #446. We should add it to the ecosystem section as well.
