### ISSUE TITLE
Security hash maps not properly ORed when using OAuth scopes

### ISSUE THREAD

**Issue by carl-adams-planet** [spec-first/connexion#1423]
### Description
Security specification handling does not seem to properly apply OpenAPI "OR" semantics when trying to specify that "scope 1" or "scope 2" are acceptable for a given endpoint.  See https://swagger.io/docs/specification/authentication/ for a description of how the security section specifies a list of hashmaps where the maps specify AND criteria but the list is a list maps that are ORed.

### Expected behaviour
I should be able to use OpenAPI security OR semantics to specify the same security scheme in different `security` entries with different scopes specified.

### Actual behaviour
When the same security scheme is listed in multiple entries in the security section, the last one appears to clobber the earlier one.

### Steps to reproduce
Consider the spec fragment: 
````
{
  "components": {
    "securitySchemes": {
      "OAuthAuthCode": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://my-provider/authorize",
            "tokenUrl": "https://my-provider/token",
            "scopes": {
              "my.scp1" : "my test scope 1",
              "my.scp2" : "my test scope 2"
            }
          }
        }
      }
    }
  },  
  "security": [
    {
      "OAuthAuthCode": ["my.scp1"]
    },
    {
      "OAuthAuthCode": ["my.scp2"]
    }
  ],
}
````

I would expect that endpoints using the default security would accept tokens with the `my.scp1` or `my.scp2` scope.  In practice, an access token with `my.scp1` is rejected, and only a token with `my.scp2` is accepted.

### Additional info:

Output of the commands:

- `python --version`
````
Python 3.9.4
````
- `pip show connexion | grep "^Version\:"`
````
Name: connexion
Version: 2.7.0
Summary: Connexion - API first applications with OpenAPI/Swagger and Flask
Home-page: https://github.com/zalando/connexion
Author: Zalando SE
Author-email: None
License: Apache License Version 2.0
Location: /venv/lib/python3.9/site-packages
Requires: jsonschema, clickclick, requests, inflection, openapi-spec-validator, PyYAML, flask
Required-by: foo-service
````

**Comment by Ruwann** [comment]
Thanks for the bug report, I can indeed reproduce it locally.

The culprit is this line, which overwrites the current scope (even if it is no longer `None`):
https://github.com/zalando/connexion/blob/2dfd57dafbedff99c0a32616079f80c21b9de6d9/connexion/operations/secure.py#L94

These `required_scopes` are then returned:
https://github.com/zalando/connexion/blob/2dfd57dafbedff99c0a32616079f80c21b9de6d9/connexion/operations/secure.py#L162

**Comment by carl-adams-planet** [comment]
Yeah, scope design is pretty open-ended in OIDC. Application implementors are pretty free to decide what particular scopes mean. While certainly not the only approach you can find, one may choose to design scopes of laddered power. If I design a scope "foo_svc.god_admin", I might want it to be accepted by the "GET /foos" endpoint in the OpenAPI spec, and not require a separate scope of "foo_svc.reader".
