### ISSUE TITLE
Add support for mutual http authorization scheme

### ISSUE THREAD

**Issue by sesa535875** [spec-first/connexion#1427]
### Description

Considering following OpenAPI :

```
openapi: 3.0.0
info:
  title: MyServer
  version: '1.0'
paths:
  /mypath:
    post:
      operationId: mymodule.my_function
      responses:
        '200':
          description: My description
      security:
        - MySecurityScheme: []
components:
  securitySchemes:
    MySecurityScheme:
      type: http
      scheme: mutual
```

And following Zalando Connexion python code :

```
import connexion

def my_function():
    return "My response"

app = connexion.FlaskApp(__name__)
app.add_api("openapi.yaml", options={"swagger_ui": False})
app.run(port=4433)
```

When executing following curl command :
`curl -X POST http://127.0.0.1:4433/mypath`

### Expected behaviour

Curl response should be :
"My response"

### Actual behaviour

Zalando Connexion writes following message :
... Unsupported http authorization scheme mutual

And curl response is :
{
  "detail": "No authorization token provided",
  "status": 401,
  "title": "Unauthorized",
  "type": "about:blank"
}

### Steps to reproduce

1. Run provided python code
2. Execute curl command

### Additional info:

Output of the commands:

- `python --version`
Python 3.8.10

- `pip show connexion | grep "^Version\:"`
Version: 2.9.0

**Comment by RobbeSneyders** [comment]
Hi @sesa535875 
Mutual authentication is currently indeed not supported.

**Comment by Ruwann** [comment]
I'm not familiar with this authentication scheme, could you provide some more information about how you would see this in connexion? Similar to API keys where the user can specify a function that will do the security check?

For future reference: https://datatracker.ietf.org/doc/html/rfc8120

**Comment by RobbeSneyders** [comment]
You can now insert your [own custom security handlers](https://connexion.readthedocs.io/en/latest/security.html#custom-security-handlers) . If you would build a handler for mutual http scheme, we'd be happy to accept it as a contribution.
