### ISSUE TITLE
Moving to a new Github organization

### ISSUE THREAD

**Issue by RobbeSneyders** [spec-first/connexion#1429]
I would like to start the discussion to move Connexion to a new Github organization as first raised in https://github.com/zalando/connexion/issues/1365#issuecomment-867644177. 

With the recent addition of new non-Zalando maintainers, I see two main benefits in this:
- It removes the responsibility from Zalando over work that is now partially steered by external people.
- It would allow non-Zalando maintainers to receive additional rights on the repo, which could speed up the development and release cycle. Currently there is a blocking issue (#1401, #1420), which we cannot move forward on without the Zalando maintainers.

Our first idea was to move to an organization with the name 'Connexion', but this name has been taken already (https://github.com/Connexion). There is no public activity by the organization, but unfortunately I cannot see a way to contact them, and Github has moved away from their previous name squatting policy where you could request transfer of inactive names. I would therefore suggest 'ConnexionAPI' or 'ConnexionOrg' as name, but curious about other suggestions.

The most important step now is to get approval from Zalando side and see how we can credit the work done by Zalando to bring connexion where it is today. @hjacobs can you provide a view on which steps we need to take to move forward with this?

**Comment by cognifloyd** [comment]
@dtkav what about using github.com/spec-first for this?

**Comment by dtkav** [comment]
sure, I'm happy to transfer ownership if folks like the name.

**Comment by RobbeSneyders** [comment]
spec-first sounds perfect to me.

**Comment by RobbeSneyders** [comment]
@dtkav could you already add @hjacobs, @Ruwann and myself as owners of the spec-first organization?

**Comment by dtkav** [comment]
@RobbeSneyders 
done

**Comment by dtkav** [comment]
I've deleted all the repositories from the org so you should be able to do the transfer. I could also transfer dtkav/swagger-ui-bundle to the organization as the primary use case is to (optionally) have "batteries included" swagger-ui in connexion.
@RobbeSneyders I saw you had a pull request to update to swagger UI v4.
FYI the release process is a little bit more complicated than copying the distributable binaries from upstream because there is a jinja template that is used to inject some settings from connexion.

**Comment by hjacobs** [comment]
@dtkav @RobbeSneyders @Ruwann I would prepare a Zalando blog post (for https://engineering.zalando.com/) explaining the move of Connexion and share a draft with you latest next week. Afterwards we can do the migration between orgs.

**Comment by hjacobs** [comment]
I will move this repository from https://github.com/zalando/connexion/ to https://github.com/spec-first/connexion/ today at ~15:30 CET if there is no veto.

GitHub help on transferring repositories for reference: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by RobbeSneyders** [comment]
Thanks @hjacobs!
