### ISSUE TITLE
Use API validation only 

### ISSUE THREAD

**Issue by ritabiniash** [spec-first/connexion#1458]
Question

Is there a way to use only the validation util without registering the API routes to the app ?

More specifically: define API'S with OpenAPI , but to register the routes natively with Flask and consume the validators that connexion generates.

**Comment by RobbeSneyders** [comment]
Hi @ritabiniash 

There is no straightforward way to do this. Connexion registers it's own routes with Flask under the hood, so they would conflict. Can you explain why you want to do this?

You can also have a look at [`jsonschema`](https://github.com/Julian/jsonschema), the framework Connexion uses for validation. However you'll probably need to reimplement a lot of `connexion` to make this work for individual routes.

**Comment by ritabiniash** [comment]
Thanks @RobbeSneyders 

I want to do this because we have an existing Flask project with routes configured by connexion. We want to add new routes that will use Flask async. Since async Flask routes are not supported, we want to still use OpenAPI for validation.

**Comment by RobbeSneyders** [comment]
Validation will also not work on async routes. Let's track this in https://github.com/spec-first/connexion/issues/1400.
