### ISSUE TITLE
MethodViewResolver inconsistent documentation/incorrect(?) behavior

### ISSUE THREAD

**Issue by jdkent** [spec-first/connexion#1466]
### Description
The [API documentation](https://connexion.readthedocs.io/en/latest/autoapi/connexion/resolver/index.html#connexion.resolver.MethodViewResolver) suggests the endpoint `/foo_bar` would translate to `FooBarView`, but [the testing suite](https://github.com/spec-first/connexion/blob/a67baa5be02c0018a2f501534fb0899a5b4e06d2/tests/test_resolver_methodview.py#L39-L179) translates `example_method` to `Example_methodView`

### Expected behaviour
`/foo-bar` -> `FooBarView`
`/foo_bar` -> `FooBarView`

### Actual behaviour
`/foo-bar` -> `Foo_barView`

### Steps to reproduce

run tests in [test_resolver_methodview](https://github.com/spec-first/connexion/blob/a67baa5be02c0018a2f501534fb0899a5b4e06d2/tests/test_resolver_methodview.py#L39-L179)

### Additional info:

[In the pep8 standard, class names should be FooBar and not Foo_bar](https://www.python.org/dev/peps/pep-0008/#class-names)

**Comment by RobbeSneyders** [comment]
Thanks for the report @jdkent.

I would say the documentation is indeed the more logical behavior to follow.
