### ISSUE TITLE
Swagger-UI GUI: Mandatory form parameters with implicit default must be changed then changed back to execute

### ISSUE THREAD

**Issue by macdjord** [spec-first/connexion#1468]
### Description

If you have a form parameter with a finite number of possible values, e.g. a boolean or a string with enum set, the 'Try it out' GUI will helpfully provide a drop-down menu to select from these values. If the field is mandatory and you do not explicitly set a default value in the spec, this drop-down will default to the first item. However, you will not be able to submit the query with this default selection; you must manually select a *different* item from the list (then select the original element again if that's the one you wanted in the first place).

### Steps to reproduce
`swagger/swagger.yaml`:
```yaml
openapi: "3.0.0"

info:
  version: "1.0.0"
  title: "foo-ms"
  license:
    name: "MIT"
  description: "Foo"

servers:
  - url: "/test"

paths:
  /foo:

    post:
      summary: "Create a foo"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: "object"
              properties:
                enabled:
                  type: "boolean"
                mode:
                  type: "string"
                  enum: ['a', 'b', 'c']
                enabled-default:
                  type: "boolean"
                  default: true
                mode-default:
                  type: "string"
                  enum: ['a', 'b', 'c']
                  default: 'a'
              required:
                - "enabled"
                - "mode"
                - "enabled-default"
                - "mode-default"
              additionalProperties: false

      responses:
        default:
          description: "Foo happens"
```

`app.py`:
```python
import connexion as _connexion
app = _connexion.App(__name__, specification_dir='swagger/')
app.add_api(
    'swagger.yaml',
    validate_responses=True,
    strict_validation=True,
    resolver=_connexion.resolver.RestyResolver('api'),
    pythonic_params=True,
)
app.run(port=5000)
```

`api/foo.py`:
```python
def post(body):
    """Placeholder"""
```

* Run `app.py`
* Visit [localhost:5000/test/ui](localhost:5000/test/ui)
* Go to the 'POST /foo' section and hit 'Try it out'
* Note that 'enabled' is set to 'true' and 'mode' is set to 'a'
* Hit 'Execute'

### Expected behaviour
The operation executes with the selected values.

### Actual behaviour
The operation is not executed; 'enabled' and 'mode' are highlighted in red. In order to execute the operation with these values, you must select a *different* item from each dropdown, then change back.

Note that if you have a parameter which has only 1 valid value, it becomes *impossible* to execute the operation - opening the drop-down and selecting the item which is already active doesn't work.

### Additional info:

- `python --version`: Python 3.7.10
- `pip show connexion | grep "^Version\:"`: Version: 2.11.2

**Comment by RobbeSneyders** [comment]
Hi @macdjord.
Thanks for the report, but I cannot reproduce using your example.
If this is an issue, it would be with [swagger-ui](https://github.com/swagger-api/swagger-ui) which Connexion depends on to generate the UI.
