### ISSUE TITLE
Defaulted POST body parameters should be added if missing in the request.

### ISSUE THREAD

**Issue by ddurham2** [spec-first/connexion#1487]
### Description
@RobbeSneyders  - first a question - Would you expect the json body arg passed to a handler to have defaulted properties added to the body if they were missing on the request?  This appears to be the intention from the looks of the code, but it's not happening in my project.  

Before I submit a PR, I wanted to ask if that's the expected behavior.   I could not find find a unit test that tests this scenario using a POST, though I do see one for GET.

If you agree, I'll alter this issue description and start working on a fix.

### Additional info:

Output of the commands:

- `python --version` 3.8.10
- `pip show connexion | grep "^Version\:"` 2.12

**Comment by RobbeSneyders** [comment]
Hi @ddurham2,
This is currently not supported, but would indeed be a nice improvement. Let's continue the discussion in #351.
