### ISSUE TITLE
CORS availability with mock server

### ISSUE THREAD

**Issue by Nolaan** [spec-first/connexion#1488]
### Description
Is it possible to have cors disabled in mock server mode?

Best Regards

### Expected behaviour

No CORS issues

### Actual behaviour
CORS enabled

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by RobbeSneyders** [comment]
Hi @Nolaan 
Could you provide some more info and a reproducible example?
