### ISSUE TITLE
Add black formatter

### ISSUE THREAD

**Issue by cognifloyd** [spec-first/connexion#1498]
### Description

I use [black](https://github.com/psf/black) in a lot of open source projects. When reviewing the code here, it would be nice to have the same format.

There is going to be a lot of PRs involved in the major rewrite of #1489. Could we reformat with black before all of that happens? Or somewhere convenient in the process?

**Comment by RobbeSneyders** [comment]
Hi @cognifloyd 

Thanks for starting the discussion. If we want to do this, now would probably be a good time indeed. I'm not explicitly for or against, but I do want to mention two downsides.
- It's hard to do it gradual, so it will obfuscate the git history a bit.
- It might be a hurdle for new contributors and lead to some additional discussion / rework on PR.

The setup can be made simple though, I really like [the way it's setup on werkzeug](https://github.com/pallets/werkzeug/blob/main/CONTRIBUTING.rst#submitting-patches).

**Comment by Ruwann** [comment]
I think it is indeed a good timing to introduce black, and I believe the downsides are fairly limited:

- There will be a lot of changes anyway with connexion 3.0. And it's possible to ignore these big revisions using `--ignore-rev`, also coming natively to Github: https://github.com/github/feedback/discussions/5033
- It should be straightforward for people to apply black to their patches as black should take care of doing the actual reformatting work?

The werkzeug way does indeed seem very nice and simple - and our contributing docs could use a small upgrade
