### ISSUE TITLE
DeprecationWarning: Passing a schema to Validator.iter_errors is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by bluebrown** [spec-first/connexion#1510]
### Description

Hi, I am observing a warning while executing my pytests. I dont think it comes from a user config but something connexion internal.

```console
/home/blue/projects/blueprints/my-app/.venv/lib/python3.9/site-packages/connexion/spec.py:50: 
DeprecationWarning: Passing a schema to Validator.iter_errors is deprecated and will be removed in a future release. 
Call validator.evolve(schema=new_schema).iter_errors(...) instead.
    for error in instance_validator.iter_errors(instance['default'], instance):
```

It seems to come from here:

https://github.com/spec-first/connexion/blob/895d3d475aec60d6dbb5d62fdc833895559f32af/connexion/spec.py#L50

### Additional info:

Output of the commands:

- `python --version` : Python 3.9.2
- `pip show connexion | grep "^Version\:"`  Version: 2.13.0

**Comment by Ruwann** [comment]
Thanks for the report, @bluebrown . It seems like this was added in `jsonschema==4.0.0` - we can bump the version and use `instance_validator.evolve()` in connexion 3.0
