### ISSUE TITLE
Why does ApiKey auth functions have a "required_scopes" argument?

### ISSUE THREAD

**Issue by itsdkey** [spec-first/connexion#1515]
### Description

This isn't a bug but a question to the developers.

I'm trying to define permission levels based on API key auth. As I read in the documentation (https://connexion.readthedocs.io/en/latest/security.html#apikey-authentication) the apiKey auth function requires 2 arguments: the apiKey itself and "required_scopes". I'm trying to use it by defining in my YML file "a workaround" (since at this moment the securitySchemes object doesn't use the scope attribute (from the OpenAPI [documentation](https://swagger.io/docs/specification/authentication/)  "Other schemes (Basic, Bearer, API keys and others) do not use scopes, so their security entries specify an empty array [] instead.").

I can define something like "x-scopes" --- so the scheme becomes valid but I really cannot use the values that I pass inside the security section on my paths.
```
  security:
    - ApiKeyAuth: [test]
```
I've checked the logs and the value is there:
```
[connexion.operations.secure][DEBUG]: ... Security: [{'TestAuth': ['test']}]
```
However, it isn't passed into the auth function itself like in OAuth2

Code from secure.py:
```
                elif security_scheme['type'] == 'apiKey':
                    scheme = security_scheme.get('x-authentication-scheme', '').lower()
                    if scheme == 'bearer':
                        bearer_info_func = self._api.security_handler_factory.get_bearerinfo_func(security_scheme)
                        if not bearer_info_func:
                            logger.warning("... x-bearerInfoFunc missing", extra=vars(self))
                            break
                        sec_req_funcs[scheme_name] = self._api.security_handler_factory.verify_bearer(bearer_info_func)
                    else:
                        apikey_info_func = self._api.security_handler_factory.get_apikeyinfo_func(security_scheme)
                        if not apikey_info_func:
                            logger.warning("... x-apikeyInfoFunc missing", extra=vars(self))
                            break

                        sec_req_funcs[scheme_name] = self._api.security_handler_factory.verify_api_key(
                            apikey_info_func, security_scheme['in'], security_scheme['name']
                        )
```

I get it that ApiKey Auth should not implement scopes although it is possible when you look at the YML file (since you define empty arrays anyways on the security level in paths). Since this parameter should be defined when creating your auth function then why aren't we really allowed to use it?

### Expected behaviour
We can use the required_scopes kwargs in our auth function

### Actual behaviour
required_scopes is always None

### Steps to reproduce

YML file:
```
    openapi: "3.0.3"
    info:
    title: TestApiAuth
    version: 1.0.0
    servers:
        - url: http://0.0.0.0:8080/api/v1.0
    paths:
        /authorized-resource:
            get:
                x-openapi-router-controller: src.api.v1.views
                operationId: auth_view
                responses:
                    "200":
                        description: The service returns this response when the API Key is valid.
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        status:
                                            type: string
            security:
               - TestAuth: [god]    # <--- you can play with it here
   
    components:
        securitySchemes:
            TestAuth:
                type: apiKey
                name: X-Auth
                in: header
                x-apikeyInfoFunc: src.api.v1.auth.auth
                x-scopes:
                    fresh: fresh token level
                    human: basic rights
                    god: all rights
```

views.py:
```
def auth_view() -> dict:
    """Return status OK if the API key is valid."""
    return {"status": "OK"}
```

auth.py:
```
def auth(token: str, required_scopes: list) -> dict:
    # here you can put a breakpoint to check the required_scopes
    return {
        "sub": {"name": "foo"},
        "token": token.value,
    }
```

### Additional info:

Output of the commands:

- `python --version`   == Python 3.9.10
- `pip show connexion | grep "^Version\:"`  == Version: 2.11.2

**Comment by Ruwann** [comment]
Hi @itsdkey, thanks for raising the issue and the detailed information!
The current behaviour of passing the `required_scopes` argument is still a remnant from a previous implementation which reused the scopes from any OAuth security scheme defined on the same operation. As of 2.13.0, the `required_scopes` argument will always return `None` for security schemes that don't support scopes. It seems that this part of the docs does not yet reflect these changes.


The reason is that [per the API 3.0 spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-requirement-object) (emphasis mine):

> Each name MUST correspond to a security scheme which is declared in the [Security Schemes](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#componentsSecuritySchemes) under the [Components Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#componentsObject). If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution, and the list MAY be empty if authorization does not require a specified scope. **For other security scheme types, the array MUST be empty**.

So, the desired behaviour you're described is not valid according to OpenAPI.

However, I understand that it may seem that connexion supports this behaviour, so this is something we definitely should address in the documentation.

**Comment by itsdkey** [comment]
Yes, if I define an OAuth security scheme then it's going to be there. However, I was just curious why I can't really use them in an API Key scheme. The curiosity came from that after calling the security_handler_factory the methods (more specific the wrappers) there allow passing scopes (even the api key one), yet the verify_api_key itself doesnt pass them.

Okay, fine - I like this answer :smile:  thanks for answering it :+1:
