### ISSUE TITLE
ValueError when parsing ref

### ISSUE THREAD

**Issue by itsdkey** [spec-first/connexion#1519]
### Description
I'm trying to update to the latest version of connexion from 2.11.2 (newest at the moment 2.13.1) and when I try to start my project I get a ValueError when parsing my yml file.

I believe this is connected with #1455

### Expected behavior
No error

### Actual behaviour
KeyError -> KeyError -> ValueError -> jsonschema.exceptions.RefResolutionError: unknown url type: './v1/paths/authorized_resource.yml

### Steps to reproduce
v1.yml
```
openapi: "3.0.3"
info:
  title: TestAPI
  version: 1.0.0
servers:
  - url: http://0.0.0.0:8080/api/v1.0
paths:
  /authorized-resource:
    $ref: './v1/paths/authorized_resource.yml'
```

authorized_resource.yml
```
get:
  x-openapi-router-controller: src.api.v1.views
  operationId: authorized_health_check
  summary: Authorized health check for testing Auth

  responses:
    "200":
      description: The service returns this response when the API Key is valid.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
    "401":
      description: Unauthorized error due to the fact of an invalid authentication.
```

### Additional info:

Output of the commands:

- `python --version`  python3.9
- `pip show connexion | grep "^Version\:"` 2.13.1

**Comment by RobbeSneyders** [comment]
I can indeed confirm that relative refs are currently not supported. However I find it strange that they would have worked on 2.11.2 since `openapi-spec-validator` dropped support for relative refs a long time ago.

We're tracking everything related to relative refs in #254.

**Comment by alexandr-san4ez** [comment]
@itsdkey try this method - https://github.com/spec-first/connexion/issues/254#issuecomment-1133843523
