### ISSUE TITLE
Improve and update documentation for version 3.0

### ISSUE THREAD

**Issue by RobbeSneyders** [spec-first/connexion#1531]
Proposed structure:

- [x] Index (#1646)
- [x] Getting started (#1701)
- [x] Middleware (#1706)
- [x] Routing (#1738)
- [x] Swagger UI (#1739)
- [x] Request handling (#1741)
- [x] Response handling (#1742)
- [x] Validation (#1743)
- [x] Security (#1764)
- [x] Context (#1747)
- [x] Exceptions (#1758)
- [x] CLI (#1763)
- [x] Lifespan (#1759)
- [x] Testing (#1760)
- [x] Migrating from 2 to 3 (#1646)

We should also
- [ ] Update the README (#1769)
- [x] Write a blogpost about the migration

**Comment by jagadeeshgarvis** [comment]
Is there any examples for uploading and accessing files. I am facing issues regarding this in connexion 3.0.

`await connexion.request.form()` makes the application go into a limbo..
