### ISSUE TITLE
Remove `pass_context_arg_name` argument

### ISSUE THREAD

**Issue by RobbeSneyders** [spec-first/connexion#1532]
I propose to remove the `pass_context_arg_name` argument and fix the name under which the context is passed. This parameter is passed often between internal functions and classes, which is not worth the benefit of having it configurable.

**Comment by Ruwann** [comment]
We'll have to take into account name collisions. E.g. if there is a parameter called `context` in the spec - then this could cause trouble if we want to pass the request context as `context`
