### ISSUE TITLE
filtering operations in swagger ui

### ISSUE THREAD

**Issue by rjkooijman** [spec-first/connexion#1543]
### Description
For usage of my API the client has to authorize using a API-key. For some specific operations/paths I want to implement additional authentication for specific clients/partners. For example /test is available for everyone and /test2 isn't unless you're authenticated (type isn't important now, lets say basic HTTP). In swagger UI, all the operations are listed. You can't call them but you can always see them. Is there a way to configure connexion/swagger-ui to filter the operations which you aren't authenticated for out of swagger-ui? As soon as the client authenticates, the operations are listed in swagger-ui.

APIKeyHeader is defined for security on API level, but defining additional security for some operations doesn't automatically filter them out of swagger-ui.

### Additional info:

Output of the commands:

- `python --version`
  -  3.6.5
- `pip show connexion | grep "^Version\:"`
  - 2.13.0

**Comment by rjkooijman** [comment]
I found that it isn't possible on the server, but it is using plugins in swagger. Is there a way to make swagger load the plugin using connexion?

**Comment by rjkooijman** [comment]
@RobbeSneyders https://github.com/swagger-api/swagger-ui/issues/4326#issuecomment-377041063

It's probably still only a solution for swagger-ui. My guess is that when users download the openapi specification (openapi.json) the 'private' endpoints are still available in the specification.

**Comment by RobbeSneyders** [comment]
This would indeed only affect swagger-ui. 

If you want to use this (or another similar) plugin, you probably need to edit the static swagger-ui files yourself and point connexion to them instead of using the packaged ones.
