### ISSUE TITLE
unable to resolve schema from another file

### ISSUE THREAD

**Issue by bluebrown** [spec-first/connexion#1548]
### Description

I am trying to modularize my open api spec. I have a file with some common definitions. I am trying to reference it in another file like so:

```yaml
$ref: "common.yaml#/components/schemas/Error"
```

### Expected behaviour

I expect that it works.

### Actual behaviour

I am getting an error.  `sonschema.exceptions.RefResolutionError: unknown url type: 'common.yaml'`

### Additional info:

Output of the commands:

- `python --version`: Python 3.9.2
- `pip show connexion | grep "^Version\:"` : Version: 2.13.1

**Comment by RobbeSneyders** [comment]
Hi @bluebrown 
Please refer to #254
