### ISSUE TITLE
support method view decorator

### ISSUE THREAD

**Issue by bluebrown** [spec-first/connexion#1549]
Hi, I am trying to use `MethodView` decorator. 

I found out that the regular decorator list from the `MethodView` is not called, since .as_view is never called. 

I can see in one of the example, there is a field called method_decorators  but I cannot find any reference in the code base. It appears to be unused. https://github.com/spec-first/connexion/blob/b561ecfdaacd7606d1398512762b946e2d778c74/examples/openapi3/methodresolver/api/petsview.py#L11

Is this possible?

If its not possible, we could maybe add it to the `MethodResolver`. I managed to kind of get it working by modifying the code.

```python
if view is None:
    view = view_cls()
    self.initialized_views.append(view)
func = getattr(view, meth_name)

# I have added this:
# if the view has decorators, apply them to the function
# since .as_view() is never called
if view.decorators:
    for decorator in view.decorators:
        func = decorator(func)

# Return the method function of the class
return func
```

I have added this to the code here https://github.com/spec-first/connexion/blob/b561ecfdaacd7606d1398512762b946e2d778c74/connexion/resolver.py#L241

**Comment by RobbeSneyders** [comment]
Hi @bluebrown 
I don't understand the issue. Could you please provide a minimal reproducible example to show what the issue is?

**Comment by bluebrown** [comment]
Hi, sorry. I am trying to use a method view decorator as documented here:https://flask.palletsprojects.com/en/2.1.x/views/#decorating-views


### main.py

```python
import connexion
from connexion.resolver import MethodViewResolver
from flask.views import MethodView


def test_decorator(f):
    """
    based on https://flask.palletsprojects.com/en/2.0.x/views/#decorating-views
    """
    print("Test decorator 1 registered")

    def decorator(*args, **kwargs):
        print("Test decorator 1 running")
        return f(*args, **kwargs)

    return decorator


class TestView(MethodView):
    decorators = [test_decorator]

    def search(self):
        return "ok", 200


app = connexion.FlaskApp(__name__, specification_dir="./")
app.add_api("spec.yaml", resolver=MethodViewResolver("main"))
app.run(port=8080)
```

### spec.yaml

```yaml
openapi: "3.0.2"
info:
  title: Test
  version: "1.0"
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
```

---

I cannot see either of the print statements. After some digging, I found out that the reason for this is that the decorators in this list are registered when calling [`View.as_view`](https://flask.palletsprojects.com/en/2.1.x/api/#flask.views.View.as_view).  The source code for this method looks like this:

```python
@classmethod
def as_view(
    cls, name: str, *class_args: t.Any, **class_kwargs: t.Any
) -> t.Callable:
    """Converts the class into an actual view function that can be used
    with the routing system.  Internally this generates a function on the
    fly which will instantiate the :class:`View` on each request and call
    the :meth:`dispatch_request` method on it.

    The arguments passed to :meth:`as_view` are forwarded to the
    constructor of the class.
    """

    def view(*args: t.Any, **kwargs: t.Any) -> ResponseReturnValue:
        self = view.view_class(*class_args, **class_kwargs)  # type: ignore
        return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)

    if cls.decorators:
        view.__name__ = name
        view.__module__ = cls.__module__
        for decorator in cls.decorators:
            view = decorator(view)

    # We attach the view class to the view function for two reasons:
    # first of all it allows us to easily figure out what class-based
    # view this thing came from, secondly it's also used for instantiating
    # the view class so you can actually replace it with something else
    # for testing purposes and debugging.
    view.view_class = cls  # type: ignore
    view.__name__ = name
    view.__doc__ = cls.__doc__
    view.__module__ = cls.__module__
    view.methods = cls.methods  # type: ignore
    view.provide_automatic_options = cls.provide_automatic_options  # type: ignore
    return view
```

But connexion does not call this function. It only instantiates the class, probably to create any state that the methods rely on. https://github.com/spec-first/connexion/blob/c71b1169f6e72eb503a132cd90a533a5c8cdad82/connexion/resolver.py#L240

Therefore, this decorator list does not work. In the mentioned example, there is a field called method_decorators, but it's empty, and I cannot find any evidence in the code showing that this list would be used in some way.

https://github.com/spec-first/connexion/blob/b561ecfdaacd7606d1398512762b946e2d778c74/examples/openapi3/methodresolver/api/petsview.py#L11

So, I think this feature is not supported by connexion at the moment. 

I came up with a naive way to support it, that is, as mentioned above, to mimic the decorator behaviour from as view inside the method resolver.

```python
if view.decorators:
    for decorator in view.decorators:
        func = decorator(func)
```

**Comment by RobbeSneyders** [comment]
Thanks for the detailed info!
This indeed doesn't seem supported, and I agree that it would be good to support this functionality with the `MethodViewResolver`.

I would prefer to call the `as_view()` method instead of copying specific partial behavior though. I had a quick look and I don't see an immediate reason why this wouldn't be possible.

Feel free to submit a PR if you'd like!

**Comment by bluebrown** [comment]
Hi, I dont think calling as_view is good. There come serveral problems with it. 

If you call this, then you should use the returned view function to route the requests, because it is this view function that is decorated, not the individual methods.

```python
def view(*args: t.Any, **kwargs: t.Any) -> ResponseReturnValue:
    self = view.view_class(*class_args, **class_kwargs)  # type: ignore
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
```

Connexion doesn't do that, since it's grabbing the individual methods, from the view class.

https://github.com/spec-first/connexion/blob/c71b1169f6e72eb503a132cd90a533a5c8cdad82/connexion/resolver.py#L242

If you try to return the view function instead, you get conflicts with the method names. 

```python
view = None
for v in self.initialized_views:
    if v.view_class == view_cls:
        view = v
        break
if view is None:
    view = view_cls.as_view(view_name)
    self.initialized_views.append(view)
return view
```

For example, connexion uses `search` and `get` to differentiate between a list operation and one that gets and item by id. The standard implementation of `dispatch_request` uses the http method to determine which method of the view to call.

```python
class MethodView(View, metaclass=MethodViewType):
    def dispatch_request(self, *args: t.Any, **kwargs: t.Any) -> ResponseReturnValue:
        meth = getattr(self, request.method.lower(), None)

        # If the request method is HEAD and we don't have a handler for it
        # retry with GET.
        if meth is None and request.method == "HEAD":
            meth = getattr(self, "get", None)

        assert meth is not None, f"Unimplemented method {request.method!r}"
        return current_app.ensure_sync(meth)(*args, **kwargs)
```

So, one had to implement a custom `MethodView` class or override the method otherwise, in order to align the routing behaviour so that a `search` method is looked up for list operations.

So I am not sure whether it would be easier to opt for this and try to work around `dispatch_request` or decorating the *popped* functions with the decorators from the list. Like shown above.

```python
if view.decorators:
    for decorator in view.decorators:
        func = decorator(func)
```

**Comment by bluebrown** [comment]
On the other hand, such MethodView decorators might expect to be initialized only once. If you decorate with it, you break this assumption. 

For example, the below would throw an error.

```python
from prometheus_client import Summary, make_wsgi_app

REQUEST_TIME = Summary("request_processing_seconds", "Time spent processing request")

def with_metrics(f):
    @REQUEST_TIME.time()
    def decorator(*args, **kwargs):
        return f(*args, **kwargs)

    return decorator
```

```
ValueError: Duplicated timeseries in CollectorRegistry: {'request_processing_seconds_created', 'request_processing_seconds_sum', 'request_processing_seconds_count', 'request_processing_seconds'}
```

**Comment by bluebrown** [comment]
Well the issue here is actually, importing the file twice, and calling `Summary` multiple times. Its not the decorator. Importing the initialized `Summary` from another file, fixes the error. 

The point, might still hold up. Only in this case, it wasn't the actual problem.

**Comment by bluebrown** [comment]
If we want to call `as_view`, the something like this could work

```python
def dispatch_request(self, *args, **kwargs):
    meth_name = request.endpoint.split("_")[-1]
    meth = getattr(self, meth_name, None)
    return current_app.ensure_sync(meth)(*args, **kwargs)

class MethodViewResolver(RestyResolver):
    # ...
    def resolve_function_from_operation_id(self, operation_id):
        # ...
        for v in self.initialized_views:
            if v.view_class == view_cls:
                view = v
                break
        if view is None:
            setattr(view_cls, "dispatch_request", dispatch_request)
            view = view_cls.as_view(view_name)
            self.initialized_views.append(view)
        return view
```

**Comment by RobbeSneyders** [comment]
I'm not sure if we want to use the `search` endpoint here, since it doesn't match the Flask `MethodView` behavior. It would be great if we could just leverage the default `dispatch_request` method.

> If you call this, then you should use the returned view function to route the requests, because it is this view function that is decorated, not the individual methods. Connexion doesn't do that, since it's grabbing the individual methods, from the view class.

We don't need to do this. We can use the `view` returned by `as_view` instead as you did in your latest comment.

> If you try to return the view function instead, you get conflicts with the method names.

Where do we get a name conflict? I think we can still use `search` for the generated `operation_id`. The `search` and `get` operations will be registered as two separate routes since their path is different. But since we're actually registering the `dispatch_request` function, both will be dispatched to the `get` method.

```
endpoint             operation_id          registered func       method
GET /route       ->  RouteView.search  ->  dispatch_request  ->  get
GET /route/{id}  ->  RouteView.get     ->  dispatch_request  ->  get
```

Or am I missing something?

**Comment by bluebrown** [comment]
Wouldn't that break all user code that has a search method, since they need to merge it with the get method? It would also make it impossible to use the id as required arument for the get method.

**Comment by RobbeSneyders** [comment]
Yes, it would, but I don't think it's a big issue.
- The resolver is pluggable, so it's easy to provide a custom one with the current behavior. We could even still provide it as part of connexion.
- It has no impact on the API spec. So while this is a breaking change for connexion, it shouldn't be for APIs inplemented with connexion.
- The new behavior would align with the Flask `MethodView` behavior.
- We're currently working towards a new major version (3.0), so now would be a good time to do it.
