### ISSUE TITLE
Release 2.13.2

### ISSUE THREAD

**Issue by rickpr** [spec-first/connexion#1555]
### Description
It's been 49 days since the last release - usually releases have been about once a month. There have been some good fixes and enhancements in v2 since then.

Can we get a version bump?

### Expected behaviour
This is expected, it's a release request.

### Actual behaviour
Still on 2.10 to wait for fixes in that are in the v2 branch but not 2.13.1.

### Steps to reproduce
`pip install connexion`

### Additional info:

Output of the commands:

- `python --version`
- `Python 3.8.12`
- `pip show connexion | grep "^Version\:"`
- `Version: 2.10.0`

**Comment by RobbeSneyders** [comment]
Hi @rickpr,
We just released [2.14.0](https://github.com/spec-first/connexion/releases/tag/2.14.0).
