### ISSUE TITLE
Take advantage of type hints

### ISSUE THREAD

**Issue by aholmes** [spec-first/connexion#1557]
### Description

Type hints allow for safer code and, in some cases, self-documenting code. Connexion currently lacks type hints, which hurts its usability. In an effort to avoid a debate or argument over whether static typing is advantageous in a code base, I ask to consider type hints for the purpose of making the API more discoverable and simpler to use, and to enable type safety within code bases that do care about it.

As a simple example, consider the following. Here, we're calling `add_api` without a guarantee that 1. what we're using as parameters are correct and 2. that the documentation is up-to-date with the implementation.
![image](https://user-images.githubusercontent.com/277061/175100926-bdf9ce90-6144-4eaf-aa05-8af005043c6b.png)

Of note, the static types are already documented in the docblock comment. Using these types as Python type hints instead tends to require less effort to maintain (tooling helps with this), and goes a lot further toward the capabilities of tooling to use those type hints. In fact, although this is inconsequential here, the order of parameters in the docblock is inconsistent with the order of arguments for the method parameters.

Surprisingly, despite the docblocks, my tooling (pyright/pylance, vs code) wasn't able to offer up the parameters I was typing.
![image](https://user-images.githubusercontent.com/277061/175101393-36ecd977-66ae-4edd-a0db-2a9fb96c1790.png)

### Expected behaviour

Ideally, type hints would grant our tooling the ability to produce something like this.

![image](https://user-images.githubusercontent.com/277061/175108900-0d5ff0e3-6eb5-4f58-b2a3-f19667fe2abe.png)

![image](https://user-images.githubusercontent.com/277061/175108979-4fac092c-b487-4ae1-bd7f-d48a7f4e9656.png)

The change that enabled this was just to use type hints with the method parameters.

```python
    def add_api(
        self,
        specification: pathlib.Path | str | Dict[Any, Any],
        base_path: str | None = ...,
        arguments: Dict[Any, Any] | None = ...,
        auth_all_paths: bool = ...,
        validate_responses: bool = ...,
        strict_validation: bool = ...,
        resolver: Resolver | types.FunctionType = ...,
        resolver_error: int | None = ...,
        pythonic_params: bool = ...,
        pass_context_arg_name: str | None = ...,
        options: Dict[Any, Any] = ...,
        validator_map: Dict[Any, Any] = ...,
    ) -> AbstractAPI: ...
```

### Actual behaviour

Static type guarantees in Connexion are spurious and sometimes problematic for applications that attempt to remain type safe.

### Additional info:

In 2018 #716 was closed. In 2022, we now have much more advanced static type tooling for Python and clearer understandings of how to best use static types within Python to write higher quality code. Regardless of the claims asserted to justify not including type hints for the benefit of Connexion itself, type hints will increase the usability of Connexion for users of the library.

Output of the commands:

- `python --version` `Python 3.10.2`
- `pip show connexion | grep "^Version\:"` `Version: 2.13.1`

**Comment by RobbeSneyders** [comment]
Hi @aholmes 
We are very much convinced of the benefit of type hints. We are adding typing with new changes and run `mypy` in non-failing mode in our CI to track progress. Any contributions towards this are welcome.

Closing this one, as we track this in https://github.com/spec-first/connexion/issues/1111.

**Comment by aholmes** [comment]
Awesome! Thanks. I missed #1111.
