### ISSUE TITLE
Pytest generates 2,464 warnings that should be investigated

### ISSUE THREAD

**Issue by cclauss** [spec-first/connexion#1576]
### Description

Our GitHub Actions run pytest which generates a lot of warnings that should be investigated and remedied.

From the GitHub Action output:
> ================ 467 passed, 2464 warnings in 111.63s (0:01:51) ================

### Additional info:

The output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by RobbeSneyders** [comment]
Thanks @cclauss.
These mostly seem to be deprecation warnings from Flask:
```
DeprecationWarning: 'app.json_encoder' is deprecated and will be removed in Flask 2.3. Customize 'app.json_provider_class' or 'app.json' instead.
```
```
DeprecationWarning: 'JSONEncoder' is deprecated and will be removed in Flask 2.3. Use 'Flask.json' to provide an alternate JSON implementation instead.
```
```
DeprecationWarning: Setting 'json_encoder' on the app or a blueprint is deprecated and will be removed in Flask 2.3. Customize 'app.json' instead.
```
```
DeprecationWarning: '_request_ctx_stack' is deprecated and will be removed in Flask 2.3.
```
```
DeprecationWarning: '_request_ctx_stack' is deprecated and will be removed in Flask 2.3. Use 'g' to store data, or 'request_ctx' to access the current context.
```

One from Starlette:
```
DeprecationWarning: ExceptionMiddleware is deprecated on `starlette.exceptions`. Import it from `starlette.middleware.exceptions` instead.
```

And then some of our own, which are logical, since we still want to test the deprecated behavior until it is completely removed.
