### ISSUE TITLE
openapi examples won't work for me

### ISSUE THREAD

**Issue by passani** [spec-first/connexion#1578]
### Description

Example won't work for me.

### Expected behaviour

Flask running and exposing Swagger UI

### Actual behaviour

```
$ ./app.py
Traceback (most recent call last):
  File "./app.py", line 30, in <module>
    resolver=MethodViewResolver(
  File "/home/passani/.local/lib/python3.8/site-packages/connexion/resolver.py", line 196, in __init__
    super(MethodViewResolver, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'class_arguments'
```

### Steps to reproduce

```$ ./app.py```

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

```
$ python --version
Python 3.8.10
$ pip show connexion | grep "^Version\:"
Version: 2.14.1
```

**Comment by RobbeSneyders** [comment]
Hi @passani, please try the [examples on the 2.14.1 version](https://github.com/spec-first/connexion/tree/2.14.1/examples) of the repository. The examples on main have been updated to reflect unreleased changes.
