### ISSUE TITLE
Adding JSight API support

### ISSUE THREAD

**Issue by andrew-platonov** [spec-first/connexion#1580]
### Description

What do you think about adding support of **JSight API** language, which you can use instead of **OpenAPI**?

This language is much more easier for Spec First approach, than OpenAPI.

For more information on JSight API language: https://github.com/jsightapi/online-editor-frontend#scroll--jsight-api-language
Also here: https://jsight.io

### Expected behaviour

Support of JSight API language for service contract definition.

### Actual behaviour

No JSight API language support.

**Comment by RobbeSneyders** [comment]
Marking as a won't fix as jsight doesn't have the popularity to warrant this kind of effort.
