### ISSUE TITLE
Malformed __version__

### ISSUE THREAD

**Issue by cibio** [spec-first/connexion#1594]
In the current version of the main-branch, a string literal surrounded by double quotes is assigned to the `__version__`-attribute 
([see](https://github.com/spec-first/connexion/blob/fc003ca1402814fb5c543e505466ca0622ddc377/connexion/__init__.py#L34)). Yet, in your [setup.py](https://github.com/spec-first/connexion/blob/fc003ca1402814fb5c543e505466ca0622ddc377/setup.py?plain=1#L17) you expect the literal to be surrounded by single quotes. This causes the version to not be properly read.

The bug has been introduced with the following commit: 600ed4ed94a3c9868370aa0d6e0c40a5ebd455be.

**Comment by Ruwann** [comment]
Thanks for the report, @cibio !

It seems indeed that the black formatting changed the quotes but this wasn't updated in the `setup.py`.

**Comment by RobbeSneyders** [comment]
No longer relevant after https://github.com/spec-first/connexion/pull/1628
