### ISSUE TITLE
connexion.FlaskApp.add_api() validate_responses enables also strict_validation.

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [spec-first/connexion#1602]
### Description
Setting `validate_responses=True` in `connexion.FlaskApp.add_api()` also enables parameters validation as if `strict_validation` is enabled.

### Expected behaviour
`validate_responses=True` should only enable response validation, without validating parameters.

### Actual behaviour
Setting `validate_responses=True` in `connexion.FlaskApp.add_api()` also enables parameters validation as if `strict_validation` is enabled.

### Steps to reproduce
Use this example:

```Python
main_app = FlaskApp(import_name='Some name here', debug=debug_mode, specification_dir='path/to/spec_dir/')
main_app.add_api(specification='path/to/spec_dir/openapi.yaml',validate_responses=True,strict_validation=False)
```

### Additional info:

Output of the commands:

- `python --version` = Python 3.9.2
- `pip show connexion | grep "^Version\:"` = Version: 2.13.1

**Comment by RobbeSneyders** [comment]
Hi @MiltiadisKoutsokeras, could you provide a minimal reproducible example?

Note that parameter validation is enabled by default. `strict_validation` only controls if parameters not defined in the spec are rejected.
