### ISSUE TITLE
Ability to pass arguments to flask's MethodViews while using MethodViewResolver

### ISSUE THREAD

**Issue by mmohaveri** [spec-first/connexion#1605]
### Description

I need a way to initialize MethodView objects when using `MethodViewResolver ` as far as I was able to infer from the code, currently there's no way to pass arguments to `__init__` function of a `MethodView` when using `MethodViewResolver`.

I suggest that MethodViewResolver stores all of its `*args` and `**kwargs` and pass them to the `MethodView` class when trying to construct it.

**Comment by RobbeSneyders** [comment]
Hi @mmohaveri 

This will be possible in Connexion 3.0, see [here](https://connexion.readthedocs.io/en/latest/routing.html#automatic-routing-with-methodviewresolver). On Connexion 2.X this is unfortunately not possible.
