### ISSUE TITLE
restyresolver example PUT not working as expected

### ISSUE THREAD

**Issue by strobelight** [spec-first/connexion#1608]
### Description
Having issue with restyresolver example.

After setting up 2 pets using POST, confirming with GET, I attempted to use PUT to update one, and get a 400 due to read-only property.

### Expected behaviour
Desired pet attributes changed.

### Actual behaviour
validation error: Property is read-only - 'id'

### Steps to reproduce
- create container with python 3.8.2, update, upgrade
- `pip install connexion[swagger-ui]`
- clone connexion tag 2.14.1
- build and start container mounting the examples, binding port 9090:9090
- cd examples/openapi3/restyresolver
- start resty.py
- access localhost:9090/v1.0/ui
- perform GET confirm empty response
- perform POST twice with different names and tags
- perform GET confirm 2 entries
- perform PUT using default body assuming it's different from the corresponding id from a GET
- get validation error

### Additional info:

Output of the commands:

- `python --version`
  Python 3.8.2
- `pip show connexion | grep "^Version\:"`
  Version: 2.14.1

**Comment by RobbeSneyders** [comment]
Hi @strobelight,

This PUT behavior for read-only properties is discussed here: https://github.com/spec-first/connexion/issues/942. Now would be a good time to change this behavior for version 3.0. We'd welcome a PR.

**Comment by strobelight** [comment]
I'm a newbie to connexion, and just wanted the examples to work, so that I could follow similar coding practices in my own code that might use it.
