### ISSUE TITLE
How to validate method at operationId matches openapi schema

### ISSUE THREAD

**Issue by ReallyLiri** [spec-first/connexion#1614]
Is there any way to statically check, ahead of making api calls, that a method defined as the `operationId` of some path actually matches the schema specified by openapi manifest?

**Comment by RobbeSneyders** [comment]
This is currently only done at runtime. In theory it would be possible to do at startup as well.

**Comment by ReallyLiri** [comment]
Could you point me to where its done at runtime?

**Comment by RobbeSneyders** [comment]
We don't even really validate the method signature. We just inspect it to provide the unpacked arguments.

On main (v3.X):
https://github.com/spec-first/connexion/blob/main/connexion/decorators/parameter.py#L38
On v2.X (current release):
https://github.com/spec-first/connexion/blob/v2/connexion/decorators/parameter.py#L79
