### ISSUE TITLE
Extend validate_responses to detect use of HTTP response code not in OpenAPI spec

### ISSUE THREAD

**Issue by chrisinmtown** [spec-first/connexion#1623]
### Description

Setting the `validate_responses` parameter to `True` in the `add_api` function is valuable for detecting response content bodies that do not meet the specification. Please extend the feature to cover the HTTP status code also. For example, if the specification says an endpoint returns `200` but the code actually returns `201`, a validation exception should be raised.

### Expected behaviour

With response validation enabled, Connexion raises an exception when the server responds with a HTTP status code not listed in the OpenAPI spec.

### Actual behaviour

With response validation enabled, Connexion raises *no* exception when the server responds with a HTTP status code not listed in the OpenAPI spec. FWIW the Swagger UI complains "Undocumented", which is easy to miss.

### Steps to reproduce

Run the example shown below. Use the Swagger UI to request `/version`.  The code answers an object with code 201, which is not in the open API spec, and connexion passes it thru.  I would like the server to raise 500, which is what happens if I botch the response body, for example by mis-spelling the `version` tag.

### Additional info:

    % python --version
    Python 3.9.12
    % pip show connexion | grep "^Version\:"
    Version: 2.14.1

Thanks in advance for considering this!

**Comment by chrisinmtown** [comment]
Here's a small self-contained example that demonstrates the situation.
File `openapi.yml`:
```
openapi: "3.0.0"
  
info:
  version: "0.0.0"
  title: "Connexion status code validation"
    
servers:
  - url: "/"

paths:
  /version:
    get:
      summary: Get the server version
      tags:
        - Admin
      operationId: api.get_version
      responses:
        200:
          description: Server version
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    description: SemVer
                    type: string
                required:
                  - version
```
File `api.py`:
```
#!/usr/bin/env python3

def get_version() -> tuple:
    rsp = {
        'version': '0.0.0',
    }
    return rsp, 201
```
File `scce_codeval.py`:
```
#!/usr/bin/env python3
import connexion

cnx = connexion.FlaskApp(__name__)
cnx.app.config['ENV'] = 'development'
cnx.add_api('openapi.yml', validate_responses=True)
cnx.run()
```

**Comment by Ruwann** [comment]
I'm not convinced that an error should be raised when a response is returned that is not listed in the API spec:

From [the spec on responses](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#responses-object):

> A container for the expected responses of an operation. The container maps a HTTP response code to the expected response.

> The documentation is not necessarily expected to cover all possible HTTP response codes because they may not be known in advance. However, documentation is expected to cover a successful operation response and any known errors.


However, I agree that it can be useful to be able to extend the response validation to check for unknown response. Not sure on the best way to implement it in terms of connexion API as the `validate_responses` is currently a bool.

**Comment by RobbeSneyders** [comment]
Agree with @Ruwann that we can't add this as default behavior since it doesn't follow the spec. You can now easily [plug in custom validators](https://connexion.readthedocs.io/en/latest/validation.html#custom-validators) though to change the validation behavior.
