### ISSUE TITLE
Servers URL / basepath is filled out erroneously.

### ISSUE THREAD

**Issue by julien-lecomte** [spec-first/connexion#1625]
### Description

Similar to https://github.com/spec-first/connexion/issues/1622, the expected value of "Servers" used by the "Try it out" feature is incorrect.

In the following example, I want api to be in "/api", along with the support files. When I curl the API endpoint it works fine. When I access the UI at '/api/ui', the try it out button will have an url with double '/api/api' route, thus executing a Not Found.

Sample openapi.yml:
```
---
#
# https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md
#
openapi: "3.0.0"
  
# set some required defaults
info:
  version: "0.0.0"
  title: "Flasket OpenAPI Server"
  description: None 
    
servers:
  - url: "/"

paths:
  /api/metrics:
    get:
      operationId: "api.metrics.get"
      summary: "Return metrics."
      description: "Return prometheus type metrics."
      responses:
        200:
          description: "OK"
          content:
            text/plain:
              schema:
                type: string
                example: |
                  # HELP permission_helper_api_service_status Static value to imply service is up
                  # TYPE permission_helper_api_service_status gauge
                  permission_helper_api_service_status 1
```

Sample app.py
```
#!/usr/bin/env python3
import connexion

app = connexion.FlaskApp(__name__, specification_dir='api')
app.add_api('openapi.yml',
  strict_validation=True,
  validate_responses=True,
  options={
    "openapi_spec_path": "/api/openapi.json",
    "swagger_url": "/api/ui",
    "swagger_ui":   True,
    "swagger_spec": True,
  },
)
app.run(port=8080)
```

### Expected behaviour

Servers to be either blank, or "/", but not "/api". This will make the TryItOut feature work again.

### Actual behaviour

Servers contain '/api'.

### Additional info:
- `python --version` : Python 3.9.2
- `pip show connexion | grep "^Version\:"`: Version: 2.14.1

**Comment by RobbeSneyders** [comment]
Thanks for the report @julien-lecomte, this is fixed on main and will be in v3.
