### ISSUE TITLE
Incorrect link in documenation

### ISSUE THREAD

**Issue by DamianGiebas-Xebia** [spec-first/connexion#1633]
### Description
Link in documentation is not a link I was looking for.
In this section - https://connexion.readthedocs.io/en/latest/security.html#bearer-authentication-jwt
I was click on link [minimal JWT example application](https://github.com/zalando/connexion/tree/main/examples/openapi3/jwt)

### Expected behaviour
Page with example

### Actual behaviour
Enduser landed on cool 404 page

### Steps to reproduce
- go [here](https://connexion.readthedocs.io/en/latest/security.html#bearer-authentication-jwt)
- click on [minimal JWT example application](https://github.com/zalando/connexion/tree/main/examples/openapi3/jwt)
- you landed here: https://github.com/spec-first/connexion/tree/main/examples/openapi3/jwt

**Comment by RobbeSneyders** [comment]
Thanks @DamianGiebas-Xebia. We still need to update the documentation for v3, which is the current main branch (#1531)
