### ISSUE TITLE
Extraneous  app.run(...) argument in most examples?

### ISSUE THREAD

**Issue by ag-forge** [spec-first/connexion#1650]
### Description
Running examples from the `examples/ folder` causes exception.

### Expected behaviour
For examples/helloworld:
```
$ python hello.py
 * Serving Flask app 'hello'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.10.121:8080
Press CTRL+C to quit
```
This dump is produced after modifying `hello.py` thus (remove first argument to `app.run`):
```
$ git diff .
diff --git a/examples/helloworld/hello.py b/examples/helloworld/hello.py
index 7ba26d6..f0b84a5 100755
--- a/examples/helloworld/hello.py
+++ b/examples/helloworld/hello.py
@@ -13,4 +13,4 @@ app.add_api("swagger.yaml", arguments={"title": "Hello World Example"})


 if __name__ == "__main__":
-    app.run(f"{Path(__file__).stem}:app", port=8080)
+    app.run(port=8080)

```
### Actual behaviour
```
$ python hello.py
Traceback (most recent call last):
  File "/home/ag/exp/connexion/connexion/examples/helloworld/hello.py", line 16, in <module>
    app.run(f"{Path(__file__).stem}:app", port=8080)
TypeError: run() got multiple values for argument 'port'

```
### Steps to reproduce
```
cd examples/helloworld
python hello.py

```
Similar for almost all other examples (not the one for sqlalchemy)

### Additional info:

Output of the commands:

- `python --version`: 3.9.15
- `pip show connexion | grep "^Version\:"`: Version: 2.14.2

The documentation/guides for connexion does not mention the first argument to `app.run` seen in the examples. So is this argument simply something left over from earlier releases?

**Comment by RobbeSneyders** [comment]
Hi @ag-forge, these are compatible with the current main version.

Please check the examples for the release that you are using:
https://github.com/spec-first/connexion/tree/2.14.2

**Comment by ag-forge** [comment]
Of course!

Yes, I was using main. Using version 2.14.2, the examples work like a charm.

Den tor. 23. feb. 2023 kl. 15.19 skrev Robbe Sneyders <
***@***.***>:
