### ISSUE TITLE
Pre-flight OPTION request requires auth token

### ISSUE THREAD

**Issue by alfechner** [spec-first/connexion#1651]
I've got a POST route. My browser sends an OPTION pre-flight request. The request is replied with an 401 and the log output: `No auth provided. Aborting with 401.`.

AFAIK pre-flight requests never send auth information. Is the behaviour in Connexion intended?

**Comment by RobbeSneyders** [comment]
Hi @alfechner,
Could you please provide a minimal reproducible example and information on the version you're running?

**Comment by RobbeSneyders** [comment]
Closing due to lack of response. Feel free to re-open with a minimal reproducible example.
