### ISSUE TITLE
Connexion 3.0.0a2, Starlette, on_startup and on_shutdown

### ISSUE THREAD

**Issue by SpudInNZ** [spec-first/connexion#1672]
### Description
Using a Starlette app with Connexion 3, startup and shutdown handlers are not called. 

I understand that Connexion uses/wraps Starlette Router, but the question remains; how to implement startup and shutdown handlers. As well, if we want to use the vanilla `connexion.AsyncApp`, what's the recommended way of adding handlers for lifecycle events?

### Expected behaviour

```
def on_startup():
    logging.info("Starting up")
def on_shutdown():
    logging.info("Shutting down")
app = Starlette(on_startup=[on_startup], on_shutdown=[on_shutdown])
app = connexion.ConnexionMiddleware(app)
app.run(f"{Path(__file__).stem}:app", host="0.0.0.0", port=8082, workers=1, reload=False)

```
The on_startup and on_shutdown handlers should be called as part of server lifecycle.

### Actual behaviour

The on_startup and on_shutdown are ignored/never called.

### Steps to reproduce
Shown above.

### Additional info:

Output of the commands:

Python 3.11.2
Connexion 3.0.0a2

**Comment by RobbeSneyders** [comment]
Thanks for the report @SpudInNZ.
Submitted #1673 to fix this.

**Comment by SpudInNZ** [comment]
Thanks for the fast turnaround @RobbeSneyders 

I did modify the question to ask how we should implement lifecycle handlers for the vanilla `connexion.AsyncApp`. Do you have any thoughts about that?

**Comment by RobbeSneyders** [comment]
Lifecycle handlers are currently not available on the `AsyncApp`.

There's two ways you could already do this:
- Register them on the underlying `Router`, although I'd like to prevent having to access the internals
- Add a custom middleware which handles the `lifecycle` events

I agree that we should provide this in an easier way though, for which I see three options:
- Build on top of `Starlette` `Lifecycle` and register it on the underlying `Router` ourselves. If we do this, we should only support the generator functions which are now recommended in the [Starlette docs](https://www.starlette.io/lifespan/)
- Implement lifecycle events on top of the ASGI interface natively in the `AsyncApp`
- Implement lifecycle events on top of the ASGI interface natively in a separate middleware

I'll have to look into what makes most sense.

**Comment by RobbeSneyders** [comment]
See relevant discussion on Starlette: https://github.com/encode/starlette/discussions/2067

`on_startup` and `on_shutdown` will be removed. I'm currently thinking towards implementing `lifespan` as a middleware in the middleware stack, so it can be used by both the `FlaskApp` and `AsyncApp`.

**Comment by SpudInNZ** [comment]
I ended up with this, which mimics the way aiohttp works and is enough for my use-case right now. 

import typing as t
from starlette.types import ASGIApp, Receive, Scope, Send

```

class LifecycleMiddleware:
    """
    Middleware that traps ASGI lifespan events and passes them to the specified functions

    Required because lifecycle events are not passed through to Starlette properly in Connexion 3.0.0a2
    """
    def __init__(self,
                 asgi_app: ASGIApp,
                 on_startup: t.Callable[[], t.Awaitable[None]],
                 on_shutdown: t.Callable[[], t.Awaitable[None]]) -> None:
        self.asgi_app = asgi_app
        self.on_startup = on_startup
        self.on_shutdown = on_shutdown

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope['type'] == 'lifespan':
            while True:
                message = await receive()
                if message['type'] == 'lifespan.startup':
                    try:
                        await self.on_startup()
                    except Exception as e:
                        await send({'type': 'lifespan.startup.failed', 'message': str(e)})
                    else:
                        await send({'type': 'lifespan.startup.complete'})
                elif message['type'] == 'lifespan.shutdown':
                    await self.on_shutdown()
                    await send({'type': 'lifespan.shutdown.complete'})
                    return
        else:
            await self.asgi_app(scope, receive, send)
```

**Comment by RobbeSneyders** [comment]
I opened https://github.com/spec-first/connexion/pull/1676 to add support for lifespan handlers.
