### ISSUE TITLE
How to enable Swagger UI when using Conda

### ISSUE THREAD

**Issue by dragorosson** [spec-first/connexion#1680]
### Description

This probably mostly comes down to unfamiliarity. I'm forced into using conda and the `conda-forge` channel because of some of my other dependencies instead of pypi. I can install `connexion` but I don't know how to install `connexion[swagger-ui]` as it is a pip extra and conda does not speak that language. (It's [not directly possible](https://stackoverflow.com/a/4348109), but there's [something similar available](https://github.com/conda/conda/issues/3299#issuecomment-299616619) in conda but I wouldn't know how to translate the pip extra to that) 

I also can't install `swagger_ui_bundle` (a shot in the dark based on https://stackoverflow.com/a/60992592/17045052) because it's in the `anaconda` channel and conda is not finding it even though I'm listing in my conda environment file when I do `conda env update -f ...`.

There are enough things I'm unfamiliar with here that I thought it might be better to ask directly:

What is the best way to get Swagger UI working with connexion when using conda (and conda-forge)?

**Comment by RobbeSneyders** [comment]
Hi @dragorosson 

You should be able to install packages in conda using `pip`. See the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages).

If you're still having issues, it's probably better to direct yourself to the conda community for help.
