### ISSUE TITLE
Connexion 3.0.0a4, GZIP Middleware

### ISSUE THREAD

**Issue by SpudInNZ** [spec-first/connexion#1682]
### Description

In 3.0.0a2 I was able to use the Starlette GZipMiddleware class but in 3.0.0a4 I get an exception at runtime.

### Expected behaviour

I would hope to be able to use Starlette middleware in my app's middleware stack.

### Actual behaviour

Using 
```
middlewares = [GZipMiddleware] + ConnexionMiddleware.default_middlewares
super().__init__(__name__,
                 lifespan=self.lifespan,
                 middlewares=middlewares,
                 specification_dir="spec/",
                 resolver=RelativeResolver(root_path="app.controllers"),
                 *args, **kwargs)

```
in my application constructor. But in 3.0.0a4 I get TypeError: GZipMiddleware.__init__() got an unexpected keyword argument 'lifespan'

It's clear that this is a result of the lifespan changes in the previous release. 

Am I doing something wrong here?

### Steps to reproduce

As above

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by RobbeSneyders** [comment]
Thanks for the report @SpudInNZ 

The issue is that we're passing the lifespan to every middleware, which isn't a problem for Connexion middleware, but could be for others. I'll look into how we can do this differently.

**Comment by rashmi-mi** [comment]
We ran into the same issue, here is our implementation for a CORSMiddleware - does this look right?

```
from starlette.middleware.cors import CORSMiddleware as StarletteCorsMiddleware

from starlette.types import ASGIApp, Receive, Scope, Send


class CORSMiddleware(StarletteCorsMiddleware):
    def __init__(self, next_app: ASGIApp, *args, **kwargs):
        kwargs["allow_origins"] = ["*"]
        kwargs["allow_methods"] = ["*"]
        kwargs["allow_headers"] = ["*"]
        kwargs["allow_credentials"] = True

        if "lifespan" in kwargs:
            kwargs.pop("lifespan")

        super().__init__(next_app, *args, **kwargs)

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        # Needs to be set so starlette router throws exceptions instead of returning error responses
        scope["app"] = "connexion"
        await super().__call__(scope, receive, send)

```
