### ISSUE TITLE
Body in GET/DELETE requests in 3.x

### ISSUE THREAD

**Issue by AndrianStoikov** [spec-first/connexion#1689]
### Description
Hello,
Since version 2.x connexion does not support body in GET and DELETE requests. 
https://github.com/spec-first/connexion/blob/e8408406f6381657c7f0dc18b34bfd7efd980d91/connexion/operations/abstract.py#L283

However, many APIs are designed this way and connexion is being too restrictive to API implementations which causes problems with further library updates.

### Expected behaviour
IMHO it is best for the library to be as flexible as possible while at the same time promoting correct API design. But currently, it is too restrictive and blocks the projects that have been developed for years to upgrade to a higher version of connexion.

Even the authors of OpenAPI understand that this change is too restrictive

> In OpenAPI 3.1, we decided to go back on this change for the main reason that indeed many APIs are designed this way (this is not to say that we believe it's the right approach).

https://github.com/swagger-api/swagger-ui/issues/2136#issuecomment-1055839700

I think it is best if connexion 3.x also reverts to this behavior in order to be more flexible and allow easier transition for projects.

### Actual behaviour
Connexion from version 2.x does not automatically parse body in arguments and breaks all endpoints that currently utilize this functionality. I know about the fix of using `connexion.request.json` however this requires changes of many APIs especially of old APIs that have been developed for years.

### Additional info:

Output of the commands:

- 3.11
- 2.14.2

**Comment by Ruwann** [comment]
Hi @AndrianStoikov , Thanks a lot for the detailed issue report!

Reading the spec and links you provided, I am indeed inclined to agree that it would make sense for connexion to be as liberal as possible and accept body arguments in `GET` and `DELETE` operations. I do not immediately see a reason why it would not be possible in connexion. I assume the one place would be the swagger UI that woud not properly support it.

Even in OpenAPI 3.0.3 (as opposed to 3.0.2), it is not actually disallowed but rather discouraged, allowing connexion some liberty to choose what to do with it:

> The request body applicable for this operation. The requestBody is fully supported in HTTP methods where the HTTP 1.1 specification [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.1) has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague (such as [GET](https://tools.ietf.org/html/rfc7231#section-4.3.1), [HEAD](https://tools.ietf.org/html/rfc7231#section-4.3.2) and [DELETE](https://tools.ietf.org/html/rfc7231#section-4.3.5)), requestBody is permitted but does not have well-defined semantics and SHOULD be avoided if possible.
