### ISSUE TITLE
Connexion/Uvicorn silently swallowing exceptions at startup

### ISSUE THREAD

**Issue by SpudInNZ** [spec-first/connexion#1693]
### Description

I have an issue in my code that means the server cannot start. Instead of seeing the error in the logs and have the server exit, Uvicorn/Connexion is swallowing the exception and erroneously displaying "ASGI 'lifespan' protocol appears unsupported." instead. It does this whether or not I specify `lifespan=` in the __init__ call.

### Expected behaviour

The server should exit with an error message and the exception text if it fails to start. 

### Actual behaviour

Uvicorn appears to still be running even though the webserver failed to start/exited

### Steps to reproduce

In my case the error was in a call to a decorator on an API endpoint handler, probably easy to reproduce something similar.

```
@fb_api(required_scopes=[], required_permissions=[], no_cache=True, audit=False)
async def get_health(*, request: Request):
 [...]

```
This endpoint is referenced in the swagger spec.

### Additional info:

The runtime error I get in my code is:

`TypeError("fb_api() got an unexpected keyword argument 'required_permissions'")`

But the logging output is:

```
webapi_1          | INFO:     Started server process [7]
webapi_1          | INFO:     Waiting for application startup.
webapi_1          | INFO:     ASGI 'lifespan' protocol appears unsupported.
webapi_1          | INFO:     Application startup complete.
webapi_1          | INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)


```

100% a simple bug in my code. I can see this by placing a breakpoint in the exception handler uvicorn.lifespan.on.py:

```
    async def main(self) -> None:
        try:
            app = self.config.loaded_app
            scope: LifespanScope = {  # type: ignore[typeddict-item]
                "type": "lifespan",
                "asgi": {"version": self.config.asgi_version, "spec_version": "2.0"},
                "state": self.state,
            }
            await app(scope, self.receive, self.send)
        except BaseException as exc:
            self.asgi = None
            self.error_occured = True
            if self.startup_failed or self.shutdown_failed:
                return
            if self.config.lifespan == "auto":
                msg = "ASGI 'lifespan' protocol appears unsupported."
                self.logger.info(msg)
            else:
                msg = "Exception in 'lifespan' protocol\n"
                self.logger.error(msg, exc_info=exc)
```

Ideally this block of code would be executed:

```
            if self.startup_failed or self.shutdown_failed:
                return

```

But instead 

```
            if self.config.lifespan == "auto":
                msg = "ASGI 'lifespan' protocol appears unsupported."
                self.logger.info(msg)

```
is executed. Even then, the exception message would be swallowed. It seems like there should be an exception handler further up the stack catching the exception, printing the message and setting `self.startup_failed`,  but I don't really know.

Output of the commands:

- `python --version`  Python 3.11.3
- `pip show connexion | grep "^Version\:"`  Version: 3.0.0a5

**Comment by RobbeSneyders** [comment]
I believe this might be fixed by #1711 and #1754. Feel free to reopen with a reproducible example if you still run into this.
