### ISSUE TITLE
Access Token as Query Parameter Ends up in Access Logs

### ISSUE THREAD

**Issue by demonCoder95** [spec-first/connexion#1694]
### Description
Allowing `accessToken` query parameter for endpoints leads to a situation where the token ends up in the access logs of the application. 

While it is possible to attach logging filters to the logs to remove the log entries, I believe the issue is central that is better handled inside the library.

### Expected behaviour
It would perhaps be better to forbid usage of this parameter somehow and encourage usage of the `Authentication` header.

### Actual behaviour
The query parameter is logged in the access logs as part of the URI.

### Additional info:
An example log is here:
```
10.2.26.0 - - [2023-04-21 12:30:57] "GET /nacos/v1/auth/users?accessToken=+++JWT_TOKEN_REDACTED+++&pageNo=1&pageSize=10 HTTP/1.1" 404 329 0.001025

```

Output of the commands:

- `python --version` python 3.9
- `pip show connexion | grep "^Version\:"` connextion>=2.7.0

**Comment by Ruwann** [comment]
Can you share the corresponding part of your Swagger/OpenAPI file? I assume you are using an API key in the query?

Where exacty and how does the access logging take place? If this done before the request reaches any connexion code, this is not something we can fix from our side.

I'm not convinced this should be included in connexion by default. What we are currently already doing, is taking the security query parameters into account:
https://github.com/spec-first/connexion/blob/15fe2eda8fa1853a4d73a13839d7e35814ad7358/connexion/middleware/request_validation.py#L74-L94

So, perhaps it makes more sense to keep the original request intact as much as possible until it reaches the user's code.
We could provide middleware that is based on the code above and remove the parameter from the string. This would build upon the API spec parsing that connexion does, but not yet convinced this is the right approach.
