### ISSUE TITLE
Flask 2.3.x causes error 'flask.json' has no attribute 'JSONEncoder' at startup

### ISSUE THREAD

**Issue by chrisinmtown** [spec-first/connexion#1699]
### Description

Please update connexion for the latest release of Flask, version 2.3.x released 25 Apr 2023. That version removes some code that Connexion relies on. Now our REST server fails at startup with this message:
```
our_module/__init__.py:9: in <module>
    import connexion
.tox/code/lib/python3.9/site-packages/connexion/__init__.py:32: in <module>
    from .apps.flask_app import FlaskApp
.tox/code/lib/python3.9/site-packages/connexion/apps/flask_app.py:151: in <module>
    class FlaskJSONEncoder(json.JSONEncoder):
E   AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
```
Also see: https://github.com/pallets/flask/issues/5094

### Expected behaviour

Connexion server starts as before.

### Actual behaviour

Connexion server fails to start.

### Steps to reproduce

Upgrade to Flask 2.3.0 or 2.3.1 and run tox tests.

### Additional info:

Output of the commands:

- `python --version`: python 3.9
- `pip show connexion | grep "^Version\:"`  connexion 2.14.2

**Comment by davidism** [comment]
Already reported in https://github.com/spec-first/connexion/issues/1576 and fixed in https://github.com/spec-first/connexion/pull/1582

**Comment by chrisinmtown** [comment]
Thanks for the really fast reply. I see the old issue about upgrading connexion to Flask 2.3. To the best of my knowledge I'm using the latest and greatest connexion, version 2.14.2. Please tell me which connexion version has fix #1582?

**Comment by davidism** [comment]
Looks like it will be in the next stable release. Until then, and regardless, you should always use a tool like pip-tools to pin your application's entire dependency tree and avoid unexpected updates.

**Comment by chrisinmtown** [comment]
Yep here's the complaint from pip-compile (from pip-tools):
```
There are incompatible versions in the resolved dependencies:
  Werkzeug>=2.3.0 (from Flask==2.3.1->our_package (setup.py))
  werkzeug<2.3,>=1.0 (from connexion[swagger-ui]==2.14.2->our_package (setup.py))
```

**Comment by RobbeSneyders** [comment]
Connexion 2.X is not compatible with Flask 2.3+. This is indicated by the upper bound in the requirements.

Connexion 3.X is compatible with Flask 2.3+ only and is now in alpha.

The reasoning is explained in #1582 
> Partially fixes #1576 by updating the jsonifier and related code to be compatible with Flask 2.3.
Since this new json interface in Flask was only introduced in Flask 2.2, we'll have to pin it as the lower bound version.

> I'm doubting if we should backport this to v2. It introduces some breaking changes for users who use custom json encoders, and it would force us to bump the lower bound version of Flask to 2.2 there as well.

> If we don't do a backport, we should pin the upper bound Flask version on v2 to 2.2 instead.

**Comment by davidism** [comment]
Got it, thanks for clarifying. I should have been more nuanced when I said that, sounds like connexion is doing things right.

**Comment by chrisinmtown** [comment]
Are you absolutely certain connexion pins the flask version < 2.3? I didn’t force usage of Flask version 2.3, my build process found it automatically today. Flask ver 2.3 was released yesterday.
