### ISSUE TITLE
Accessing Security Credentials and JWT Tokens

### ISSUE THREAD

**Issue by rkrishnasanka** [spec-first/connexion#1717]
### Description

Currently, the examples and docs give very little information on how the middleware works and how we can extract parsed token information in the request handlers. I've been using connexion in conjunction with the OpenAPI code generator so it's really hard to figure out where any of the accesspoints for retrieving information is

### Expected behaviour

Being able to access the bearer tokens needs to be something as simple as

```
connexion.securitymiddleware.getJWT() token
```

Its fine if its more convoluted but there's no documentation showing me where I can retrieve this information from.

### Actual behaviour

Not sure

### Steps to reproduce

Not Applicable

### Additional info:

Output of the commands:

- `python --version` : NA
- `pip show connexion | grep "^Version\:"` : NA

**Comment by RobbeSneyders** [comment]
Hi @rkrishnasanka, please have a look at the following example: https://github.com/spec-first/connexion/tree/main/examples/jwt

The values returned by your authentication function are injected into the view function if you define them:

Authentication function:
```python
def decode_token(token):
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
    except JWTError as e:
        raise Unauthorized from e
```

View function (2 options):
```
def get_secret(user, token_info) -> str:
    ...
```

```
def get_secret(context_) -> str:
    user = context_["user"]
    token_info = context_["token_info"]
   ...
```
