### ISSUE TITLE
MockResolver should generate valid example data if no example is provided by the schema.

### ISSUE THREAD

**Issue by mjp4** [spec-first/connexion#1719]
### Description
If an OpenAPI spec has examples, then sensible reponses are returned. Including building up nested objects and arrays (as of https://github.com/spec-first/connexion/pull/1148).

However, if no example field exists, then a default (and invalid) response is returned. This is causing a problem when trying to mock out a third-party schema (that I do not want to modify).

This issue is being resolved in https://github.com/spec-first/connexion/pull/1718. An earlier attempt to solve the same problem never got merged https://github.com/spec-first/connexion/pull/513. 

### Expected behaviour
Server returns some dummy data that matches the schema requirements.

### Actual behaviour
Server returns a body of `'No example response was defined.'`.

**Comment by RobbeSneyders** [comment]
> While I agree that generating example responses based on the schema would be useful, I don't want to take on the effort to maintain this in Connexion. This PR implements this logic only for the most simple schema's, which means that we'll get issues for every case where this is not working.
> 
> If there is a third-party library that can provide this behavior, I'm happy to integrate it.

_Originally posted by @RobbeSneyders in https://github.com/spec-first/connexion/issues/1718#issuecomment-1628662131_
