### ISSUE TITLE
Connexion 3.0.0a6's RelativeResolver seems to generate false positive error when loading a module

### ISSUE THREAD

**Issue by alanmun** [spec-first/connexion#1723]
### Description
When you try to load method from a module that has nothing to do with route resolving in a relative manner, RelativeResolver generates an error.

### Expected behaviour

I can use a relatively imported module

### Actual behaviour

connexion.exceptions.ResolverError: Cannot resolve operationId "backend.api.home.landingPage"! Import error was "No module named 'utils'" 

(utils is the module I am trying to import, into the same file that contains landingPage endpoint)

### Steps to reproduce

For both expected and actual consider this project structure:
- app.py
- backend
  - api
    - utils.py
    - home.py

and home.py has some endpoint called landingPage:

```python
from flask import render_template
from utils import someUtil

def landingPage():
  b = someUtil()
  return render_template("index.html", data=b)
```

Access the landingPage endpoint via your API and it will generate the error shown in Actual behavior. someUtil isn't an endpoint and has nothing to do with the API or operationIds. Its just a helper function I am trying to import.

**I can get around this issue by specifying absolute pathing for module imports. So, change `from utils...` to `from backend.api.utils...`**

### Additional info:

Python 3.10.11

**Comment by RobbeSneyders** [comment]
Your import is not correct. It should either be absolute as you mention, or `from .utils import someUtil` if you want to use a relative import.
