### ISSUE TITLE
"AttributeError: module 'flask.json' has no attribute 'JSONEncoder'" on Flask 2.3.x

### ISSUE THREAD

**Issue by renxinhe** [spec-first/connexion#1729]
### Description

I'm attempting to upgrade my `Flask` pip package from 2.2.5 to 2.3.3. Afterwards, I started seeing `connexion` import failures.

In the [Flask documentation](https://flask.palletsprojects.com/en/2.2.x/api/#flask.json.JSONEncoder), we see that `flask.json.JSONEncoder` is removed in Flask 2.3.x. We should consider changing this to support Flask 2.3.x.

> Deprecated since version 2.2: Will be removed in Flask 2.3. Use app.json instead.

### Expected behaviour

Importing `connexion` should not raise an error due to Flask version mismatch. Ideally this should be enforced in "requirements.txt", or otherwise have supported Flask version documented.

### Actual behaviour

Error trace:
```
ImportError while loading conftest 'client/endpoints/tests/conftest.py'.
client/endpoints/tests/__init__.py:3: in <module>
    import connexion
../.venv/lib/python3.8/site-packages/connexion/__init__.py:32: in <module>
    from .apps.flask_app import FlaskApp
../.venv/lib/python3.8/site-packages/connexion/apps/flask_app.py:151: in <module>
    class FlaskJSONEncoder(json.JSONEncoder):
E   AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
```

### Steps to reproduce

**Versions:**
```
Flask                           2.3.3
connexion                       2.14.1
Python                          3.8.13
```

**Code:**
```python
import connexion
```

### Additional info:

Output of the commands:

- `python --version`
```
$ python --version
Python 3.8.13
```
- `pip show connexion | grep "^Version\:"`
```
$ pip show connexion | grep "^Version\:"
Version: 2.14.1
```

**Comment by renxinhe** [comment]
After some digging, I came across this closed issue on this very topic: https://github.com/spec-first/connexion/issues/1699

Seems like the upper version of Flask is pinned to 2.2 for V2 connexion. However I don't think I got a pip warning. I was able to install both Flask 2.3.3 and connexion 2.14.1 at the same time.

**Comment by julien-lecomte** [comment]
I confirm this new issue.

I do get a warning:
```bash
The conflict is caused by:
    flask-gordon 0.15.0 depends on flask>=2.3.0
    connexion[swagger-ui] 2.14.2 depends on flask<2.3 and >=1.0.4
```

**Comment by LewisCowlesMotive** [comment]
This issue has been warned about for a while though

```
Library/Caches/pypoetry/virtualenvs/pnc-gateway-api-q6XNtrYF-py3.11/lib/python3.11/site-packages/connexion/apps/flask_app.py:36
   Library/Caches/pypoetry/virtualenvs/pnc-gateway-api-q6XNtrYF-py3.11/lib/python3.11/site-packages/connexion/apps/flask_app.py:36: DeprecationWarning: 'app.json_encoder' is deprecated and will be removed in Flask 2.3. Customize 'app.json_provider_class' or 'app.json' instead.
    app.json_encoder = FlaskJSONEncoder

```

**Comment by RobbeSneyders** [comment]
Indeed, see my comment in the linked issue: https://github.com/spec-first/connexion/issues/1699#issuecomment-1524042812

If you want to use Flask 2.3, please use Connexion 3.0.

**Comment by LewisCowlesMotive** [comment]
Sorry, but "use Alpha software" isn't a fix is it? Once the Alpha becomes stable it will be a fix, but right now it's not, and switching to 3 breaks other parts of existing code.
