### ISSUE TITLE
Connexion 3.0.0a7: SystemError: no locals when loading 'str'

### ISSUE THREAD

**Issue by jarirajari** [spec-first/connexion#1730]
### Description
I am trying to get connexion 3.0.0a7 running, but I always encounter the same error. Currently, I am trying to use Starlette explicitly (see code), but I have managed to get same error by using AsyncApp. I am able to start the server from the command line, but as soon as the first request arrives to connexion there is the 500 error. Is my app somehow breaking things or is this something else?

**webserver-connexion.py**
```python
import connexion
from starlette.applications import Starlette
# from starlette.templating import Jinja2Templates

# line 128, in _setup_env_defaults
#     context: typing.Dict[str, typing.Any],
# SystemError: no locals when loading 'str'
# templates = Jinja2Templates(directory='./templates')


# same error with this one
# def connexion_asyncapp():
#    async_app = connexion.AsyncApp(__name__, specification_dir="./")
#    async_app.add_api("./openapiv3.yaml")
#
#    return async_app


def connexion_starlette():
    async_app = Starlette(debug=True)
    async_app = connexion.ConnexionMiddleware(async_app, specification_dir='./')
    async_app.add_api("./openapiv3.yaml")

    return async_app


def run():
    import uvicorn
    asgi = connexion_starlette()
    uvicorn.run(asgi, host='0.0.0.0', port=5000,  log_level='info', app_dir="./")


if __name__ == '__main__':
    run()


``` 

### Expected behaviour
I am expecting to normal behavior.

### Actual behaviour
**The error:**
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jari/.local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/jari/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/jari/.local/lib/python3.8/site-packages/connexion/middleware/main.py", line 467, in __call__
    self.app, self.middleware_stack = self._build_middleware_stack()
  File "/home/jari/.local/lib/python3.8/site-packages/connexion/middleware/main.py", line 317, in _build_middleware_stack
    app.add_api(
  File "/home/jari/.local/lib/python3.8/site-packages/connexion/middleware/swagger_ui.py", line 205, in add_api
    api = SwaggerUIAPI(
  File "/home/jari/.local/lib/python3.8/site-packages/connexion/middleware/swagger_ui.py", line 50, in __init__
    self._templates = Jinja2Templates(
  File "/home/jari/.local/lib/python3.8/site-packages/starlette/templating.py", line 112, in __init__
    self._setup_env_defaults(self.env)
  File "/home/jari/.local/lib/python3.8/site-packages/starlette/templating.py", line 128, in _setup_env_defaults
    context: typing.Dict[str, typing.Any],
SystemError: no locals when loading 'str'

``` 

### Steps to reproduce
Run the app:
`python3 webserver-connexion.py`

### Additional info:
I checked the templating.py source code, but wasn't able to come up with a fix or a workaround.

![templating-py](https://github.com/spec-first/connexion/assets/3974196/b356984e-c1bb-406f-84ed-cd892a7a5d24)

I checked following documentation:
- https://github.com/spec-first/connexion/blob/main/examples/frameworks/hello_starlette.py
- https://connexion.readthedocs.io/en/latest/v3.html#using-stand-alone-connexion
- https://www.starlette.io/templates/#customizing-jinja2-environment

Output of the commands:

- `python --version` Python 3.8.0
- `pip show connexion | grep "^Version\:"` Version: 3.0.0a7

**Comment by RobbeSneyders** [comment]
Hi @jarirajari, this was a [bug in Python](https://bugs.python.org/issue39215) that is fixed in later versions. Please upgrade your Python version. Using 3.8.0 isn't great, 3.8.18 has already been released.
