### ISSUE TITLE
Use MethodViewResolver with connexion 3.0.0a7

### ISSUE THREAD

**Issue by jdkent** [spec-first/connexion#1748]
### Description

Trying out 3.0.0a7, from my current connexion version 2.14.2

### Expected behaviour

The resolver would execute and create an url_map

### Actual behaviour

the app has no url_map, and if I try to emulate the test here: 
https://github.com/spec-first/connexion/blob/655ea430ed9c54fb9c90fe222008a1daf9c69670/examples/methodresolver/app.py

I get an error that debug is not a valid argument to `FlaskApp`

### Steps to reproduce

my current code: https://github.com/neurostuff/neurostore/blob/d59a5c67e6725a6352d36766a8a37ad233cc7529/store/neurostore/core.py#L18-L62

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by RobbeSneyders** [comment]
Hi @jdkent,

It's not exactly clear to me from your description which issue you're running into. Do note that the behavior of the `MethodViewResolver` changed between version 2.X and 3.X (see our [docs](https://connexion.readthedocs.io/en/latest/routing.html#methodviewresolver)). If you want to maintain the same behavior, you can use the `MethodResolver` on 3.X instead.

You're correct about the `debug` argument in the example. I opened a PR to fix it: #1749.

If you can't fix the issue with the information above, feel free to reopen the issue, but please provide a minimal reproducible example with a more detailed description of the expected and actual behavior.
