### ISSUE TITLE
routes not being added to url_map with MethodViewResolver

### ISSUE THREAD

**Issue by jdkent** [spec-first/connexion#1751]
### Description
 more reproducible example of #1748
May be a documentation/usage issue, for the MethodViewResolver example, `app.app.url_map` is not being populated with routes in the example app.

### Expected behaviour

```python
>>> app.app.url_map
Map([<Rule '/static/<filename>' (HEAD, GET, OPTIONS) -> static>,
 <Rule '/v1.0/openapi.json' (HEAD, GET, OPTIONS) -> /v1_0./v1_0_openapi_json>,
 <Rule '/v1.0/openapi.yaml' (HEAD, GET, OPTIONS) -> /v1_0./v1_0_openapi_yaml>,
 <Rule '/v1.0/ui/<filename>' (HEAD, GET, OPTIONS) -> /v1_0./v1_0_swagger_ui_static>,
 <Rule '/v1.0/ui/' (HEAD, GET, OPTIONS) -> /v1_0./v1_0_swagger_ui_index>,
 <Rule '/v1.0/pets' (HEAD, GET, OPTIONS) -> /v1_0.api_PetsView_search>,
 <Rule '/v1.0/pets' (POST, OPTIONS) -> /v1_0.api_PetsView_post>,
 <Rule '/v1.0/pets/<petId>' (HEAD, GET, OPTIONS) -> /v1_0.api_PetsView_get>,
 <Rule '/v1.0/pets/<petId>' (OPTIONS, PUT) -> /v1_0.api_PetsView_put>,
 <Rule '/v1.0/pets/<petId>' (DELETE, OPTIONS) -> /v1_0.api_PetsView_delete>])
```

### Actual behaviour
```python
>>> app.app.url_map
Map([<Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>])
```

### Steps to reproduce
```
cd examples/methodresolver
python app.py
```
(add debug statement right before app is run)

### Additional info:

Output of the commands:

- `python --version`
  -  `Python 3.8.10`
- `pip show connexion | grep "^Version\:"`
  -  3.0.dev0

**Comment by RobbeSneyders** [comment]
Thanks for the clearer description @jdkent.

The `url_map` is still created, but only when the app starts running. If you test the app, you will see that it still works. Is there any reason you need to access the `url_map` before running the app?

**Comment by RobbeSneyders** [comment]
The examples now host both a swagger and an openapi API, which are accessible under `http://localhost:8080/swagger` and `http://localhost:8080/openapi` respectively. 

So instead you can eg try:
`http://localhost:8080/openapi/pets`
`http://localhost:8080/openapi/ui`

I see this is not reflected in all example READMEs though. so I'll update that.

**Comment by jdkent** [comment]
> Is there any reason you need to access the url_map before running the app?

From my reading of the flask documentation on how to test an app, they do not run the app when using it in tests
https://flask.palletsprojects.com/en/3.0.x/testing/

When using connexion, I should start the app before using it as a fixture?

**Comment by RobbeSneyders** [comment]
No, you can use the built-in `test_client`.

Eg:
```python
from connexion import AsyncApp

app = AsyncApp(__name__)
app.add_api(...)

client = app.test_client()
response = client.get("/path")
assert ...
```

This is a new feature in Connexion 3. The testing documentation is one of the final pages of documentation we still need to write (see https://github.com/spec-first/connexion/issues/1531).

**Comment by RobbeSneyders** [comment]
Has this solved your issue @jdkent?

**Comment by jdkent** [comment]
yes, thank you! I am using that test client now.
