### ISSUE TITLE
Current release requires vulnerable version of werkzeug

### ISSUE THREAD

**Issue by sr-verde** [spec-first/connexion#1757]
### Description

Current release 2.14.2 requires werkzeug < 2.3 but werkzeug is [vulnerable to DDoS attacks](https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw). It would be wonderful to relelase a version 2.14.3 with a version bump of werkzeug to >= 3.0.1 that [fixes this vulnerability](https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-3-0-1).

### Expected behaviour

Current release doesn't require vulnerable version of werkzeug.

### Actual behaviour

Current release requires vulnerable version of werkzeug.

### Steps to reproduce

Install connexion and scan dependencies with software like safety.

### Additional info:

Output of the commands:

```
python --version
Python 3.11.5
```

```
pip show connexion | grep "^Version\:"
Version: 2.14.2
```

**Comment by RobbeSneyders** [comment]
We cannot update the werkzeug / Flask version without introducing breaking changes. A new major version (3.0) will be released tomorrow including this fix among a lot of other improvements.

**Comment by RobbeSneyders** [comment]
Connexion 3 is out now! [More info](https://github.com/spec-first/connexion/discussions/1775.)

**Comment by sr-verde** [comment]
Okay, that’s hard since Connexion 3 introduces several braking changes.

**Comment by sr-verde** [comment]
I have an API running with Connexion and Gunicorn. But I cannot run a Connexion 3 application with Gunicorn anymore. So, this introduces a breaking change to my software (since it bundles these two apps). Even if I can update the software quickly, it's another question whether the users of my software will deploy a major release at such short notice. I think it is good practice to provide previous versions with security fixes, at least for a transitional period. I know, you could make the same argument for werkzeug but you pinned to the version before last.

Apart from that, I very much welcome version 3.

**Comment by sr-verde** [comment]
> Sounds like we are in the same situation. Dependent on a package where a security fix is only available on a breaking version.

Yes, it’s a hazzle.

> You can still run connexion with Gunicorn (see [our docs](https://connexion.readthedocs.io/en/latest/quickstart.html#running-your-application)).

Okay, that sound nice. But I am a bit confused since you tell you need an ASGI server [here](https://connexion.readthedocs.io/en/latest/v3.html#asgi-server).

**Comment by petrblaho** [comment]
That need to have ASGI server should be better advertised. Docs say that connexion comes with uvicorn as an extra which is nice but to really understand that now with connexion 3.x we need different server should be much more highlighted.

For me, this is breaking change, which is understandable as connexion is now in new major version (this is ok) and I can work with this.

What I don't like in general (not directly a fault by anyone particular) is that b/c of werkzeug security fix I need to do major upgrade of it which leads to major upgrade of connexion which leads to introduction of ASGI server and adding uvicorn (which I did not know that it existed till a few days ago :unicorn:)

Anyway, thank you all for your work!
