### ISSUE TITLE
Token information Context params missing

### ISSUE THREAD

**Issue by Subin-Qreative** [spec-first/connexion#1780]
### Description

Documentation shows these would be available 
{
    "api_base_path": ...  # The base path of the matched API
    "operation_id": ...  # The operation id of matched operation
    "user": ...  # User information from authentication
    "token_info": ...  # Token information from authentication
}

### Expected behaviour

def get_secret(user, token_info, context_) -> str:
    print(context_)
    return """
    You are user_id {user} and the secret is 'wbevuec'.
    Decoded token claims: {token_info}.
    """.format(
        user=user, token_info=token_info
    )

print should real all of the context:

{'api_base_path': '/api/auth/{user_id}', 'operation_id': 'app.generate_token', 'user': '12', 'token_info': {'iss': 'com.zalando.connexion', 'iat': 1698962243, 'exp': 1698962843, 'sub': '12'}}

### Actual behaviour

{'user': '12', 'token_info': {'iss': 'com.zalando.connexion', 'iat': 1698962243, 'exp': 1698962843, 'sub': '12'}}

### Steps to reproduce

Followed instructions as per : 
https://connexion.readthedocs.io/en/stable/request.html#context

using 

https://github.com/spec-first/connexion/tree/main/examples/jwt

### Additional info:

Output of the commands:

- `python --version` Python 3.10.12
- `pip show connexion | grep "^Version\:"`  Version: 3.0.0

**Comment by RobbeSneyders** [comment]
Thanks @Subin-Qreative. Seems like this is a mistake in the documentation. The `api_base_path` and `operation_id` are stored under a separate key which is not included in the context that is made available.

Is there a reason you want to access these parameters?

**Comment by Subin-Qreative** [comment]
no particular reason, i was trying to  wrap my head around / understand how the "user" parameter was exposed and came to find the following.

**Comment by RobbeSneyders** [comment]
Ok, then I will update the documentation to match the current behavior. Thanks for reporting!

**Comment by temple** [comment]
Latest documentation ain't updated yet
https://connexion.readthedocs.io/en/latest/request.html#context @RobbeSneyders
