### ISSUE TITLE
connexion 3.0.0 breaks airflow standalone deployment

### ISSUE THREAD

**Issue by vtrbraga** [spec-first/connexion#1781]
### Description
Had this unpinned in my Airflow standalone local environment, had to flush docker image cache and couldn't get the environment back up.
After some investigation, I traced the issue to this package. Pinning to `2.14.2 `solves the issue and the environment loads just fine.

Airflow init traceback
```
airflow_1  | Traceback (most recent call last):
airflow_1  |   File "/usr/local/bin/airflow", line 8, in <module>
airflow_1  |     sys.exit(main())
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/__main__.py", line 48, in main
airflow_1  |     args.func(args)
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/cli/cli_parser.py", line 52, in command
airflow_1  |     return func(*args, **kwargs)
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 48, in entrypoint
airflow_1  |     StandaloneCommand().run()
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 64, in run
airflow_1  |     self.initialize_database()
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 183, in initialize_database
airflow_1  |     appbuilder = cached_app().appbuilder
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/www/app.py", line 167, in cached_app
airflow_1  |     app = create_app(config=config, testing=testing)
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/www/app.py", line 151, in create_app
airflow_1  |     init_api_connexion(flask_app)
airflow_1  |   File "/usr/local/lib/python3.10/site-packages/airflow/www/extensions/init_views.py", line 216, in init_api_connexion
airflow_1  |     connexion_app = App(__name__, specification_dir=spec_dir, skip_error_handlers=True, options=options)
airflow_1  | TypeError: FlaskApp.__init__() got an unexpected keyword argument 'skip_error_handlers'
```

### Expected behaviour
Airflow expects keyword `skip_error_handlers` during init

### Actual behaviour
Missing keyword causes application to raise a `TypeError`

### Steps to reproduce
apache-airflow==2.5.1

Airflow standalone local deployment: [https://airflow.apache.org/docs/apache-airflow/stable/start.html](https://airflow.apache.org/docs/apache-airflow/stable/start.html)

### Additional info:

Output of the commands:

- `python --version`: Python 3.10.13
- `pip show connexion | grep "^Version\:"`: Version: 3.0.0

**Comment by RobbeSneyders** [comment]
Thanks @vtrbraga, I think this issue should be raised at https://github.com/apache/airflow though. Connexion 3.0.0 contains breaking changes by design. Airflow should either restrict the upper bound of the Connexion dependency, or recommend its users to pin the dependencies.

Could you open an issue [here](https://github.com/apache/airflow/issues/new/choose)?
