### ISSUE TITLE
Error handling isn't correctly typed/documented

### ISSUE THREAD

**Issue by sidux** [spec-first/connexion#1787]
### Description
Error handling documented in https://connexion.readthedocs.io/en/latest/exceptions.html doesn't work 
Types and documentation are probably incorrect, instead the following example works altough types are detected as incorrect by the IDE.

```
def not_found(exc: Exception):
    return "Not found", 404
```

### Additional info:
python version 3.12

**Comment by RobbeSneyders** [comment]
Thanks for the report @sidux.

Seems like the `FlaskApp` was not following the documented behavior here. We will release a patch version (3.0.1) to correct the behavior.
