### ISSUE TITLE
OAuth: When verifying token, do not pass the access_token as query param

### ISSUE THREAD

**Issue by JoshStutts** [spec-first/connexion#179]
In decorators/security.py - verify_oauth, a session.get() call is made to the token_info_url and the access_token to be verified is passed as a query parameter.  According to the OAuth 2.0 Authorization Framework: Bearer Token Usage, section 5.3 ( https://tools.ietf.org/html/rfc6750#section-5.3 ):

> Don't pass bearer tokens in page URLs:  Bearer tokens SHOULD NOT be
>       passed in page URLs (for example, as query string parameters).
>       Instead, bearer tokens SHOULD be passed in HTTP message headers or
>       message bodies for which confidentiality measures are taken.
>       Browsers, web servers, and other software may not adequately
>       secure URLs in the browser history, web server logs, and other
>       data structures.  If bearer tokens are passed in page URLs,
>       attackers might be able to steal them from the history data, logs,
>       or other unsecured locations.

I propose that this code is changed to something along these lines:

`token_request = session.post(token_info_url, json={'access_token': token}, timeout=5)`

**Comment by hjacobs** [comment]
@JoshStutts thanks, actually I would propose passing the OAuth token in the `Authorization` header (as "Bearer" token), this is also what our two (!) :smirk: different OAuth providers support, e.g. our Open Source Plan B infrastructure, see https://planb.readthedocs.org/en/latest/oauth2.html#introspection-endpoint

Even better would be to support the "new" standard OAuth 2.0 Token Introspection Endpoint, see https://tools.ietf.org/html/rfc7662

**Comment by hjacobs** [comment]
Our STUPS Spring support library (for implementing OAuth resource servers with Java/Spring) also uses the `Authorization` header, see https://github.com/zalando-stups/stups-spring-oauth2-support/blob/master/stups-spring-oauth2-server/src/main/java/org/zalando/stups/oauth2/spring/server/DefaultTokenInfoRequestExecutor.java#L71

**Comment by hjacobs** [comment]
I would not use the HTTP "POST" method here as the request does not change any state, I think passing the access token should look like:

```python
token_request = session.get(token_info_url,
                            headers={'Authorization': 'Bearer {}'.format(token)},
                            timeout=5)

**Comment by JoshStutts** [comment]
Good call on changing the title of this issue, I should not have been presumptive of the solution when opening the issue.  I like the idea of passing it as an Authorization header and you are right about using GET instead of POST, but RFC 7662 that you linked to wants the access_token passed as '"application/x-www-form-urlencoded" data'.

**Comment by hjacobs** [comment]
@JoshStutts yes, the linked RFC is fairly new and not yet implemented (at least not in our own OAuth providers, e.g. https://github.com/zalando/planb-tokeninfo/issues/32) --- the response structure is also different, i.e. the new "Introspection Endpoint" is something for the future and should be configurable (on/off)

**Comment by hjacobs** [comment]
NOTE: Google actually uses the `access_token` query parameter, see https://developers.google.com/identity/protocols/OAuth2UserAgent#validatetoken

**Comment by JoshStutts** [comment]
Their first example of calling one of their APIs also passes the access_token as a query parameter:  https://developers.google.com/identity/protocols/OAuth2UserAgent#callinganapi

**Comment by hjacobs** [comment]
@JoshStutts I propose adding a `TOKENINFO_METHOD` option:

* "auth" --- use Authorization header (make this the default)
* "query" --- use "access_token" query param
* "introspect" --- use RFC 7662 method (which also has different response structure)

(Just a quick shot, open for better ideas...)

Obviously passing a custom function into Connexion for token validation is another option.

**Comment by hjacobs** [comment]
@JoshStutts what OAuth infrastructure are you using? I guess most people will be constrained by existing infrastructure...

**Comment by JoshStutts** [comment]
I created my own JWT based OAuth server, so I'm not using any particular product and I'm open to any implementation that helps secure the access_token.  I like the idea of having auth, query, or introspect as options that could be passed to connexion.

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
NOTE: We also need to update our Connexion OAuth example (https://github.com/zalando/connexion/tree/master/examples/oauth2) as soon as this issue is tackled...

**Comment by beenhead** [comment]
Would you expect the example to be broken at the moment? Having some trouble testing it. Thanks.

> srv:~/connexion/examples/oauth2$ ./mock_tokeninfo.py &
[1] 13287
srv:~/connexion/examples/oauth2$  * Running on http://0.0.0.0:7979/ (Press CTRL+C to quit)
srv:~/connexion/examples/oauth2$ ./app.py
INFO:werkzeug: * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
srv:~$ curl http://localhost:8081/secret
{"type": "about:blank", "title": "Unauthorized", "status": 401, "detail": "No authorization token provided"}
srv:~$ curl -H 'Authorization: Bearer 123' http://localhost:8081/secret
{"type": "about:blank", "title": "Internal Server Error", "status": 500, "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application."}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): srv
ERROR:__main__:Exception on /secret [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/connexion/decorators/security.py", line 82, in wrapper
    token_info = token_request.json()  # type: dict
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
INFO:werkzeug:127.0.0.1 - - [18/Mar/2016 10:21:27] "GET /secret HTTP/1.1" 500 -

**Comment by hjacobs** [comment]
@beenhead works for me --- I just tested it with Connexion 1.0.76 (Python 3, installed from PyPI)

**Comment by hjacobs** [comment]
@beenhead what version are your running? Did you change the example `app.py`? I see that your `app.py` starts on port 8081, but the example uses port 8080 (compare yourself: https://github.com/zalando/connexion/blob/master/examples/oauth2/app.py)

**Comment by beenhead** [comment]
Hi - I am running 1.0.76: 

> pip3 show connexion
> Name: connexion
> Version: 1.0.76
> Location: /usr/local/lib/python3.4/dist-packages
> Requires: requests, flask, jsonschema, strict-rfc3339, swagger-spec-validator, PyYAML, six

And the only thing I changed in app was the port (I had something running on 8080). I shut down the other service and started `app.py` on 8080 just to make sure, and still same issue.

**Comment by beenhead** [comment]
Since updating to 1.0.81 this issue is resolved and demo code works. Thanks.

**Comment by rafaelcaricio** [comment]
@beenhead thanks for the feedback! :grinning:

**Comment by hjacobs** [comment]
@rafaelcaricio I think this issue must be kept open, @beenhead's problem was "unrelated" to this issue's title.

**Comment by rafaelcaricio** [comment]
@hjacobs Oops, sorry.

**Comment by LappleApple** [comment]
@hjacobs For your March 9 comment above (NOTE: We also need to update our Connexion OAuth example (https://github.com/zalando/connexion/tree/master/examples/oauth2) as soon as this issue is tackled...): Looks like no update was made?

**Comment by prowley** [comment]
In server function call would be very welcome here. If you are issuing your own tokens for your own users there is really no need to http overhead for checking a token in process.
