### ISSUE TITLE
Document breaking change that underlying Flask app can no longer be run directly.

### ISSUE THREAD

**Issue by tariqjamal-abdulazeez** [spec-first/connexion#1794]
### Description
When using connexion and flask with the below version

> Name: Flask
> Version: 3.0.0
> 
> Name: connexion
> Version: 3.0.1

Code

> **app.py code**
> import connexion
> def post_greeting(name: str) -> str:
>     return f"Hello {name}"
> 
> api = connexion.FlaskApp(__name__, specification_dir="specs/")
> api.add_api("openapi.yml", arguments={"title": "Hello World Example"})
> app = api.app
> 
> **openapi.yml**
> # openapi.yml
> openapi: 3.0.0
> info:
>   title: Hello World Example
>   version: "1.0"
> servers:
>   - url: /api
>     description: Development API Location
> paths:
>   /post_greeting:
>     get:
>       summary: Get a greeting
>       parameters:
>         - name: name
>           in: query
>           schema:
>             type: string
>           description: Name to be used in the greeting
>       responses:
>         '200':
>           description: OK
>           content:
>             application/json:
>               schema:
>                 type: object
>                 properties:
>                   message:
>                     type: string

### Actual behaviour
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tariqjamal/anaconda3/envs/reflex-apps/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/Users/tariqjamal/anaconda3/envs/reflex-apps/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tariqjamal/anaconda3/envs/reflex-apps/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tariqjamal/anaconda3/envs/reflex-apps/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tariqjamal/anaconda3/envs/reflex-apps/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tariqjamal/anaconda3/envs/reflex-apps/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tariqjamal/anaconda3/envs/reflex-apps/lib/python3.11/site-packages/flask/app.py", line 759, in handle_user_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tariqjamal/anaconda3/envs/reflex-apps/lib/python3.11/site-packages/connexion/apps/flask.py", line 245, in _http_exception
    raise starlette.exceptions.HTTPException(exc.code, detail=exc.description)
starlette.exceptions.HTTPException: 404
`

@spec-first 
@RobbeSneyders  @Ruwann Like this in another project i'm getting the error 

>     raise NotFound() from None
`werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`

**Comment by RobbeSneyders** [comment]
Hi @tariqjamal-abdulazeez, how are you running the application? You should run the Connexion application directly, not the underlying Flask application.

**Comment by hasheur404** [comment]
@tariqjamal-abdulazeez how to achieve that because i have exactly the same issue !

**Comment by nickzandbergen** [comment]
I had a similar issue after upgrading from 2.14.0 and using connexion's FlaskApp instead of the Flask application fixed it.

**Comment by RobbeSneyders** [comment]
Check this discussion for more info https://github.com/spec-first/connexion/discussions/1795

**Comment by hasheur404** [comment]
@RobbeSneyders could you write a documentation for migration step by step ? because really i'm not able to make it works with the new version

**Comment by tariqjamal-abdulazeez** [comment]
> I had a similar issue after upgrading from 2.14.0 and using connexion's FlaskApp instead of the Flask application fixed i

@RobbeSneyders  I had tried that also but it doesn't work for me

**Comment by tariqjamal-abdulazeez** [comment]
> I had a similar issue after upgrading from 2.14.0 and using connexion's FlaskApp instead of the Flask application fixed it.



> I had a similar issue after upgrading from 2.14.0 and using connexion's FlaskApp instead of the Flask application fixed it.

@

> Hi @tariqjamal-abdulazeez, how are you running the application? You should run the Connexion application directly, not the underlying Flask application.

@RobbeSneyders I tried that also but it does not work for me

**Comment by tariqjamal-abdulazeez** [comment]
> I had a similar issue after upgrading from 2.14.0 and using connexion's FlaskApp instead of the Flask application fixed it.

@nickzandbergen  I need to achieve this thing in connexion latest version, but using the connexion latest docs with flask version 3.0 it not working properly

**Comment by tariqjamal-abdulazeez** [comment]
> > I had a similar issue after upgrading from 2.14.0 and using connexion's FlaskApp instead of the Flask application fixed it.
> 
> > I had a similar issue after upgrading from 2.14.0 and using connexion's FlaskApp instead of the Flask application fixed it.
> 
> @
> 
> > Hi @tariqjamal-abdulazeez, how are you running the application? You should run the Connexion application directly, not the underlying Flask application.
> 
> @RobbeSneyders I tried that also but it does not work for me

@RobbeSneyders While running with the connexion FlaskApp getting the below issue 
uvicorn run:application
ERROR:    Error loading ASGI app. Could not import module "run".

configuration:
flask=3.0.0
connexion=3.0.1

**Comment by tariqjamal-abdulazeez** [comment]
@RobbeSneyders Could you write a documentation for migration step by step ? because really i'm not able to make it works with the new version

**Comment by RobbeSneyders** [comment]
It's hard to write a general guide since users were using Connexion in many different ways. We spent a great amount of effort to update and improve [our documentation](https://connexion.readthedocs.io/en/latest/v3.html) for Connexion 3. Please try to use it to find your answers there.

If you run into specific errors, you can open an issue explaining the error and we can support on that error specifically. If we notice any gaps in our documentation based on these issues, we will update it.

**Comment by tariqjamal-abdulazeez** [comment]
> It's hard to write a general guide since users were using Connexion in many different ways. We spent a great amount of effort to update and improve [our documentation](https://connexion.readthedocs.io/en/latest/v3.html) for Connexion 3. Please try to use it to find your answers there.

@RobbeSneyders Previously i had working with flask=2.2.5 and connexion = 2.14.2 with this configuration the application request are correctly but due to some dependency i had upgraded the both package to their latest version, but in that the request are correctly getting in server and flask before_request is executed after then when it try to match the url with openapi duing that getting the issue

I had tried all possible according to the docs but it doesn't work for me
