### ISSUE TITLE
[Docs] "Edit on GitHub" link is broken

### ISSUE THREAD

**Issue by paketb0te** [spec-first/connexion#1797]
Currently the "Edit on GitHub" link in the docs ([https://connexion.readthedocs.io](https://connexion.readthedocs.io)) is broken, it points to `https://github.com/spec-first/connexion/blob/main/docs//docs/$PAGE` (where $PAGE is the current page of the docs you are looking at), resulting in a 404 on GitHub.

This appears to be due to the extra `/docs` in the URL.

**Comment by paketb0te** [comment]
My first assumption was that this is due to the settings in `docs/config.py`:

```py

    html_context = {
        'display_github': True,
        'github_user': 'spec-first',
        'github_repo': 'connexion',
        'github_version': 'main/docs/',   <--- this
    }
```
But when rendering the docs locally (`make html`), the link in the resulting html is correct.
So it might be something different...

**Comment by RobbeSneyders** [comment]
Thanks for the report and investigation @paketb0te!

Looks like [you were on the right track](https://docs.readthedocs.io/en/stable/guides/edit-source-links-sphinx.html#github).
