### ISSUE TITLE
How to get a custom security handler past spec validation

### ISSUE THREAD

**Issue by explody** [spec-first/connexion#1800]
### Description

Following the example here to implement a custom security handler https://connexion.readthedocs.io/en/stable/security.html#custom-security-handlers , the code is pretty straightforward but the spec using the new type fails to validate.

"type" fails validation
```
  securitySchemes:
    vantdex:
      type: vantdex
      x-vantdexInfoFunc: auth.vantdex_auth
```

### Expected behaviour

I was figuring that passing the custom security_map would just work, but it seems to have no effect here since the spec is checked against the schema.

### Actual behaviour

The yaml spec fails to validate, yielding this exception.

```
vantdex-backend-1   |   File "/usr/local/lib/python3.11/site-packages/connexion/spec.py", line 94, in _validate_spec
vantdex-backend-1   |     raise InvalidSpecification.create_from(e)
vantdex-backend-1   | connexion.exceptions.InvalidSpecification: {'type': 'vantdex', 'x-vantdexInfoFunc': 'auth.vantdex_auth'} is not valid under any of the given schemas
vantdex-backend-1   |
vantdex-backend-1   | Failed validating 'oneOf' in schema['properties']['components']['properties']['securitySchemes']['patternProperties']['^[a-zA-Z0-9\\.\\-_]+$']:
vantdex-backend-1   |     {'oneOf': [{'$ref': '#/definitions/Reference'},
vantdex-backend-1   |                {'$ref': '#/definitions/SecurityScheme'}]}
vantdex-backend-1   |
vantdex-backend-1   | On instance['components']['securitySchemes']['vantdex']:
vantdex-backend-1   |     {'type': 'vantdex', 'x-vantdexInfoFunc': 'auth.vantdex_auth'}
```

### Steps to reproduce

I believe just follow the custom security handler example.

### Additional info:

Output of the commands:

- `python --version` it's 3.11 in a venv
- `pip show connexion | grep "^Version\:"` it's 3.0.1

**Comment by RobbeSneyders** [comment]
Hi @explody,

Just to double check, do you want to:
1. Create a custom handler for an existing scheme
2. Create a handler for a scheme not supported by Connexion yet?

In case of (1.), you don't need to use a custom handler, but an `InfoFunc`. Check our [security documentation](https://connexion.readthedocs.io/en/latest/security.html) on the supported schemes and how to register an `InfoFunc` for each of them.

In case of (2.), you should define your security scheme to be OpenAPI compliant. I don't think you can have a custom `type`. You can have `type: http` and a custom `scheme` as long as you adhere to RFC 7235. ([OpenAPI docs](https://swagger.io/docs/specification/authentication/))
