### ISSUE TITLE
Duplicate parameters allowed

### ISSUE THREAD

**Issue by Elthas17** [spec-first/connexion#1809]
### Description
If you describe 2 times the same query parameter, the first one is used

  /hello:
    get:
      operationId: application.endpoints.endpoint.hello
      tags:
        - Hello
      summary: World
      parameters:
        - in: query
          **name: name**
          schema:
            type: string
          description: Your name
          **required: True**
        - in: query
          **name: name**
          schema:
            type: string
          description: Your name
          **required: False**

### Expected behaviour
Raise Exception? dont know what the open api spec enforces

### Actual behaviour
first parameter is used, duplicate parameter is ignored

### Steps to reproduce
- Please git pull the mimimal example i made for this issue on [connexion-issue repo](https://github.com/Elthas17/connexion-issue)
- use python 3.11.6 ,
- pip install requirements-working.txt to install requirements (the requirements-failing is for another created issue)
- run wsgi.py to start the flask app
- observe that the yaml /hello endpoint has 2 duplicate parameters, but the ui only uses the first instance of that parameter. the difference between the 2 parameters is if the parameter is required or not. 

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by RobbeSneyders** [comment]
Hi @Elthas17 

See my reply to your other issue: https://github.com/spec-first/connexion/issues/1808#issuecomment-1814634587. Your minimal example is not compatible with Connexion 3.

**Comment by Elthas17** [comment]
Sure. I do believe it has nothing to do with moving to connection 3. On that topic, i dont know how to get my flask configuration class loaded as per the flask factory methodology. Looking forward to your migration guide. good luck!
