### ISSUE TITLE
CORS headers not set on exception when using MiddlewarePosition.BEFORE_ROUTING

### ISSUE THREAD

**Issue by nielsbox** [spec-first/connexion#1820]
### Description
When using CORS Middleware the headers are not being returned when there are downstream exceptions.
This happens because the CORS Header is set after the exception middleware. Which does not include the CORS when shaping its error response.

### Expected behaviour
CORS headers are being returned when a ProblemResponse is shaped.

### Actual behaviour
They are not being returned

### Steps to reproduce
Use the example at https://connexion.readthedocs.io/en/latest/cookbook.html and make an invalid request which raises a 400 Bad Request.

### Additional info:

Output of the commands:

- `python --version`
3.10
- `pip show connexion | grep "^Version\:"`
3.0.2

**Comment by lotzej** [comment]
I can confirm this problem - we've experienced it too. We'd appreciate if the open PR, once confirmed, would make it into 3.0.3
