### ISSUE TITLE
Base path in server url or parameter not correctly handled

### ISSUE THREAD

**Issue by previ** [spec-first/connexion#1823]
### Description
OpenAPI definitions with server url with a base path (example: "http://localhost:8080/v1" are not correctly handled (error 404 or 500).

### Expected behaviour

Correctly handle the API with full path (server url + API path)

### Actual behaviour

Server raise exception, return 404 error code (or 500 in running with uvicorn):

```
% curl http://localhost:8080/v1/hello/world
{"type": "about:blank", "title": "Not Found", "detail": "Not Found", "status": 404}
```
or with uvicorn:
```
{"type": "about:blank", "title": "Internal Server Error", "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.", "status": 500}
```
### Steps to reproduce

Use the code in [this gist](https://gist.github.com/previ/ff19eb8c2d7385a502d270dc86141234), run it with the command:
```
connexion run openapi.yaml --host 0.0.0.0 --port 8080
```
or
```
uvicorn main:app --host 0.0.0.0 --port 8080
```

### Additional info:

It works if the server url is amended with base path and the base path "v1" is put in the API path.

Output of the commands:

- `python --version` `Python 3.11.6`
- `pip show connexion | grep "^Version\:"` `Version: 3.0.3`

**Comment by k-c-p** [comment]
Seems to be caused by `starlette` 0.33.0 which was [released a few days ago](https://www.starlette.io/release-notes/).
Downgrade to 0.32.0.post1 make it work again.
