### ISSUE TITLE
Base64 upload not working (tested with swagger-ui)

### ISSUE THREAD

**Issue by BoldizsarP** [spec-first/connexion#1825]
### Description
I am working on understanding multipart/form-data and in my example I have a binary and a base64 file example.

### Expected behaviour

I should be able to pass through both of them, together or seperately in the swagger-ui interface

### Actual behaviour

Binary upload is working, but base64 is not

### Steps to reproduce
I have zipped the workbench, just run it. And try to upload base64 according to the openapi

### Additional info:

I had to downgrade starlett to "<=0.32.0.post1" just to start it
[Base64Issue.zip](https://github.com/spec-first/connexion/files/13546915/Base64Issue.zip)

Output of the commands:

- `python 3.11.0`
- `Version: 3.0.3`

**Comment by RobbeSneyders** [comment]
Thanks @BoldizsarP, submitted a fix.
