### ISSUE TITLE
Adding typed custom config to Flask app?

### ISSUE THREAD

**Issue by uniqueg** [spec-first/connexion#1832]
Dear Connexion community,

For our Connexion-based microservice archetype [FOCA](https://github.com/elixir-cloud-aai/foca), we would like to add a custom configuration object to the Flask app wrapped by Connexion, such that:

1. the config params are readily accessible everywhere in a given service implementation making use of the archetype (including in application context when we import the `current_app`)
2. type information is available for our config params.

Currently, we define our custom configuration as a Pydantic model and then, after creating the Connexion app, we use `setattr()` to, well, set an attribute on the inner Flask `app` attribute to hold an instance of that model. This addresses the first problem, but not the second.

Now, this is not surprising, as we have no (easy) way of telling type checkers about the extra attribute, due to our crude use of `setattr()` on the instantiated Connexion app.

So instead, we would like to extend the Flask app to hold the extra attribute and then create the Connexion app based on our custom Flask app, such that eventually consumers of the archetype could use the modified Connexion App as a custom config-aware type hint for their app instances.

I suppose we could subclass for Flask like this:

```python
from flask import Flask

from foca.models.config import Config

class FocaFlaskApp(Flask):
    """FOCA extension of Flask app object."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.foca: Config
```

But then how do we make Connexion create the Connexion app with our custom Flask app?

And more generally: is this plan of subclassing Flask and Connexion sound, in your opinion? Or is there perhaps a simpler/cleaner solution to get us what we need?

Note that we are asking this here (and not, e.g., on StackOverflow) intentionally, because we feel that it would be nice to have a bit of documentation on how users can modify the Connexion and the underlying server apps (probably not an uncommon problem). However, if you feel that the issue is off topic, please close it.

Thanks a lot for your help :)

**Comment by RobbeSneyders** [comment]
Hi @uniqueg,

Instead of doing this via the Flask internals, I would recommend doing this via the ASGI mechanisms connexion 3 is built on.

- Either via a [lifespan](https://www.starlette.io/lifespan/#lifespan-state), which allows you to set the configuration at startup and make it accessible as state on the request.
- By implementing an ASGIMiddleware which makes it available as context. You can get inspiration from our own [`ContextMiddleware`](https://github.com/spec-first/connexion/blob/main/connexion/middleware/context.py) for this.
