### ISSUE TITLE
Flask `has_request_context` equivalent for AsyncApp

### ISSUE THREAD

**Issue by alfechner** [spec-first/connexion#1840]
I'm about to migrate from a Connexion 2.x FlaskApp to an Connexion 3.x AsyncApp.

In Flask we enhanced our log messages with data from the request object using a log filter.

We used [has_request_context](https://flask.palletsprojects.com/en/3.0.x/api/#flask.has_request_context) to check if we're actually operating inside a request.

Is there any way to determine if we operate in the context of a request with the [ContextMiddleware](https://connexion.readthedocs.io/en/latest/context.html)?

**Comment by RobbeSneyders** [comment]
Hi @alfechner, there is no similar function available. Best way to check this is probably by trying to access the context and catching any exceptions.
