### ISSUE TITLE
Release 3.0.6?

### ISSUE THREAD

**Issue by fbexiga** [spec-first/connexion#1875]
Is there any indication regarding when the next release would come out? Specifically because there are security issues that get fixed with the newer releases of Starlette, but connexion 3.0.5 depends on starlette<0.33.

**Comment by fralik** [comment]
Here is more information about the issue with starlette https://github.com/encode/starlette/security/advisories/GHSA-93gm-qmq6-w238

**Comment by RobbeSneyders** [comment]
[3.0.6](https://github.com/spec-first/connexion/releases/tag/3.0.6) is now out with bumped starlette version. Thanks for the push.

**Comment by glockenbach** [comment]
Good job! Thanks 👍
