### ISSUE TITLE
Add request as an optional kwarg to auth flow

### ISSUE THREAD

**Issue by kordian2k** [spec-first/connexion#1876]
### Description
In Connexion 2 the request could be accessed in the authentication validation function.

In Connexion 3 the [AbstractSecurityHandler](https://github.com/spec-first/connexion/blob/main/connexion/security.py#L108) already supplies the `required_scopes` as an optional kwarg to the validation function. This feature would allow to add the request instance as an optional kwarg, too.

### Rationale
In my case I need to access the request headers in the validation function. This can be achieved via a custom security handler, but seems too cumbersome just to access the request headers.

**Comment by RobbeSneyders** [comment]
Thanks @kordian2k,

I'm currently thinking of solving this as described in https://github.com/spec-first/connexion/issues/1750 instead. I assume that would work for you as well?

**Comment by kordian2k** [comment]
Yes, https://github.com/spec-first/connexion/issues/1750 should work as a solution to this issue. Thanks @RobbeSneyders
