### ISSUE TITLE
Middlewares are executed altough url doesnt exist in openapi spec

### ISSUE THREAD

**Issue by jasonlazo** [spec-first/connexion#1911]
### Description
I am using Connexion with flask, i have some custom ASGI Middlewares and hooks in flask (methods decorated with before_request). both are executed altought url path doesnt exist.

### Expected behaviour
I expect this code shouldnt be executed and the 404 should be returned cause connexion framework has a routingmiddleware that is called previously.

### Actual behaviour
The middlewares and hooks are called, and **Working outside of operation context** error is raised cause context and request connexion object are not accesible

### Steps to reproduce

Create a Connexion project with flask, create simple middlewares and hooks that uses context or request object and invoke a url path that doesnt exist

**Comment by RobbeSneyders** [comment]
Hi @jasonlazo, please provide a minimal reproducible example.
