### ISSUE TITLE
Trigger new release

### ISSUE THREAD

**Issue by andreas-sch-b** [spec-first/connexion#1919]
Not sure how to request that, so trying here. Would it be possible to trigger a new release?

I would be interested to use the merged feature [1] to be able to continue with the migration to connexion 3. 

Thanks!

[1] https://github.com/spec-first/connexion/commit/b3dd9862a3a724980d3cd1a11abf2c7a865aeccb

**Comment by RobbeSneyders** [comment]
This change is now available in [3.1.0](https://github.com/spec-first/connexion/releases/tag/3.1.0)
