### ISSUE TITLE
Error Logging

### ISSUE THREAD

**Issue by alfechner** [spec-first/connexion#1925]
There are several places Connexion logs errors, for example:

* When exceptions are handled in [`problem_handler`](https://github.com/spec-first/connexion/blob/fcfe151e690c8d8864605ff94923c8b8ce834bfb/connexion/middleware/exceptions.py#L73), [`http_exception`](https://github.com/spec-first/connexion/blob/fcfe151e690c8d8864605ff94923c8b8ce834bfb/connexion/middleware/exceptions.py#L80) or [`common_error_handler`](https://github.com/spec-first/connexion/blob/fcfe151e690c8d8864605ff94923c8b8ce834bfb/connexion/middleware/exceptions.py#L93) in the [`ExceptionMiddleware`](https://connexion.readthedocs.io/en/latest/middleware.html)
* When validation of the input/output data fails in [`connexion.validators.json`](https://github.com/spec-first/connexion/blob/fcfe151e690c8d8864605ff94923c8b8ce834bfb/connexion/validators/json.py#L71)

Connexion does a great job of handling exceptions by retuning a problem details with the appropriate status code to the user.

Now it's pretty common for operation teams to monitor exceptions in the logs and trigger alarms.

And here comes the issue:

Operations want to be alerted about everything that results in `5xx` status codes. That indicates that a situation couldn't be handled from a user perspective. Operations don't need to be alerted if the status code is `4xx`. Because those cases are gracefully handled.

I'd propose to

1. change [`ExceptionMiddleware`](https://connexion.readthedocs.io/en/latest/middleware.html) to log to `error` if the resulting status code is `5xx` and to `warning` for `4xx` and
2. remove the error log from [`connexion.validators.json`](https://github.com/spec-first/connexion/blob/fcfe151e690c8d8864605ff94923c8b8ce834bfb/connexion/validators/json.py#L71) since the `BadRequestProblem` raised is logged via the Exception middleware anyway.

I'm happy to contribute those changes. What do you think?

**Comment by Ruwann** [comment]
Thanks, @alfechner !

I can definitely understand where you're coming from. Based on the [Python documention on logging](https://docs.python.org/3/howto/logging.html), I agree that error logs for validation excpetions are indeed too severe as they are in most cases part of the normal flow of the application.

Note that you might be able to add a Filter for now to change the logging level for now (haven't tested it out myself): https://stackoverflow.com/questions/47412668/python-logging-change-warn-to-info
