### ISSUE TITLE
Gunicorn is not working with new Connexion 3.0.6

### ISSUE THREAD

**Issue by MachineLearning-Nerd** [spec-first/connexion#1932]
#### app.py
```python
import connexion
import os
import gunicorn.app.base
from flask_cors import CORS

app = connexion.FlaskApp(__name__, specification_dir="swagger/")

app.add_api("swagger.yaml")

APPLICATION_HOST = os.getenv("APPLICATION_HOST", "http://localhost")
whitelist = APPLICATION_HOST.split(",")
CORS(app.app, resources={r"/*": {"origins": whitelist}})

application = app.app

if __name__ == "__main__":
    # run our standalone server
    app.run(port=9090, host="0.0.0.0")
```
#### requirement.txt
```
connexion[swagger-ui,flask]==3.0.6
Flask-Cors
gunicorn
```

### Expected behaviour
while doing curl(Working with connexion[swagger-ui,flask]==2.14.2): 
```sh
$ curl -X GET http://127.0.0.1:9090/hello

{
  "message": "Hello, World!"
}
```

### Actual behaviour
```sh
$ curl -X GET http://127.0.0.1:9090/hello

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
```
Error:
flask-example  | Traceback (most recent call last):
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
flask-example  |     rv = self.dispatch_request()
flask-example  |          ^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 854, in dispatch_request
flask-example  |     self.raise_routing_exception(req)
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 463, in raise_routing_exception
flask-example  |     raise request.routing_exception  # type: ignore[misc]
flask-example  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/ctx.py", line 362, in match_request
flask-example  |     result = self.url_adapter.match(return_rule=True)  # type: ignore
flask-example  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 629, in match
flask-example  |     raise NotFound() from None
flask-example  | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
flask-example  |
flask-example  | During handling of the above exception, another exception occurred:
flask-example  |
flask-example  | Traceback (most recent call last):
flask-example  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 135, in handle
flask-example  |     self.handle_request(listener, req, client, addr)
flask-example  |   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
flask-example  |     respiter = self.wsgi(environ, resp.start_response)
flask-example  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
flask-example  |     return self.wsgi_app(environ, start_response)
flask-example  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
flask-example  |     response = self.handle_exception(e)
flask-example  |                ^^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
flask-example  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
flask-example  |                                                 ^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
flask-example  |     response = self.full_dispatch_request()
flask-example  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
flask-example  |     rv = self.handle_user_exception(e)
flask-example  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
flask-example  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
flask-example  |                                                 ^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 772, in handle_user_exception
flask-example  |     return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
flask-example  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-example  |   File "/usr/local/lib/python3.11/site-packages/connexion/apps/flask.py", line 245, in _http_exception
flask-example  |     raise starlette.exceptions.HTTPException(exc.code, detail=exc.description)
flask-example  | starlette.exceptions.HTTPException: 404: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
flask-example  |

### Steps to reproduce
- use this same app.py
- use this same requirements.txt
- swagger/swagger.yaml
```yaml
swagger: '2.0'
info:
  title: 'My API'
  version: '1.0'
paths:
  /hello:
    get:
      operationId: 'hello.hello_world'
      responses:
        200:
          description: 'Successful hello world response'
```
- hello.py
```python
def hello_world():
    return {"message": "Hello, World!"}
```

### Additional info:

Output of the commands:

- `python --version`
Python 3.11.9
- `pip show connexion | grep "^Version\:"`
Version: 3.0.6

command for gunicorn: `gunicorn -w 4 -b 0.0.0.0:9090 app:application`

**Comment by HariNani04** [comment]
This issue can be seen in all the 3.0.x versions of connexion and working fine on the old 2.14.2 version, But the old version has a dependency a vulnerable python packages.
Is there any breaking change as part of this new 3.0.x release?

**Comment by HariNani04** [comment]
Also, I found [this doc ](https://connexion.readthedocs.io/en/stable/v3.html#migrating-from-connexion-2) just now, looks like we have to change our code a bit in order for this to work.

app.py
`
import connexion
from a2wsgi import ASGIMiddleware
from connexion.lifecycle import ConnexionRequest, ConnexionResponse
from connexion.problem import problem

# Create the Connexion application and configure it
app = connexion.FlaskApp(__name__, specification_dir='./')
app.add_api('api_spec.yaml')

# Wrap the Connexion ASGI app with ASGIMiddleware to adapt it for WSGI
wsgi_app = ASGIMiddleware(app)

# Note: This 'wsgi_app' is what you'll need to point Gunicorn to.
`
Run the above file using `gunicorn 'app:wsgi_app'`

**Comment by RobbeSneyders** [comment]
Connexion implements the ASGI instead of the WSGI interface starting with Connexion 3.0.

See:
https://connexion.readthedocs.io/en/stable/v3.html#running-the-application
https://connexion.readthedocs.io/en/stable/quickstart.html#running-your-application
