### ISSUE TITLE
Upgrade dependencies (Flask)

### ISSUE THREAD

**Issue by LewisCowlesMotive** [spec-first/connexion#1958]
### Description

I got a dependency error that Jinja2 has a CVE from 2019. While I don't use it, a better fix might be to get the latest Jinja and Flask

### Expected behaviour

Feels a bit much, but no CVE's 😄 

### Actual behaviour

CVE's when running `poetry audit`

### Steps to reproduce

1. setup python
2. install package management solution (I use poetry)
3. Add the poetry audit plugin `poetry self add poetry-audit-plugin==0.3.0`
4. Run the poetry audit plugin `poetry audit`

### Additional info:

Output of the commands:

- `python --version` 3.11.9
- `pip show connexion | grep "^Version\:"` 3.1.0

**Comment by RobbeSneyders** [comment]
Installing Connexion installs the latest version of Jinja2, so there is nothing we can do.

Note that the CVE is being contested.
