### ISSUE TITLE
url_map is empty when creating a flask app

### ISSUE THREAD

**Issue by graham63** [spec-first/connexion#1971]
### Description
I'm using Connexion with openapi 3.0.0 to create a flask app, then running it with flask_socketio. Without flask_socketio I can use `curl http://localhost:8000/hello` to get the message from a `hello` function, even though the url_map is still empty. If socketio is added back in the routing isn't working at all. I'm using connexion v3.1.0, Flask-SocketIO v5.3.7, Flask v3.0.3.

### Expected behaviour
url_map should be populated with the routes hello, and get_site_layout.

### Actual behaviour
url_map just has one static route.

### Steps to reproduce
Clone the repo I made with a working example and run connexionApp.py
https://github.com/graham63/connexionApp.git

### Additional info:

Output of the commands:

- `python --version`
    Python 3.9.6

- `pip show connexion | grep "^Version\:"`
    Version: 3.1.0

**Comment by RobbeSneyders** [comment]
Since connexion 3, routing is no longer handled by Flask. Also, the Connexion `AsyncApp` now has native websocket support.

**Comment by graham63** [comment]
> Since connexion 3, routing is no longer handled by Flask. Also, the Connexion `AsyncApp` now has native websocket support.

Would you be able to point me toward documentation that mentions this, or an example? I still haven't been able to get connexion to work with socketio. There doesn't appear to be anything about sockets in the codebase, so I'm not sure I understand what you mean that it has native websocket support. 

In case you meant that socketio can run in parallel since it's asynchronous, I tried using python-socketio's AsyncServer class to attach the connexion app, and I tried mounting both the connexion app and a socketio asgi_app with FastAPI, then running with Uvicorn, but neither method has worked so far. 

Any additional help would be appreciated.

**Comment by RobbeSneyders** [comment]
I am not familiar with socket.IO. Please refer to `[their documentation](https://python-socketio.readthedocs.io/en/latest/server.html#running-as-an-asgi-application)`.

I assume this would look something like this for Connexion:

```python
import connexion
import socketio
import uvicorn

app = connexion.AsyncApp(__name__, specification_dir="spec")
app.add_api("openapi.yaml")

sio_app = socketio.ASGIApp(sio, app)

uvicorn.run(sio_app)
```

Related to the websockets, I meant you can now use [starlette websockets](https://www.starlette.io/websockets/) with the Connexion `AsyncApp`.
