### ISSUE TITLE
Why doesn't connexion support specific resolver's for validation functions ? 

### ISSUE THREAD

**Issue by JakobSachs** [spec-first/connexion#1985]
So I just stumbled across this while trying to add custom validators to my Connexion 3.0 based web service.
 
The docs (https://connexion.readthedocs.io/en/latest/security.html) say that:

> Note that even if you used a resolver for the operation id, it is not applied to the validation function, and you need to specify the complete path to the security module

Why is this? I've searched the open & closed issues and can't seem to find any discussion of this. Is it just purely practical (i.e. we've never needed/requested it, so we haven't implemented it) or is there some reason I'm not aware of? 

If all that's needed is someone to implement it, I could volunteer.

**Comment by RobbeSneyders** [comment]
Hi @JakobSachs, I don't think this has been decided with a clear reason. Most resolvers wouldn't work the security function though (`RestyResolver`, `MethodResolver`, `MethodViewResolver`). Only the `RelativeResolver` would, and I'm wondering how much value there is in that.
