### ISSUE TITLE
Extend helloworld RST with pip install-dependency command

### ISSUE THREAD

**Issue by chrisinmtown** [spec-first/connexion#1987]
### Description

Provide instructions so a novice can start the Connexion v3 "helloworld" example on the first try.

### Expected behaviour

The example runs on the first try.

### Actual behaviour

It takes a few tries to install all the prerequisites.

### Steps to reproduce

`python hello.py`

### Proposed addition to `README.rst`

* Create a new virtual environment
* Run `pip install 'connexion[flask,swagger-ui,uvicorn]>=3.1.0'`

### Discussion :)

I realize this is fairly trivial. Just trying to save the next person a little time. 

And  if you don't mind another suggestion, you might consider renaming the directory to "helloworld_flask", to keep it parallel with "helloworld_async" and similar names.

Please comment. I don't want to waste your time with a PR if this looks silly to you.

**Comment by RobbeSneyders** [comment]
That would probably be a nice change. Even better if it would be the same for all the examples :slightly_smiling_face:

**Comment by chrisinmtown** [comment]
I see this issue is tagged with "PR welcome" so I opened a PR to adjust the examples. Will someone please review?

**Comment by FelixSchwarz** [comment]
> I see this issue is tagged with "PR welcome" so I opened a PR to adjust the examples. Will someone please review?

Probably I missed something but I don't see a PR related to this issue...

**Comment by chrisinmtown** [comment]
> Probably I missed something but I don't see a PR related to this issue...

Well, the PR is here: https://github.com/spec-first/connexion/pull/1993

**Comment by FelixSchwarz** [comment]
Ah, sorry - I just noticed that your review request was roughly two days ago so I just checked the very recent PRs. :-)
