### ISSUE TITLE
parameter and masrshal_with generate TypeError: < > takes no arguments (# given)

### ISSUE THREAD

**Issue by fubarred** [spec-first/connexion#291]
### Description

Have a path in my swagger file with a query parameter. The path is handled by a controller. **The controller is marshaled using a dict**. It works fine if I dont use `@marshal_with`

Used to work fine until connexion version 1.0.109, but with later versions, the marshaling generates TypeError: get_greeting() takes no arguments (1 given)
**NOTE**: I am using python 2.7.6
### Expected bahaviour

API should return result **marshaled with the given dict**
### Actual behaviour

TypeError: get_greeting() takes no arguments (1 given)
### Steps to reproduce

**swagger.yaml** file

``` YAML
swagger: "2.0"
info:
  title: "Hello World Example"
  version: "1.0"

paths:
  /greeting:
    get:
      summary: Generate greeting
      operationId: hello.get_greeting
      parameters:
        - name: name
          in: query
          type: string
          required: true
      responses:
        200:
          description: greeting response
```

**hello.py** file

``` python
#!/usr/bin/env python2

import connexion
from flask_restful import marshal_with, fields

greeting = { 'name': fields.String }


@marshal_with(greeting)
def get_greeting():
    return {'name': 'bar'}

if __name__ == '__main__':
    app = connexion.App(__name__, 9090, specification_dir='.', debug=True)
    app.add_api('swagger.yaml')
    app.run()
```

**api call**
`curl http://localhost:9090/greeting?name=foo`
### Additional info:

**Traceback output**
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/validation.py", line 287, in wrapper
    response = function(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/produces.py", line 118, in wrapper
    data, status_code, headers = self.get_full_response(function(_args, *_kwargs))
  File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/parameter.py", line 151, in wrapper
    return function(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 679, in wrapper
    resp = f(_args, *_kwargs)
TypeError: get_greeting() takes no arguments (1 given)

Output of the commands:
- `python --version`
  Python 2.7.6
- `pip show connexion | grep "^Version\:"`
  Version: 1.0.121

**Comment by hjacobs** [comment]
I haven't looked at it yet, but I assume "marshal_with" changes the signature to include `**kwargs`? Connexion would now pass the parameter (`**kwargs` were not supported in older versions).

**Comment by hjacobs** [comment]
Why do you need/use `marshal_with` at all?

**Comment by pkjg** [comment]
yes I do need marshal_with. Object I am returning has some extra stuff so if I dont use marshal_with, it gives me this error:

File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 239, in default
    raise **TypeError(repr(o) + " is not JSON serializable")**

**Comment by hjacobs** [comment]
@pkjg as a "workaround" you can also customize the JSON encoder: http://connexion.readthedocs.io/en/latest/response.html?highlight=json#customizing-json-encoder

**Comment by rafaelcaricio** [comment]
@pkjg Thanks for reaching out and using Connexion.

You have defined in your API you have the parameter as `required: true`. So Connexion is trying to pass this positional argument to your operation handler as expected. That is how it should work, you operation handler function is not compliant with what you defined in your OpenAPI Spec.

As a improvement maybe we should make it more clear by raising a custom Connexion exception pointing this out.

Something like:
```
OperationHandlerError: The endpoint "/greeting" method GET has a required argument "name" though the operation handler get_greeting() takes no arguments (1 given)
```

**Comment by hjacobs** [comment]
@rafaelcaricio I think your observation is wrong as the `required: true` is unrelated to the handler function, we allow people to have handler functions without any parameters even when the operation defines some. This is IMHO good as the whole Flask request object is always available anyway

**Comment by pkjg** [comment]
@rafaelcaricio yes @hjacobs is right. Its unrelated to `required`. In fact, same error on `required: false`.

**Comment by rafaelcaricio** [comment]
👍
