### ISSUE TITLE
Add Swagger Editor

### ISSUE THREAD

**Issue by samperd** [spec-first/connexion#408]
### Description
As a developer
I want access to the swagger editor as part of my app
So that I can edit the API SWAGGER definition live and save it locally once new functionality is added

### Expected behaviour
Editor is accessible at [server URL]/editor

### Actual behaviour
No such link yet

### Steps to reproduce
Point your browser to: http://[server URL]/editor

### Additional info:
I assume it would be housed in the vendor sub-directory with a static file path defined
Swagger editor is here: http://swagger.io/swagger-editor/

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by hjacobs** [comment]
I see that this could be a useful feature, but I'm not whether the Swagger Editor should be included by default or at all...

**Comment by rafaelcaricio** [comment]
I really wish to remove the Swagger UI from being a vendor in Connexion (https://github.com/zalando/connexion/issues/406). I would like to have the Swagger UI and Editor as a separated package that can be installed apart from the Connexion package. We could add hooks in Connexion to enable functionality from those packages if they are installed in the same Python installation where Connexion code is running.

What do you think about this approach?

**Comment by samperd** [comment]
Hey Folks,

Thanks for the prompt response.

I am just starting out with Flask, Connexion and Swagger and the project I am working on I want to be super accessible by amateur and pro python programmers alike. Think summer students or co-op students working in a government organization. I don't have too many cycles to dedicate to bringing new students up to speed. They need to be going in 1-2 weeks for a 4 month experience.

As a newbie, I really appreciated having the UI as part of the distro because it meant I could get started quickly. I also went ahead and downloaded the editor and ran it through NODEJS. The main challenge I had was that the UI and my API played nicely, but I ran into CORS issues with the editor. As a backup I used the online editor for a bit but the workflow was chunky with continual imports, edits, exports, run the API and the start over again. Also my dev API is behind a firewall so I could not interact with the API through the online editor directly. Not a flow for the faint of heart.

With the UI and Editor as part of the same package or at least living on the same localhost port and with relative paths means that very quickly our users and developers get a nice little IDE that results in a functional and compliant API. I also want to avoid complicate proxy situations and I want to avoid diving into apache for this project.

I even tried loading the editor as a static resource, however I think I need to compile the JS in the editor to get the ./dist directory which is not available through github. I really don't want to have to compile code to run some static files.

I agree that maintaining custom code is not ideal. The less you need to maintain 3rd party code the better. The more energy that can be focused on the core project.

In the end I am looking for solutions and frameworks that help lower the bar to entry, are accessible to students and facilitate lean and agile workflows.

I am open to ideas how I can have a project with the following endpoints ready to go for our first time users/developers

[SERVER URL]/
[SERVER URL]/[wonderful API Stuff]
[SERVER URL]/ui
[SERVER URL]/editor
[SERVER URL]/docs

Thanks for any comments, thinking, or effort on this issue.

**Comment by hjacobs** [comment]
@samperd I totally get your use case and I want to make it as easy as possible for newbies to get started. I think the discussion is mostly about *how* to do it, i.e. whether to have a tight dependency to Swagger Editor. I would prefer a pluggable approach where we only pull in dependencies as needed, e.g. with `pip3 install connexion[all]`.

**Comment by xylix** [comment]
If you're looking for a noob-friendly solution for swagger file editing [OpenAPI designer](https://openapi.design/) could be helpful (github [here](https://github.com/apinf/openapi-designer)). It is pretty easy to compile. Editing local files live is not supported yet but if there is interest it's pretty easy to implement.

**Comment by hjacobs** [comment]
@xylix check out our [IntelliJ Swagger Plugin](https://github.com/zalando/intellij-swagger), I think it's pretty nice for local editing (also works with community/OSS edition of IntelliJ).
