### ISSUE TITLE
Proposal for more fine-grained input contract type validations

### ISSUE THREAD

**Issue by tomas-fp** [spec-first/connexion#423]
This is simply an informal nice-to-have proposal to evaluate doing more fine-grained type assertions as part of the validation layer based on API input contract annotations via OpenAPI specification. 

This might partially break the Postel's Law about robustness principle, but it is certainly convenient for some kind of APIs where consumer are mostly humans and error-prone while consuming the API.

Some of the scenarios it would be nice having covered here would be:

- for integer types if we pass each of the following values `["foo", None, True, False, [], {}, (), 234.243527, 0.0]`, the values `True` and `234.243527` are valid, but the rest all return the error message `limit must be an integer`. 0.0 returns no results, but other floats do not.

- for a list type of string items, if we pass each of the following values `[None, True, False, {}, 9, 234.24, 0.0, -1, []]`, the values `[None]`, `[[]]`, and `[{}]` works instead of no results (or a validation `400` message)

Those inconsistencies were discovered by our QA team while testing the APIs. I'm sure there could be more if we do more fuzz testing.

What do you think about this proposal?
I'm open to collaborate if the proposal has serious chances to be included within the project.

**Comment by hjacobs** [comment]
@tomas-fp thanks, your QA team's discoveries are certainly valuable! I think we should follow the principle of "least surprise", maybe you can draft out some desired behavior (as comments here?) we can discuss on. Adding the validation would probably be simple and easy to unit test.

**Comment by RobbeSneyders** [comment]
Validation is done by `jsonschema` and [can be extended](https://connexion.readthedocs.io/en/latest/cookbook.html#custom-type-format).
