### ISSUE TITLE
[Question] Support for date and date-time formats

### ISSUE THREAD

**Issue by tyomo4ka** [spec-first/connexion#451]
Help wanted

### Expected behaviour

```
  Scenario: Invalid date
    When I send POST request to "/myUrl":
"""
{
  "effectiveDateTime": "this is an invalid date time string, but in my spec date-time format is specified"
}
"""
    Then response code should be 400
```
### Actual behaviour

Connexion passes object to the controller.

Is there reasons why it is not implemented? 
Should I use custom type format as described here?http://connexion.readthedocs.io/en/latest/cookbook.html? 
How can I force casting into datetime object?

**Comment by tyomo4ka** [comment]
Ok, validation has been solved using this receipt: http://connexion.readthedocs.io/en/latest/cookbook.html?

Can someone help me to solve type casting. It would be super awesome to solve casting issue in the similar way.

**Comment by rafaelcaricio** [comment]
@tyomo4ka I am glad you found a solution to your problem. About the type casting, in the OpenAPI Spec [the data type of date-time and date is string](http://swagger.io/specification/#data-types-12). You for those types you will need to convert to `datetime` yourself.

I think would be interesting to have a way create custom new type casting supported by Connexion. But currently that is not the case. We are always happy to accept Pull Requests.

**Comment by tyomo4ka** [comment]
@rafaelcaricio 

Thanks for your reply.

Yeah, right. I know it's a string with `format` field set to `date` or `date-time` value in Open API spec.

However I guess it is a must have feature to cast dates/times automatically. Cause this is what  _all_ developers need to implement in their apps.

In terms of custom conversions I guess it is useful for many projects as well. Even in your example for adding custom validation for money format... it would be nice to not just validate it, but cast conversion to Money value object as well.

I guess the best place to cast types is straight after validation. Is there any code which I can use to match payload fields with specification configs implemented? From what I understand it uses JSON Schema lib for validation, so I might find some code in that lib?

P.S.: So far solved my issues by iterating over payload and casting everything which looks like datetime. But it's not ideal of course.

**Comment by RobbeSneyders** [comment]
Closing in favor of https://github.com/spec-first/connexion/issues/344
