### ISSUE TITLE
swagger API specification from another repository

### ISSUE THREAD

**Issue by roman-telepathy-ai** [spec-first/connexion#456]
### Question
is it possible to point to the `swagger.yaml` located in another git repository?
or even better to a json format which I deploy on my own "www.api.com/service/swagger.json"

### Example
app = connexion.App('dummy', specification_dir='https://github.com/..../swagger')
app.add_api('swagger.yaml', strict_validation=True, validate_responses=True)

**Comment by RobbeSneyders** [comment]
No this is not supported.
You can fetch the specification and pass it in.
