### ISSUE TITLE
Is there a way to secure the API endpoint (/swagger.json)? And the swagger UI as well?

### ISSUE THREAD

**Issue by rwitzel** [spec-first/connexion#501]
Even if OAuth security is configured on top level, the API endpoints (/swagger.json and /ui) are not secured.

How can these endpoints be secured? It is a bit of a problem that they are not secured at the moment.

**Comment by bobh66** [comment]
I have the same issue.  I think I can work around it with a before_request method, but it seems like there has to be a better way.

**Comment by RobbeSneyders** [comment]
You can do this by [customizing the middleware stack](https://connexion.readthedocs.io/en/latest/middleware.html#customizing-the-middleware-stack) and moving the swagger ui middleware after the security middleware.
