### ISSUE TITLE
Question -- Passing arbitrary arguments into the Controller functions?

### ISSUE THREAD

**Issue by jasonrhaas** [spec-first/connexion#516]
### Description

Hey guys -- Great tool! Thank you for making it open source and supporting it.

I have a situation I just can't seem to figure out --  is there a way to pass arbitrary arguments to the Controller functions when they get run? As it stands, the Swagger Yaml allows for the `path: parameters`, which line up with the controller parameters. But what if I need to pass additional things into the function, like an instance of my Flask SQLAlchemy Db, or my data models? Is that possible?

Is the example https://github.com/zalando/connexion/blob/master/examples/sqlalchemy/app.py they use global variables for the db, but that is not practical for a large application

### Additional info:

Output of the commands:

Python 3.6.2
Connexion Version: 1.1.15

**Comment by hjacobs** [comment]
You cannot pass arbitrary parameters AFAIK right now, but you Connexion can also resolve to (global) instances or static methods, i.e. you don't need to have global objects.

**Comment by hjacobs** [comment]
Sorry, I don't have any good examples right now as I try to keep it simple (modules, functions, done).

**Comment by jasonrhaas** [comment]
@hjacobs I don't quite understand.  

I enjoy up working around this by instantiating my class in name namespace at the swagger controller (global var), and then importing that to the rest of my code.  I don't love it, but it works for now.

**Comment by kanjieater** [comment]
Also running into issues with this. I'd like to be able to pass an argument for dependency injection purposes, but it doesn't seem that this is supported currently.

**Comment by languitar** [comment]
I tried realizing a similar use case with flask-injector. However, optional request bodies result in an exception in case no body is given.

**Comment by madopal** [comment]
Why is this marked as completed? The suggestion above is a hack at best. Is it so much to ask that the classes can accept some arbitrary args? The use case above would seem to be well within the expected use cases (like, connecting to a database with credentials).

**Comment by chrisinmtown** [comment]
@madopal which suggestion do you feel is a hack? I believe a custom resolver will allow you to add arbitrary arguments in the calls to your functions. Documentation is here: https://connexion.readthedocs.io/en/latest/routing.html
