### ISSUE TITLE
Attempting to run a DELETE request with an empty, non-required body returns a 400

### ISSUE THREAD

**Issue by martsa1** [spec-first/connexion#517]
### Description
When defining a DELETE endpoint, I have an optional body parameter of type array to provide a list of keys to delete.  If I provide that list, the endpoint will delete just those keys (this works fine).

What I would like to do is to make the body parameter on the delete request optional, such that if I don't provide it, I expect the endpoint to delete all its elements.

### Expected behaviour
When the DELETE request is called with no body, Connexion passes the body parameter as None to the endpoint handler function.

### Actual behaviour
Connexion returns a 400 error:
```
{
  "detail": "None is not of type 'array'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

### Steps to reproduce
Define a DELETE endpoint such as:
```yaml
paths:
  /items/:
    delete:
      summary: Delete a list of items or all of them
      description: |
        Given a list of IDs the end point will delete them. If however provided
        an empty list, the end point will delete all items
      operationId: delete_items
      produces:
         - application/json
         - application/problem+json
      parameters:
        - $ref: "#/parameters/items_keys"
      responses:
        200:
          description: Items deleted.
          examples:
            application/json:
              "\"Items Deleted\""

parameters:
  items_keys:
    name: forDelete
    description: IDs for deletion
    in: body
    required: false
    schema:
      type: array
      items:
        $ref: "#/definitions/key"

definitions:
  key:
    additionalProperties: false
    type: string
```

And an endpoint:
```python
def delete_items(forDelete):
    # Do some stuff here using either a list or a None type for forDelete    
    pass
```

### Additional info:

Output of the commands:

- `python --version`
```
Python 3.5.2
```
- `pip show connexion | grep "^Version\:"`
```
Version: 1.1.9
```

**Comment by JuxhinDB** [comment]
I would have a similar situation, except related to a `POST` request that does not require any request body. Currently sending:

```
POST /foo
Content-Type: application/json
```

Returns a 400 Bad Request. However specifying the following:

```
POST /foo
Content-Type: application/json

{}
```

Works fine and returns a 200 OK. Was wondering if you had come up with a cleaner solution to this by any chance.

**Comment by victor-arcane** [comment]
+1 
Any update on this issue? Or how to solve it ?

**Comment by dtkav** [comment]
We follow the openapi specification on this, which states that the requestBody SHALL be ignored for DELETE requests:

> The request body applicable for this operation. The requestBody is only supported in HTTP methods where the HTTP 1.1 specification [RFC7231] has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague, requestBody SHALL be ignored by consumers.

from: http://spec.openapis.org/oas/v3.0.2#fixed-fields-7

> A payload within a DELETE request message has no defined semantics; sending a payload body on a DELETE request might cause some existing implementations to reject the request.

from: https://httpwg.org/specs/rfc7231.html#DELETE
