### ISSUE TITLE
Multiple Versions in Same API

### ISSUE THREAD

**Issue by mcrowson** [spec-first/connexion#531]
### Description
I'm looking for best practices for implementing multiple versions of an API. The issue I'm seeing is that the different versions all point to the same controllers. It is possible for different API versions to need different business logic in the controllers. 

This is more of a documentation issue as I'm sure it is possible. I see that each version gets its own Flask blueprint, but I'm not sure what best practices are.

### Expected behaviour
Single API supports multiple versions

### Actual behaviour
Both API versions share the same business logic (point to same controllers and controller functions)

### Steps to reproduce
Get a swagger spec file and launch two APIs (each indicating a different version).

Then launch the API using each version

```python
app = connexion.App(__name__, specification_dir='./swagger/')
app.add_api('petstore.yaml',  base_path='/1.0')   
app.add_api('petstore.yaml',  base_path='/2.0')  # We want to change underlying business logic with this one

if __name__ == '__main__':
    app.run(port=8080)
```

### Additional info:

Output of the commands:

- `python --version` . 3.6.3
- `pip show connexion | grep "^Version\:"` 1.1.15

**Comment by mcrowson** [comment]
I'm guessing the operationId could be used assuming you version name each of those each time, but I also wonder about model versioning.

**Comment by hjacobs** [comment]
@mcrowson this probably won't help you, but we strongly discourage versioning REST APIs in Zalando Tech --- see http://zalando.github.io/restful-api-guidelines/#113
