### ISSUE TITLE
Add automatic status code sending

### ISSUE THREAD

**Issue by ThomasHickman** [spec-first/connexion#539]
If a swagger method has one specified 200-299 status code in it's swagger specification, it would be nice if connexion automatically returned this status code e.g. if the specification contained:
```yaml
delete:
    operationId: delete
    responses:
    '204':
        description: Succeeded, no response
    default:
        description: Error
        schema:
        $ref: "#/definitions/Error"
```
The handler for this:
```python
def delete():
    delete_something()
```
should result in a 204 status code being sent

**Comment by hjacobs** [comment]
I think this is a reasonable idea, not sure how many cases this will match, but `delete` is certainly one of the common ones.
