### ISSUE TITLE
Incorrect validation of required body properties

### ISSUE THREAD

**Issue by ThomasHickman** [spec-first/connexion#548]
### Description
If you have a OpenAPI specification with a required body parameter:
```yaml
swagger: "2.0"
paths:
  /endpoint:
    parameters:
      - name: param
        in: body
        required: true
```
Querying this endpoint does not report an error if the body is not specified

### Expected behaviour

Connexion should give a 400 error.

### Actual behaviour

The correct function is called, with the value of the parameter as `None`.

### Steps to reproduce

Make a connexion server with an OpenAPI specification similar to above, and query the correct endpoint with no body

### Additional info:

Output of the commands:

- `python --version`: `Python 2.7.10`
- `pip show connexion | grep "^Version\:"`: `Version: 1.2`

**Comment by mvalkon** [comment]
@ThomasHickman in order for us to easily reproduce this issue, could you please provide a full example?

**Comment by tomghyselinck** [comment]
Hi,

I have seen a similar issue with the OpenAPI v3.0 spec.

Please see my issue post [Missing required argument on PUT, POST, PATCH](https://github.com/OpenAPITools/openapi-generator/issues/1666) in [openapi-generator](https://github.com/OpenAPITools/openapi-generator).

**Comment by dtkav** [comment]
I think #815 might be related.

**Comment by tomghyselinck** [comment]
@dtkav : When I look in the connexion code, I think it is more related to the missing `x-body-name` in the schema.

But where can I find proper documentation for this `x-body-name` directive?

**Comment by tomghyselinck** [comment]
See also #579 which is related.

**Comment by cziebuhr** [comment]
`x-body-name` is for openapi 3 and defaults to `body`. This is swagger 2.
I also want to see a full example, because IMHO due to nature of http, one can't distinguish between an empty body and an "not specified" body.

**Comment by tomghyselinck** [comment]
@cziebuhr See my [earlier post](https://github.com/zalando/connexion/issues/548#issuecomment-446535545) for a a link to a full example (for OpenAPI 3.x): [#1666 - Missing required argument on PUT, POST, PATCH](https://github.com/OpenAPITools/openapi-generator/issues/1666)

**Comment by Johnlon** [comment]
https://github.com/zalando/connexion/issues/1452 is a PR that permits the x-body-name in an OAS3 compliant location to extend compat to Openapi Generator

**Comment by andreikitaitsev** [comment]
Hello! I have the same behaviour with OPEN API 3.0.0 and connextion 2.14.0:

```
openapi: 3.0.0
info:
  title:  API
  version: 0.0.0
paths:
  "/":
    post:
      operationId: some_func_id
      requestBody:
        required: true
        content:
          application/json; charset=utf-8:
            schema:
              "$ref": "#/components/schemas/CalculationRequest"
      responses:
        '200':
          description: Calc successfully finished
        '400':
          description: Exception during payload parsing.
    get:
      operationId: calc request get
      responses:
        '200':
          description: 'Use post and send data 

components:
  schemas:
    CalculationRequest:
      type: object
      additionalProperties: false
      required:
        - accountGroupId
        - accountIds
      properties:
        accountGroupId:
          type: string
        accountIds:
          type: array
          items:
            type: string


# create application
options = {'swagger_path': '/swagger-ui/', "swagger_ui": True}
application  = connexion.FlaskApp(__name__, specification_dir='./', options = options)
application.add_api('api_specification.yaml', strict_validation=True)
app = application.app
```

When I post the data with the wrong fields or with required fields missing no validation error happens.
It seems, validation does not happen at all.

Example of correct post request:
{"accountGroupId": "123",
"accountIds":
    ["accounts-1234",
    "accounts-2134"
    ]}
Response: valid payload

Example of incorrect post request:
{"lalala": "123",
"accountIds":
    ["accounts-1234",
    "accounts-2134"
    ]}
Expected Response: non-valid payload
Actual response: validation does not throw any error.
