### ISSUE TITLE
Overriding route-specific 404s to a custom response

### ISSUE THREAD

**Issue by JuxhinDB** [spec-first/connexion#550]
### Description

Currently the default response for route-specific 404s (basically, hitting a route that doesn't exist `/nonexist-file`) if as follows:

```
{
  "detail": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.",
  "status": 404,
  "title": "Not Found",
  "type": "about:blank"
}
```

However the rest of [my] the API responds in the following structure:

```
{
    "code": "ERR_SPECIFIC_NOT_FOUND" 
}
```

And as a result, I would like the default response to also follow the same structure. 

I have taken a look at the following:

- https://github.com/zalando/connexion/issues/138
- https://github.com/zalando/connexion/pull/281

However it still didn't seem quite obvious as how to achieve this (sorry!)

### Expected behaviour

Route-specific 404s should respond with a similar structure to the rest of the API.

### Actual behaviour

Route-specific 404s respond with the default response mentioned above.

### Steps to reproduce

Spin up Flask application with Connexion and send request to:

```
GET /test-nonexistent-route HTTP/1.1
Host: localhost
```

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

```
>>> python --version
>>> Python 3.6.1
```

```
>>> pip show connexion | grep "^Version\:"
>>> Version: 1.1.5
```

**Comment by drselump14** [comment]
I  have the same issue, did you able to solve it?

**Comment by drselump14** [comment]
Found the solution

```python

def render_not_found_error(_):
    return Response(status_code=404)

app.add_error_handler(404, render_not_found_error)
```
