### ISSUE TITLE
how to turn off auto serialization?

### ISSUE THREAD

**Issue by tommyjcarpenter** [spec-first/connexion#552]
### Description

I have an endpoint that returns an html page. How do I turn off serialization so that it renders in the browser?

E.g.,

```
def my_handler():
    return render_template(...)
```

Output of the commands:

- `python --version`
3.6.3
- `pip show connexion | grep "^Version\:"`
Version: 1.1.10

**Comment by samh** [comment]
From the documentation, it looks like you can either return a Response object, which will be used as-is, or set the endpoint to have a different mime-type in the OpenAPI file (it only serializes if it's a JSON endpoint). See https://connexion.readthedocs.io/en/latest/response.html.
