### ISSUE TITLE
Connexion does not support instance_relative_config param

### ISSUE THREAD

**Issue by j-zimnowoda** [spec-first/connexion#556]
### Description

It looks like you do not pass any parameter to Flask in create_app method
E.g.:

```
app = connexion.App(__name__, specification_dir='swagger/', instance_relative_config=True)
```
does not pass instance_relative_config param to Flask

### Expected behaviour

Loading configuration from instance_path
### Actual behaviour

Loading configuration from root_path

### Steps to reproduce

Create **instance/config.py** file, in your module directory, with below content:

```
DEBUG = True
TESTING = False
HOST_IP = '127.0.0.1'
HOST_PORT = 9090
TESTING = False
```

Create **app.py** with below content
```
    app = connexion.App(__name__, specification_dir='swagger/', instance_relative_config=True)
    app.app.config.from_pyfile('config.py')
```

Observe that module cannot be loaded

### Additional info:

Output of the commands:
Python 3.6.3
connexion == 1.2

**Comment by j-zimnowoda** [comment]
A quick workaround for this issue is to overwrite root_path in Falsk Config object before loading config
```
app.app.config.root_path = app.app.instance_path
```

**Comment by ovunccetin** [comment]
I have extended FlaskApp as follows: 

`class ConfigurableFlaskApp(connexion.FlaskApp):
    def __init__(self, import_name, **kwargs):
        self.flask_args = _get_flask_args(kwargs)
        connexion_args = _get_connexion_args(kwargs)
        super().__init__(import_name, **connexion_args)

    def create_app(self):
        app = flask.Flask(self.import_name, **self.flask_args)
        app.json_encoder = FlaskJSONEncoder
        return app`

You can use it as follows: 
`app = ConfigurableFlaskApp(__name__, flask_instance_path='/path/to/flask/instance')`

**Comment by RobbeSneyders** [comment]
Can be done via `server_args`
