### ISSUE TITLE
Using https all the way

### ISSUE THREAD

**Issue by FrankCRoth** [spec-first/connexion#563]
### Description
I am using cloud foundry to host my flask app. CF is configured to allow https as well and I can reach the swagger GUI using https. However not any of the controller that I used. Is there a specific setting that I need to use to allow https for the actuall implementation?

**Comment by hubertgrzeskowiak** [comment]
Also just stumbled upon this problem. I'd like to have the Swagger UI run with http locally and with https in production. How would I go about that?
