### ISSUE TITLE
Support adding fixed parameters to the function in the operationId 

### ISSUE THREAD

**Issue by WimDH** [spec-first/connexion#569]
Different API endpoints use the same python code, but with a different parameter (like a template), which is not part of the payload, and depends on the the endpoint.
for example `http://127.0.0.1/api/v1/server/interfaces` uses a python class or a function that parses interface data using the template which depends on the API endpoint.
So, I would need an operationId like `myapi.view.genericparser`, which takes as a first argument the template, and as other arguments the ones in the API query, path or body.
The function would look like: 

```
def myfunc(fixed_var, *args, **kwargs):
    # your code
```
or 
```
class MyClass(object):
    def __init__(fixed_var)
         self.fixed_var = fixed_var

    def __call__(*args, **kwargs):
         # Your code
```

Anyone had a similar request?

**Comment by mohabusama** [comment]
Hi @WimDH It might not be so clear to me, but I was just wondering whether you can use something like a generic handler class and other detailed ones representing the resources:

```python
class GenericHandler:
    @classmethod
    def get(cls, *args, **kwargs):
         inst = cls()
         # generic stuff depending on inst methods impl and inst.fixed_var

class SpecificResourceHandler(GenericHandler):
    fixed_var = 'specific value'
    # more methods etc...
```

and in swagger, use ``myapi.view.SpecificResourceHandler.get``
