### ISSUE TITLE
How to use swagger_codegen_config.json params 

### ISSUE THREAD

**Issue by jpoullet2000** [spec-first/connexion#575]
### Description

When I generate python-flask code from swagger.yaml file I'm using the following command: 

`java -jar ~/swagger-codegen-cli.jar generate -i det/swagger/swagger.yaml -l python-flask -o ~/runner -c det/swagger/python_codegen_config.json`

where the content in  `det/swagger/python_codegen_config.json` is  simply
```
{"packageName": "det"}
```

This allows me to have a package name different from `swagger_server` (`det` here).

However, when I'm using the command: 
```
python -m det
```
it returns the following error:
```
Failed to add operation for POST /detapi/0.0.1/typedefs
Traceback (most recent call last):
  File "/home/jbp/miniconda3/envs/det/lib/python3.6/site-packages/connexion/apis/abstract.py", line 242, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/home/jbp/miniconda3/envs/det/lib/python3.6/site-packages/connexion/apis/abstract.py", line 195, in add_operation
    pythonic_params=self.pythonic_params)
  File "/home/jbp/miniconda3/envs/det/lib/python3.6/site-packages/connexion/operation.py", line 215, in __init__
    resolution = resolver.resolve(self)
  File "/home/jbp/miniconda3/envs/det/lib/python3.6/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jbp/miniconda3/envs/det/lib/python3.6/site-packages/connexion/resolver.py", line 65, in resolve_function_from_operation_id
    raise ResolverError(msg, sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "swagger_server.controllers.admins_controller.add_typedefs"! Import error was "No module named 'swagger_server'">
```

with the `__main__.py` file:
```
#!/usr/bin/env python
import connexion
from det import encoder


def main():
    print(__name__)
    app = connexion.App('det', specification_dir='./swagger/')
    app.app.json_encoder = encoder.JSONEncoder
    app.add_api('swagger.yaml', arguments={'title': 'Data engineering toolkit API'}) 
    app.run(port=8080)  
  

  if __name__ == '__main__':
      main()
``` 

Is there a way to take the parameters of `det/swagger/python_codegen_config.json` into account ? Anything to change in the `__main__.py` file. It keeps pointing to the default `swagger_server` module which does not exist here. 

### Additional info:

Output of the commands:

- `python --version` : `Python 3.6.4 :: Anaconda, Inc. `
- `pip show connexion | grep "^Version\:"` : `Version: 1.1.15`

**Comment by mohabusama** [comment]
@jpoullet2000 just to confirm, the swagger file has ``swagger_server.controllers.admins_controller.add_typedefs`` as an ``operationId``? Is there a reason not to adjust this value in swagger.yaml?

**Comment by mohabusama** [comment]
In case updating swagger file is not possible, then I would go with specifying a custom resolver which adjusts the import paths etc...

https://github.com/zalando/connexion#automatic-routing

**Comment by jpoullet2000** [comment]
I could probably define for each resource the `operationId` variable but it is quite painful. What I was looking for is some similar behavior as for the config file with the `swagger-codegen-cli` command. 
I guess renaming the package should be a basic feature... but I cannot figure out how to do it using `connexion`. 

`connexion` tries to find the method: `swagger_server.controllers.admins_controller.add_typedefs`
where 
- swagger_server = default package name (that is what I want to change ;) )
- controllers = module automatically generated by swagger
- admins_controller = module that comes from a tag in the swagger.yaml file
- add_typedefs = operationId in yaml file   

If I rename my package folder `det` into `swagger_server` it works but that is not the purpose :)

About the  `RestyResolver`, I guess I should then have 
```
app.add_api('swagger.yaml', resolver=RestyResolver('det')) 
```
but I still get the same error (maybe I don't get how it works).

**Comment by jpoullet2000** [comment]
What I ended up doing is to define for all resource methods the `x-swagger-router-controller` var. 
E.g.
`x-swagger-router-controller: "det.controllers.developers_controller"`

Another way that would probably have worked is to pass a custom `function_resolver` (instead of the default [`utils.get_function_from_name`](https://github.com/zalando/connexion/blob/master/connexion/utils.py)) when initializing the `RestyResolver` instance. 

```
app.add_api('swagger.yaml', 
            resolver=RestyResolver('det', function_resolver=my_custom_resolver_function))
```

I haven't tried the latter solution.
