### ISSUE TITLE
Array items validation in 

### ISSUE THREAD

**Issue by Chez** [spec-first/connexion#576]
### Description
Failure when items of type array in swagger file are set to string

In the file connexion/decorators/validators.py

The type string is missing:

TYPE_MAP = {
    'integer': int,
    'number': float,
    'boolean': boolean
}

adding it as such gets over the errors

TYPE_MAP = {
    'string': str,
    'integer': int,
    'number': float,
    'boolean': boolean
}

### Expected behaviour

For the swagger definition to pas

### Actual behaviour

Failure with typeerror

### Steps to reproduce

add array type with items defined as string

### Additional info:

Output of the commands:

- `python --version` 3.6.4
- `pip show connexion | grep "^Version\:"` connexion 1.3

**Comment by hjacobs** [comment]
Can you provide an example Swagger file, code and the reported error?

**Comment by Chez** [comment]
this is the offending path: The links parameter if you change the items to int it works

/phish_finder_multi:
    get:
      operationId: api.handlers_multi.get
      parameters:
        - name: affiliate
          in: query
          description: Valid Affiliate Code
          type: string
          minimum: 5
          maximum: 5
          format: query
          required: true
        **- name: links
          in: query
          type: array
          items:
            type: string
          format: query
          required: true**
      responses:
        '200':
          description: 'Test a list of URL Links'
          schema:
            $ref: '#/definitions/PhishMatch'

**Comment by Chez** [comment]
Is this a bug or a feature or am I doing something wrong?

**Comment by Chez** [comment]
Is this a bug or a feature or am I doing something wrong?

**Comment by hjacobs** [comment]
@Chez would you be willing to do a PR including a test to reproduce the problem?

**Comment by Chez** [comment]
Isn't all that is needed there. I'm pretty busy with work and don't get much time off as it is. The issue and the fix have been described.
