### ISSUE TITLE
Incorrect validation of required body parameters.

### ISSUE THREAD

**Issue by eugene-babichenko** [spec-first/connexion#579]
### Description

Here is the OpenAPI specification which causes problems:

```yaml
swagger: '2.0'

consumes:
  - application/json
produces:
  - application/json

paths:
  /token:
    post:
      summary: Send tokens from the current user to another user
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            properties:
              value:
                type: integer
            required:
              - value
      responses:
        200:
          description: Success
```

__main__.py:
```python
from pkg_resources import resource_filename
import connexion
from connexion.resolver import RestyResolver

if __name__ == '__main__':
    app = connexion.App(__name__, specification_dir='.')
    app.add_api(resource_filename(__name__, 'openapi.yml'), resolver=RestyResolver('rest_api_bug'))
    app.run(port=8080, host='0.0.0.0')
```

endpoint.py:
```python
from connexion import NoContent


def post(payload):
    print(payload)
    return NoContent, 200
```
### Expected behaviour

When there is no body in a POST request one should get a 400 error.

### Actual behaviour

`None` value is being passed to the request handler. On the other hands, it handles malformed JSON. For example, if one will pass just `{}` in the request body, a 400 error will be thrown.

### Steps to reproduce

1. Start the API server.
2. Send POST request with no body: `curl -X POST http://localhost:8080/endpoint`
3. No error is thrown, `payload` in `post` is `None`.

### Additional info:

- Python 3.6.5
- Connexion 1.4

**Comment by dtkav** [comment]
This seems to be a problem/feature of jsonschema.
`null` validates with the following schema just fine, whereas `{}` does not:
```
{
  "properties": {
    "value": {
      "type": "integer"
    }
  },
  "required": [
    "value"
  ]
}
```
you can try it out on https://www.jsonschemavalidator.net/

**Comment by cziebuhr** [comment]
It's because you also have to specify `type: object`. Otherwise `properties` will just be ignored if the body is not an object.

**Comment by tomghyselinck** [comment]
See also [#1666](https://github.com/OpenAPITools/openapi-generator/issues/1666) on [openapi-generator](https://github.com/OpenAPITools/openapi-generator)
