### ISSUE TITLE
Response validator fails to determine mimetype when several are provided in spec.

### ISSUE THREAD

**Issue by positron96** [spec-first/connexion#593]
### Description

I have an endpoint that produces either `application/json` or `text/csv`, depending on Accept header. 

This is reflected in swagger file as 
```
/endpoint:
    get:
      summary: get all calibrations from server
      operationId: endpoint
      produces:
        - application/json
        - text/csv
      responses:
        '200':
          description: 'OK'
          schema:
            type: array
            items:
              $ref: '#/definitions/CalibrationData'  ## this in an array of records of 3 floats
          examples:
            text/csv: |-
                  1, 0.12, -12
                  2, 1, 2
            aplication/json:
              Series: 1
              a: 0.12
              b: -12
      parameters: []
```

I have turned on response validation with ```app.add_api('api.yaml', validate_responses=True)```

### Expected behaviour

A correct response to a request with `Accept: text/csv` header should be sent to browser. The ResponseValidator should pass text/csv as is.

### Actual behaviour

Validator produces this error:

```
ERROR:connexion.decorators.validation:http://localhost:8080/api/endpoint validation error: '123,0.345000,1.234000\n4,0.345000,1.234000' is not of type 'array'

Failed validating 'type' in schema: 
...
On instance:
    '123,0.345000,1.234000\n4,0.345000,1.234000'

```

Seems that validator does not favour additional mimetypes when they are present.

### Additional info:

Output of the commands:

- `python --version`

Python 3.5.2

- `pip show connexion | grep "^Version\:"`

Version: 1.4.2

**Comment by positron96** [comment]
It seems to me that there are several causes of this problem:
 * ResponseValidator stores only one mimetype from spec and does not check actual response mimetype
 * Operation.get_mimetype returns only 1 mimetype from `produces` list. If there are several entries, they are discarded and json is returned (https://github.com/zalando/connexion/blob/master/connexion/operation.py#L333)

**Comment by RobbeSneyders** [comment]
Fixed in https://github.com/spec-first/connexion/issues/590
