### ISSUE TITLE
How do I access Flask current_app?

### ISSUE THREAD

**Issue by zimmicz** [spec-first/connexion#626]
```
server.py

#!/usr/bin/env python3

from connexion.resolver import RestyResolver
import connexion

def create_app():
    app = connexion.FlaskApp(__name__, specification_dir='swagger/')
    app.add_api('mapmybook.yaml',validate_responses=True, strict_validation=True, resolver=RestyResolver('api'))

    return app

if __name__ == '__main__':
    create_app().run(port=9090)
```

```
api/routes.py

from flask import current_app
def get() -> list:
    print(current_app)
    return items
```
results in `RuntimeError: Working outside of application context.`
I'm using Flask 1.0 with connexion 1.4.2, creating the app as seen above. Is there a way to access Flask's `current_app` from other modules?
I keep getting `RuntimeError: Working outside of application context.` when calling current_app in API modules.

**Comment by zimmicz** [comment]
Got it, app context is only available under certain conditions.

**Comment by BobDG** [comment]
@zimmicz I still get these errors. Can you let me know how you solved your issue? I've tried so many things but I always get this error...

**Comment by rolawson-ora** [comment]
Same issue here...

**Comment by randyesq** [comment]
Can we re-open this?

**Comment by jtlz2** [comment]
Any update on this? :\

**Comment by olof-kohlhaas** [comment]
I found a way: [https://stackoverflow.com/questions/53941243/how-to-pass-a-variable-into-connexion-flask-app-context](https://stackoverflow.com/questions/53941243/how-to-pass-a-variable-into-connexion-flask-app-context)

**Comment by vladislavkoz** [comment]
What about connexion 3.0.0+ 
How we can access context?
