### ISSUE TITLE
Plugin Mechanism

### ISSUE THREAD

**Issue by sharbov** [spec-first/connexion#719]
### Description

I would like to propose a plugin mechanism to the request handling flow.
The idea is to enable the registration of functions / decorators on predefined hooks,
to later be triggered at certain points of the request life-cycle.
I would also like o be able to set the order of these plugins execution.

Some examples of possible plugins:

* Logging 
* Authentication
* Metric collection
 
The plugins could be initialized at the app definition.
The implementation could be very similar to the current custom validators, but free of the current assumptions (the validators are only triggered when needed, and not on every incoming request).

**Comment by dtkav** [comment]
FWIW you can override the `def function` method on the Operation class. That method is where all of the decorators are applied, and in which order.

If you like, you can create a pull request with the plugin API you have in mind. I'm happy to provide feedback / review.

**Comment by RobbeSneyders** [comment]
You can add custom middlewares starting from version 3.0: https://github.com/spec-first/connexion/issues/1395
