### ISSUE TITLE
Does connexion support async in tornado?

### ISSUE THREAD

**Issue by braco** [spec-first/connexion#754]
Your docs say yes:
> For asynchronous applications, you can also use Tornado as the HTTP server. To do this, set your server to tornado:

but then it looks like the regular WSGI server is used:
https://github.com/zalando/connexion/blob/1fbb1ff941dee089dcf881ef46bcb079ac52502a/connexion/apps/flask_app.py#L102

and Tornado says this kills async:
http://www.tornadoweb.org/en/stable/wsgi.html
> In WSGI mode asynchronous methods are not supported. This means that it is not possible to use AsyncHTTPClient, or the tornado.auth or tornado.websocket modules.

**Comment by roman-telepathy-ai** [comment]
for me that is the reason to move away from connexion and maybe start a similar project for tornado.

**Comment by ptytb** [comment]
Same synchronous WSGI-compliance there for gevent:

https://github.com/zalando/connexion/blob/890fe9a17181a7bbb08638cdc476a339a711e10f/connexion/apps/flask_app.py#L111

while app for aiohttp looks async, see [aiohttp.web.run_app](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.run_app)

https://github.com/zalando/connexion/blob/890fe9a17181a7bbb08638cdc476a339a711e10f/connexion/apps/aiohttp_app.py#L93

Also it's not clear why *swagger_ui* mode is optional but Flask is still a hard dependency and some(?) async frameworks are forced to run in synchronous WSGI-compliant mode. Any elucidation on this matter will be very appreciated.
