### ISSUE TITLE
Serve Swagger Spec in YAML format

### ISSUE THREAD

**Issue by chiefnoah** [spec-first/connexion#769]
### Description
Currently a JSON representation of the Swagger/OpenAPI spec can be found at /swagger.json. It would be helpful if the YAML format was also available by changing the extension (ie. /swagger.yaml).

### Expected behaviour
The configured swagger spec is returned in YAML format from the /swagger.yaml endpoint.

### Actual behaviour
HTTP/1.0 404 NOT FOUND
Content-Type: application/problem+json

{"type": "error", "code": "objectNotFound", "message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."}

**Comment by dtkav** [comment]
I've put up a demo of this behavior, can you take a look @chiefnoah ?
Anyone else have thoughts/feedback on this idea?

My basic assumption was that the yaml should be accessible whenever the json spec is accessible, so I did not add any additional flags to enable/disable it separately.

Also, since the user can override the spec path, the yaml is available at the same path as the json, just with the yaml extension.

**Comment by chiefnoah** [comment]
@dtkav looks good to me. I agree, it serves the exact same purpose as the swagger.json, so I don't see a reason for it to be configured independent of it.  It looks good to me and behaves as expected, thanks! 😄

**Comment by dtkav** [comment]
Another way to do this would be to just store your spec in a static files folder
You can do this in flask (but I'd recommend doing it with nginx or similar).
```
@app.app.route('/static/<path:path>')
def send_static(path):
    return send_from_directory('static', path)
```
I think it's important to at least serve json, as most web clients aren't set up to parse yaml.

I'm not sure if serving yaml is generally desired, or if it's specific to your use case.
While I put up a demo of the implementation, I personally have a weak preference against this feature.

I'm looking for more input on this ticket for the best path to take...
@kornicameister mentioned that they'd prefer to not have this feature
@nmusatti you had a thumbs up on the ticket - any thoughts to add?
@jmcs any thoughts?

**Comment by ioggstream** [comment]
Given the popularity of `yaml` for writing specs, and considering that the patch is trivial, I'm for adding.

Consider that even in this repos, we have almost all yaml files.
 
I provided a more isolated implementation is in #842 .
