### ISSUE TITLE
Exception responses are not validated

### ISSUE THREAD

**Issue by dirkschneemann** [spec-first/connexion#797]
### Description
When activating `validate_responses=True` on initialization of the app in `app.add_api()`, responses that are generated from raising an exception are not validated against their according models in the specification file.

### Expected behaviour
When the implementation raises an error which generates a response that does not match the model then the response validation should fail, returning the according `HTTP 500` error.

### Actual behaviour
Response validation does not fail even though the response implementation does not match the according model. The response is returned as implemented.

### Steps to reproduce
`specification.yml`
```
openapi: 3.0.2
info:
  title: Some API
  version: Some version
paths:
  /:
    get:
      operationId: main.magic
      responses:
        422:
          description: Unprocessible Entity
          content:
            application/problem+json:
              schema:
                description: Some description
                properties:
                  detail:
                    enum:
                      - The only allowed detail text
                    type: string
                  status:
                    enum:
                      - 422
                    type: number
                  title:
                    enum:
                      - Unprocessable Entity
                    type: string
                  type:
                    enum:
                      - about:blank
                    type: string
                required:
                  - detail
                  - status
                  - title
                  - type
```

`main.py`:

```
import connexion

def magic():
    raise werkzeug.exceptions.UnprocessableEntity(
        description='Some text which does not match the specification and'
                    ' hence should make the validation fail but does not'
    )

connexion_app = connexion.FlaskApp(__name__, specification_dir='.')
connexion_app.add_api('specification.yml', validate_responses=True)
connexion_app.run(port=8000)
```

Trying out:
```
curl -XGET localhost:8000/
{
  "detail": "Some text which does not match the specification and hence should make the validation fail but does not",
  "status": 422,
  "title": "Unprocessable Entity",
  "type": "about:blank"
}
```

Work-around by directly returning the according response object instead of raising an exception:
```
def magic():
    return dict(
            status=422,
            detail='Some text which does not match the specification and'
                    ' hence should make the validation fail but does not',
            title='Unprocessable Entity',
            type='about:blank'
    ), 422
```

Trying out:
```
curl -XGET localhost:8000/
{
  "detail": "'Some text which does not match the specification and hence should make the validation fail but does not' is not one of ['The only allowed detail text']\n\nFailed validating 'enum' in schema['properties']['detail']:\n    {'enum': ['The only allowed detail text'], 'type': 'string'}\n\nOn instance['detail']:\n    ('Some text which does not match the specification and hence should '\n     'make the validation fail but does not')",
  "status": 500,
  "title": "Response body does not conform to specification",
  "type": "about:blank"
}
```

However, this takes away the possibility to end a request deep down in the function stack by raising an exception on some condition. Instead, the result of this condition must be bubbled up all the way to the function specified in `operationId` which then has to return this response. This also impedes re-usability when this needs to be done for multiple `operationId` handlers.

### Additional info:

Output of the commands:

- `python --version`: 3.5.2
- `pip show connexion | grep "^Version\:"`: Version: 2.0.0

**Comment by dtkav** [comment]
Hi @dirkschneemann - thanks for the ticket.
Response validation is a bit of a mess at the moment for several reasons (for example it only really works with pure json apis).
AFAICT response validation happens too early, but I haven't been able to dig into where all the exception handling happens completely yet.

**Comment by RobbeSneyders** [comment]
Response validation happens before exception response generation, so this is unfortunately not possible. Marking as wontfix.
