### ISSUE TITLE
Can't use flask-socketIO with Connexion

### ISSUE THREAD

**Issue by M1CK431** [spec-first/connexion#832]
### Description
I have write my first Python app (which is also my first API) using Connexion and now I'm trying to use [Flask-socketIO](https://github.com/miguelgrinberg/Flask-SocketIO) to add real time.

Unfortunately and after days of documentation reading and implements try, I can't have access to the `socketIO` object created at app start because it seems that Connexion re-run my `server.py` each time a HTTP route is called and so a new `socketIO` object is created (which doesn't works).

I have open an [issue in Flask-SocketIO project](https://github.com/miguelgrinberg/Flask-SocketIO/issues/862) but for now it seems that the problem doesn't happens with a route implemented directly with Flask and that's why I open this issue.

### Expected behaviour
No re-run of my `server.py` file each time a HTTP route defined in my `swagger.yml` file is called and so no new `socketio` object created.

### Actual behaviour
Re-run of my `server.py` file each time a HTTP route defined in my `swagger.yml` file is called and so no new `socketio` object created.

### Steps to reproduce
There is additional details in the [issue in Flask-SocketIO project](https://github.com/miguelgrinberg/Flask-SocketIO/issues/862) but here is a quick summary.

Project structure:
```
src/
  |_ server.py
  |_ swagger.yml
  |_ modules/
            |_ version.py
```

`server.py` file:
```python
import connexion
from flask_socketio import SocketIO

app = connexion.App(__name__, specification_dir='./')
app.add_api('swagger.yml')

flask_app = app.app
socketio = SocketIO(flask_app, logger=True)
print('socketio in server:', socketio)

# test
@app.route("/event", methods=['GET'])
def event():
    socketio.emit('alive', {'alive': True})
    print('socketio in server (event route)', socketio)
    return ''


if __name__ == '__main__':
    socketio.run(
        flask_app,
        host=0.0.0.0,
        port=5000,
        debug=True
    )

```

`version.py` file:
```python
from __future__ import unicode_literals


def version():
    socketio_emit('version', {'api': '0.1'})
    return {'api': '0.1'}


def socketio_emit(name, message):
    from server import socketio
    print('socketio in version:', socketio)
    socketio.emit(name, message)

```

`swagger.yml` file:
```yaml
paths:
  /version:
    get:
      operationId: "modules.version.version"
      tags:
        - "Information"
      summary: "Version of API"
      description: "Get the version of this API"
      responses:
        200:
          description: "Successful read version operation"
          schema:
            type: "object"
            properties:
              api:
                type: "string"
```

Now I have try to call `/version` (define in my `swagger.yml`) then `/event` route (define directly in `server.py` using `@app.route`) and here is the output in the console of my API:
```bash
$ python src/server.py 
socketio in server: <flask_socketio.SocketIO object at 0x7f009bfe8b00>
 * Restarting with stat
socketio in server: <flask_socketio.SocketIO object at 0x7f05c4c93588>
 * Debugger is active!
 * Debugger PIN: 256-773-169
(12580) wsgi starting up on http://0.0.0.0:5000
(12580) accepted ('127.0.0.1', 37068)
socketio in server: <flask_socketio.SocketIO object at 0x7f05c382f080>
socketio in version: <flask_socketio.SocketIO object at 0x7f05c382f080>
emitting event "version" to all [/]
127.0.0.1 - - [26/Dec/2018 13:50:36] "GET /version HTTP/1.1" 200 157 0.066981
(12580) accepted ('127.0.0.1', 37092)
emitting event "alive" to all [/]
socketio in server (event route) <flask_socketio.SocketIO object at 0x7f05c4c93588>
alive
127.0.0.1 - - [26/Dec/2018 13:50:40] "GET /event HTTP/1.1" 200 115 0.001125
```

It seems that when I'm calling a route defined using `Connexion` my `server.py` is re-run (don't know why) and so a new `socketio` object is created. It's this object which is then imported in my `version` function.

But, the good (working) `socketio` object is the one created just after the line ` * Restarting with stat`:
```bash
 * Restarting with stat
socketio in server: <flask_socketio.SocketIO object at 0x7f05c4c93588>
```
because it's this one which is used in my `/event` test route and it works.

### Additional info:

Perhaps this issue is trivial and due to my poor knowledge in Python I don't know but I have really no idea on how to fix that.

Output of the commands:

- `python --version`:
```bash
$ python --version
Python 3.7.1
```
- `pip show connexion | grep "^Version\:"`:
```bash
$ pip show connexion | grep "^Version\:"
Version: 2.2.0
```

**Comment by dtkav** [comment]
hey @M1CK431 
try:
```
if __name__ == '__main__':
    app.run(
        host=0.0.0.0,
        port=5000,
        debug=True
    )
```
Here's what I get when I start the connexion app instead of using `socketio.run(...)`
```
curl localhost:5000/event
# emitting event "alive" to all [/]
# socketio in server (event route) <flask_socketio.SocketIO object at 0x7f4cf899f780>
# 127.0.0.1 - - [07/Jan/2019 22:30:00] "GET /event HTTP/1.1" 200 -
```
```
curl localhost:5000/version
{
  "api": "0.1"
}
# socketio in version: <flask_socketio.SocketIO object at 0x7f4cf7e32710>
# emitting event "version" to all [/]
# 127.0.0.1 - - [07/Jan/2019 22:30:20] "GET /version HTTP/1.1" 200 -
```

**Comment by ocordes** [comment]
Hi,

this is not a BUG but has something to do with the debugging server from Flask. As far as I remember there are two instances of the program running, which gives the flask server the possibility to restart parts of the server while editing. 

My trivial suggestion would be so save the socketio object inside the app.config part and checks for existence before creating a new one ... 

I want to check the SocketIO for my project but I keep your behaviour in mind...

**Comment by coltenkrauter** [comment]
Did you ever solve this?

**Comment by pcbt** [comment]
I have found a hacky solution:

First I write firstly created socket.io id to json file then read that id in the inner py file (in this case it is version,py) then dereference the object from id using _ctypes library:

```
def socketio_emit(name, message):
    import _ctypes, json

    with open('socket-io.json') as json_file:
        data = json.load(json_file)

    socketio = _ctypes.PyObj_FromPtr(int(data['id']))
    socketio.emit(name, message, namespace='/')
    print('socketio in version:', socketio)
```

**Comment by pcbt** [comment]
You have two instances in the beginning because when you import a module in python you basically run the file. That is why you have two different socket.io objects.

I came up with better solution,

first pass the socketio instance to app_context then use it in the version.py file

in server.py
```
    with app.app.app_context():
        current_app.config['socketio'] = socketio
```

in version.py
```
socketio = current_app.config['socketio']
```

that worked for me.
