### ISSUE TITLE
Oauth2 - uid verification in addition to scope verification

### ISSUE THREAD

**Issue by fpozzobon** [spec-first/connexion#859]
### Description

I would like to secure an entry point using oauth2 with : 
- Specific Scope returned by the token info
- Specific UID returned by the token info

### Expected behaviour

Ideally add in the openApi definition a filter on uid in addition to the scope.
Or having a function like x-scopeValidateFunc but taking in parameter the token-info.
Or store the token-info in the session.

### Actual behaviour

As far as I know, there is no way to add a filter on uid.

**Comment by fpozzobon** [comment]
As a workaround, I use x-tokenInfoFunc to have the extra logic there verifying if the uid is valid or not depending on the context path.

**Comment by dtkav** [comment]
Hey @fpozzobon - I'm not sure I totally understand your question.
Can you say more about why you think using `x-tokenInfoFunc` is a workaround?
AFAIK that's exactly the place to write your auth logic, but I might just be missing so important detail.
An example would help me if you have one.

**Comment by fpozzobon** [comment]
Hi @dtkav - to me it feels like x-tokenInfoFunc is about getting the informations from a token (ie not make sure that he is allowed to see the resource).
- Wouldn't it be nice to have a "x-uidValidateFunc' (same as x-scopeValidateFunc) but taking the uid from the token in parameter ?

Ideally, we could also have in securityDefinitions the option to define uids (a bit like we define scopes) : 
```uids:
  export: ['uid_app_1', 'uid_app_2']```
which then would be used in security section for each resource : 
```security:
  - oauth2uid: [export]```

**Comment by fpozzobon** [comment]
What I did to apply a uid whitelist : 
```
def token_info(access_token):
    if config.TOKENINFO_URL:
        token_info = security.get_tokeninfo_remote(config.TOKENINFO_URL, access_token)
        if token_info:
            if is_uid_authorized(token_info['uid']) is False:
                raise OAuthResponseProblem(
                    description='Provided token doesn\'t have the required uid',
                    token_response=None
                )
            return token_info
    return None
