### ISSUE TITLE
Pattern support in schema doesn't appear to conform to OpenAPI 3.0 specification

### ISSUE THREAD

**Issue by wittlesouth** [spec-first/connexion#871]
### Description

According to the [OpenAPI 3.0 specification for the pattern attribute](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object) of a schema object, the pattern provided should comply with [ECMA 262 regular expression syntax](https://www.ecma-international.org/ecma-262/5.1/#sec-7.8.5). The syntax defined in that specification defines regular expression literals as being preceded and trailed by a '/' character, as they are in Javascript/ECMAscript.

### Expected behaviour

Pattern specified in the schema as:

`pattern: /regular expression/`

apply the regular express contained within the '/' characters as a validation for the schema object.

### Actual behaviour

If preceding and following '/' are included, the regular expression validation fails.

### Steps to reproduce

Attempt to validate an e-mail address on a schema property with the following pattern provided in the yaml spec for the API:

`pattern: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/`

It will fail. Remove the preceding and trailing '/' characters from the above regex, and the email address will validate according to the regex.

### Additional info:

Output of the commands:

- `python --version`
3.7.1
- `pip show connexion | grep "^Version\:"`
Version: 2.2.0

See also Issue #269 which reported the problem that the regex didn't work with preceding and trailing '/' characters, but didn't refer to this as being in violation of the OpenAPI 3.0 specification.

**Comment by dtkav** [comment]
Hey @wittlesouth - 
We use https://github.com/p1c2u/openapi-spec-validator for validation.
That might be the best place to raise this issue.

**Comment by wittlesouth** [comment]
Perhaps I don't understand how you're using the openapi-spec-validator. My understanding was that all that project does is validate that the provided OpenAPI specification is valid, not that it is used to check the validity of JSON passed to a Connexion endpoint via a POST (for example). I'm assuming this because when I use an invalid specification, Connexion fails during startup.

It seems to me that there are two issues. First, patterns that are not valid ECMA 262 regular expressions should be flagged by the spec validator as invalid. Agree that this is not a Connexion issue and should be filed against the spec validator. Second, when data passed into an API is being checked to see if it conforms to the API specification, a valid ECMA 262 regular expression should work. This second problem I'm assuming belongs to Connexion, but perhaps I'm wrong.

Is the spec validator you reference validating the specification document *and* data included as a request body in POST requests to Connexion endpoints? Because the bigger issue from my perspective is that when I use what should be (and is according to the spec validator) a valid OpenAPI 3.0 specification, Connexion incorrectly flags the data POSTed to an endpoint as invalid.

If the spec validator was fixed and correctly marked pattern values without leading and trailing '/' characters as invalid specifications, then pattern validation would be completely broken. Because including the '/' would make the spec valid but connexion flag data matching the specification as invalid. Leaving out the '/' values (as I'm doing now) would make the spec invalid, causing Connexion to fail during initialization.

**Comment by wittlesouth** [comment]
Filed [issue number 57 in the openapi spec validator project](https://github.com/p1c2u/openapi-spec-validator/issues/57).

**Comment by dtkav** [comment]
There a couple layers that handle incoming request bodies.
First, request body validation only happens if you either (1) only accept JSON, or (2) only accept formdata (unfortunately).
The validator used in connexion is the Draft4Validator from https://github.com/Julian/jsonschema . 
If you can reproduce the bug with just the jsonschema validator, that would be the place to follow up.

(We also extend the validator with some additional functionality in this file: https://github.com/zalando/connexion/blob/master/connexion/json_schema.py )
