### ISSUE TITLE
Connexion doesn't execute the function specified in the operation id for request method OPTIONS

### ISSUE THREAD

**Issue by KBA07** [spec-first/connexion#873]
### Description
Connexion doesn't execute the function specified in the operation id for request method OPTIONS

### Expected behavior
It should execute the function specified in the operation id.

### Actual behaviour
It is not executing the function defined in the operation id.

### Steps to reproduce
Swagger File for API description

-- option_api.yml

swagger: '2.0'

info:
  title:  "Test API"
  description: "Just checking"
  version: "1.0"

basePath: "/v2"

paths:
  /option2:
    options:
      tags:
        - Opt
      summary: "Just Checking"
      operationId: "option.get_options"
      produces:
      - "text/html"
      responses:
        200:
          description: "Testing"
    get:
      tags:
        - Opt
      summary: "Just Checking"
      operationId: "option.get_request"
      produces:
      - "text/html"
      responses:
        200:
          description: "Testing"

-- option.py

from flask import Blueprint, Response, Flask, request

def get_options():
    resp = Response()
    resp.headers = {
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Allow-Methods': 'GET, POST',
        'Access-Control-Max-Age': '3400',
        'Access-Control-Allow-Origin': '*'
    }
    return resp

def get_request():
    resp = Response()
    resp.status = 'OK'
    resp.status_code = 200
    resp.headers = {
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Allow-Methods': 'GET, POST',
        'Access-Control-Max-Age': '3400',
        'Access-Control-Allow-Origin': '*'
    }
    return resp

-- app.py

from connexion import App

conn_app = App(__name__)
conn_app.add_api('option_api.yml')

if __name__ == '__main__':
    conn_app.run(debug=True)

### Additional info:
I have declared two API method  GET and OPTIONS and specified the operation id for both.
when I hit GET API 
I get headers as expected 
Access-Control-Allow-Origin →*
Access-Control-Allow-Methods →GET, POST
Access-Control-Max-Age →3400
Access-Control-Allow-Credentials →true
Content-Length →0
Server →Werkzeug/0.14.1 Python/2.7.15
Date →Sat, 09 Feb 2019 10:03:34 GMT

But when I hit OPTIONS API the headers I get is 

Content-Type →text/html; charset=utf-8
Allow →HEAD, OPTIONS, GET
Content-Length →0
Server →Werkzeug/0.14.1 Python/2.7.15
Date →Sat, 09 Feb 2019 10:04:19 GMT

Even though I am returning custom headers in the function specified in the operation id. Also if I raise a manual exception inside the operation id I get status as 200 and the headers specified above.

- `python --2.7`
- `connexion versions (1.0.109, 2.0.0)

**Comment by prabhu** [comment]
Are you not able to workaround this defect by handling OPTIONS at the web or wsgi server level?

**Comment by KBA07** [comment]
I can register one after request function on WSGI server level which handles OPTIONS request based on my custom logic for API rule, origins etc to set the required headers.

Since registering GET, POST, PUT, DELETE APIs using a swagger file in connexions allows you to specify a method for each request type.

Connexion should allow registration of a custom method for request type OPTIONS. So someone can set headers based on API level directly instead of setting on a server level.

**Comment by RobbeSneyders** [comment]
Cannot reproduce
