### ISSUE TITLE
Header missing token 

### ISSUE THREAD

**Issue by ctippur** [spec-first/connexion#890]
### Description
I am using a older version of connexion (1.1.9) and am in the process of migrating to 2.x. I am working on a flask based application using AWS Lambda. 

### Expected behaviour
I see that the header where I pass the token seem to be missing - only sometimes. Given the fact that I am working on a older version, can someone please shed some light on the reason I could be seeing this behavior.

### Actual behaviour
Header has a valid token passed by the client.

### Steps to reproduce
It is hard to reproduce. I cant seem to reproduce in my local environment. I see this behavior on AWS. I see a failure rate to be around 70%

### Additional info:

```
app = connexion.App(__name__, specification_dir='./swagger/')
app.app.json_encoder = JSONEncoder
app.add_api('swagger.yaml', arguments={'title': 'My app'})

if __name__ == '__main__':
    app.run()
```

Output of the commands:

- `python --version`
3.6.4
- `pip show connexion | grep "^Version\:"`
1.1.9

**Comment by dtkav** [comment]
Hey @ctippur , I can't reproduce the issue with the information you have
provided. Can you include a spec that has the problem?

Also helpful would be information about your environment (is your path
altered by a reverse proxy, etc).

The auth subsystem was completely rewritten for Connexion 2.0.
