### ISSUE TITLE
Response validation with streaming

### ISSUE THREAD

**Issue by Glutexo** [spec-first/connexion#904]
### Description

When response validation is turned on, it’s not possible to use Flask streaming. The response is buffered by Connexion and flushed after being validated. That’s not necessarily incorrect, but requires to entirely disable response validation.

### Expected behaviour

It’d be great to have some way to have response validation turned on yet still be able to use Flask streaming. Even disabling the validation for specific operation would be sufficient.

### Actual behaviour

Now it’s only possible to disable response validation for the whole API.

### Steps to reproduce

Add the API with response validation turned on.

```python
    connexion_app.add_api("api_spec.yaml", validate_responses=True)
```

Define a streaming operation

```yaml
/stream
  get:
    operationId: api.stream
    summary: Streaming operation
    description: A stream of Newline Delimited JSON objects.
    responses:
      '200':
        description: Successfully streamed some JSONs.
        content:
          application/x-ndjson: {}
```

```python
from flask import Response
from flask.json import dumps


def stream():
    def generate():
        for i in range(10):
            item = dumps({"i": i})
            yield(item)
    return Response(generate(), mimetype="application/x-ndjson")
```

### Additional info:

Output of the commands:

- `python --version`
   `Python 3.6.7`
- `pip show connexion | grep "^Version\:"`
   `Version: 2.2.0`

**Comment by RobbeSneyders** [comment]
Hi @Glutexo, thx for the PR. Hopefully you're still interested in merging this :)

In the perfect case, we might want to try to validate the response in a streaming fashion, but this already looks like an improvement. I see two downside as well though:
- Response headers are also not validated anymore 
- Users might not expect that validation is deactivated on streaming responses

I think we can address this by logging a warning about this when we skip validation.

Also, we moved to the main branch, so can you please rebase and change the target of your PR?

**Comment by NielsRogge** [comment]
I'm having the same issue, except that I use `from starlette.responses import StreamingResponse` instead of `from flask import Response`. The app itself is a Connexion `AsyncApp`.

It seems validation is still happening even though the response gets streamed. Is there a way to disable this just for the endpoint whose return type is "application/x-ndjson"?

**Comment by NielsRogge** [comment]
Update, resolved it with a custom validator: https://connexion.readthedocs.io/en/stable/validation.html#custom-validators.

```python
from connexion.datastructures import MediaTypeDict
from connexion.validators import AbstractResponseBodyValidator, JSONResponseBodyValidator, TextResponseBodyValidator


class NDJSONResponseValidator(AbstractResponseBodyValidator):

    def _parse(self, stream: t.Generator[bytes, None, None]) -> t.Any:
        pass

    def _validate(self, body: dict):
        pass


validator_map = {
    "response": MediaTypeDict(
        {
            "*/*json": JSONResponseBodyValidator,
            "*/*ndjson": NDJSONResponseValidator,
            "text/plain": TextResponseBodyValidator,
        }
    ),
}
```
