### ISSUE TITLE
Unable to register callback function with Flask blueprint

### ISSUE THREAD

**Issue by jonathonadler** [spec-first/connexion#906]
### Description

A before_request callback function must to bound to a blueprint before registering the blueprint with Flask. The FlaskApp.add_api method currently creates and registers the blueprint in one action, meaning to is not possible to assign a before_request callback function before registration.

see: https://stackoverflow.com/questions/42093205/flask-doesnt-call-blueprints-before-request-function

### Actual behaviour

1. FlaskApp.add_api method creates the api blueprint and registers it with Flask.

```
    def add_api(self, specification, **kwargs):
        api = super(FlaskApp, self).add_api(specification, **kwargs)
   
        # No opportunity to apply a callback - could the api be refactored to allow this?
        @api.blueprint.before_request
        def handle_before_request():
           pass

        self.app.register_blueprint(api.blueprint)
        return api
```
### Additional info:

Output of the commands:

- `python --version`
Python 3.5.3
- `pip show connexion | grep "^Version\:"`
Version: 2.2.0

**Comment by dtkav** [comment]
Hey @jonathonadler - Thanks for the ticket.
I don't fully understand the implications here, or what you are trying to do.
Is there any way you can provide some more context?
Have you considered inheriting from FlaskApp and overriding the `add_api` function?

**Comment by jonathonadler** [comment]
Thanks @dtkav. I was just looking to split the add_api method into create blueprint and register blueprint methods. This is because you callbacks for a blueprint need to be registered (for example, using a decorator like @api.blueprint.before_request) before  the blueprint itself is registered.

I ended up solving this like below (thanks for the hint to inherit - really not sure what I was thinking):
 
```python
class ConnexionApp(FlaskApp):
    def create_api(self, specification, **kwargs):
        api = super(FlaskApp, self).add_api(specification, **kwargs)
        return api

    def register_api(self, api):
        self.app.register_blueprint(api.blueprint)
```

I can now solve my problem this this:

```python
  connexion_app = ConnexionApp(__name__)
  api = connexion_app.create_api('openapi.yaml')
  
  @api.blueprint.before_request
  def append_globals():
    # ensure that global variables are present within context of blueprint
    logger.debug('appending global variables to context')
    pass

  connexion_app.register_api(api)
```

Feel free to close the ticket, or consider adding these methods if you think they are useful for others.
