### ISSUE TITLE
Get requests with same parameters blocking, otherwise async on Aiohttp via swagger-ui

### ISSUE THREAD

**Issue by davidkraljic** [spec-first/connexion#918]
### Description
Using Aiohttp backend. Have a simple Get request handler containing an asyncio.sleep(10) and a return. The majority of the code generated by swagger codegen, just with flask replaced by aiohttp.

### Expected behaviour
The requests are processes asynchronously no matter what the parameters are.

### Actual behaviour
Requests are processed asynchronously if request parameters are different. However, if I perform multiple Get requests with the same parameters - they are processed in series.

Writing the same handler within only Aiohttp works as expected.

### Steps to reproduce
As described above.

### Additional info:

Output of the commands:
Python 3.6.7
Version: 2018.0.dev1

**Comment by davidkraljic** [comment]
This appears to be the issue only when using the swagger UI

**Comment by christiansiegel** [comment]
I can reproduce this issue with an async version of the `openapi/helloworld` example:
```python
import connexion
import asyncio
from aiohttp import web

async def post_greeting(name: str) -> web.Response:
    print("start")
    await asyncio.sleep(5)
    print("end")
    return web.Response(text='Hello {name}'.format(name=name))

if __name__ == '__main__':
    app = connexion.AioHttpApp(__name__, port=9090, specification_dir='openapi/')
    app.add_api('helloworld-api.yaml', arguments={'title': 'Hello World Example'})
    app.run()
```
Interestingly, only GET requests with the same URL are blocking. For POST requests everything seems to work just as expected.
