### ISSUE TITLE
Route terminated at / is different than route completed empty

### ISSUE THREAD

**Issue by henriqueweiand** [spec-first/connexion#919]
![Kapture 2019-04-09 at 14 09 56](https://user-images.githubusercontent.com/6539492/55820615-e64d4880-5ad1-11e9-8b1c-474b480ffe8a.gif)

### Description

When configuring the routes I noticed that there is a distinction between "/" and without, for example: site.com and site.com/

### Expected behaviour

Both routes should fall into the example site.com/

### Actual behaviour

Redirects as gif

### Additional info:

Output of the commands:

- Python 3.7.3
- Version: 2.2.0

**Comment by dtkav** [comment]
This is expected behavior.

**Comment by dtkav** [comment]
I may have spoken too soon (sorry was on mobile).
What looks very surprising to me is that your POST request is becoming a GET request.
This is not expected! It looks like your client is treating the 308 as though it were a 301.

Perhaps this is a bug in postman. Are you able to reproduce with curl or python-requests?
