### ISSUE TITLE
How to protect swagger UI endpoint?

### ISSUE THREAD

**Issue by jo-me** [spec-first/connexion#922]
### Description

The swagger UI endpoint , e.g. /api/ui  is generally unprotected.
How can I enforce basic auth on that endpoint?

### Expected behaviour

Endpoint is protected

### Actual behaviour

Endpoint is accessible to all

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by rafaelcaricio** [comment]
Hi @jo-me ,

The best way to do this is through NGINX of some other reverse proxy you might be using on top of your Connexion application. I would say that this feature is out of scope of what Connexion purposes to solve. Maybe other maintainers have different opinion. I will be happy to discuss.

**Comment by RobbeSneyders** [comment]
Duplicate of #501
