### ISSUE TITLE
Question: How do you use url_for to get a route specified in your yaml file?

### ISSUE THREAD

**Issue by hello-josh** [spec-first/connexion#924]
Question is in the subject. 

I've tried using operationId to no avail. Given the following snippet, how would I use `url_for` to fetch a URL?

```yaml
---
swagger: "2.0"
info:
  description: Example for Issue Reporting
  version: "1.0.0"
  title: Example API
basePath: /v1.0
paths:
  /hello/{name}:
    get:
      summary: "Says Hello, $name"
      operationId: controllers.example.say_hello_name
```

Looking at the code, it seems that the Api is created as a Blueprint using `basePath` as the blueprint name. I've tried using the `<blueprint name>.<route name>` convention and it didn't work. 

Examples tried:
`v1_0.controllers.example.say_hello_name`
`v1_0.controllers_example_say_hello_name`

The error I get back is:
```
werkzeug.routing.BuildError: Could not build url for endpoint 'v1_0.controllers_example_say_hello_name' with values ['name']. Did you mean '/v1_0.controllers_example_say_hello_name' instead?
```

It seems to work with the leading `/`, but why does it add a slash to the start overriding the normal way `url_for` works with Blueprints? http://flask.pocoo.org/docs/0.12/blueprints/#building-urls

**Comment by pilayar76** [comment]
@hello-josh I am also hitting the same issue. Did you find any solutions so far?

**Comment by srtab** [comment]
@hello-josh you're missing the initial slash, this will work: `url_for("/v1_0.controllers_example_say_hello_name")`.

**Comment by hello-josh** [comment]
> @hello-josh you're missing the initial slash, this will work: `url_for("/v1_0.controllers_example_say_hello_name")`.
> 
> To inspect urls, just print `app.url_map` variable ;)

I don't have this code around any longer to verify, but I believe as stated that when I used a leading slash, that the URL was returned with two leading slashes. `//v1...`
