### ISSUE TITLE
flask url_for equivalent in connexion

### ISSUE THREAD

**Issue by umaparvat** [spec-first/connexion#926]
### Description
Celery async job id has to be returned in the post api endpoint header "Location" value. When i've given the path of the operation id in the url_for of flask it shows it's not valid endpoint and displays whether did i mean /files/v0/xfiles_apis_controllers_files.get_jobId 

### Expected behaviour
filename: xfiles/apis/controllers/files.py
from flaks import url_for, jsonify
def create_filesystem(data):
    print(data)
    ins = FileSystemService()
    tasks = ins.createFS.apply_async()
    return jsonify({'fileSystemId':"123", 'status': tasks.state, 'completionStatus': 66}), 201, \
           {'Location': url_for('xfiles.apis.Files.controllers.jobs.get_jobId', id=tasks.id, _external=True)}

swagger.yaml

/filesystem:
    post:
      consumes:
          - application/json
      summary: Create a file system
      responses:
        401:
          description: Authentication failed
        403:
          description: Not authorized
        500:
          description: Unexpected error
        201:
          description: "Success"
          schema:
            $ref: '#/definitions/createFileSystemResponse'
      summary: "Create a File System"
      description: "Async API to create a file system, status can be verified using task_id in response"
      operationId: "xfiles.apis.Files.controllers.files.create_filesystem"
      parameters:
        - in: body
          name: data
          required: true
          schema:
            $ref: '#/definitions/fileSystemInputRequest'
      tags:
        - "Files"

  /jobs/{id}:
    get:
      consumes:
          - application/x-www-form-urlencoded
      responses:
        401:
          description: Authentication failed
        403:
          description: Not authorized
        500:
          description: Unexpected error
        200:
          description: "The details of the job"
          schema:
            $ref: '#/definitions/jobResponse'
      description: "Job status of the given Id"
      operationId: "xfiles.apis.Files.controllers.jobs.get_jobId"
      parameters:
        - in: path
          name: id
          description: Id of the job to be checked
          required: true
          type: string
      tags:
        - "Jobs"

### Actual behaviour
 In Response
 {'Error': xfiles.apis.controllers.files.get_jobId is not found did you mean /files/v0/xfiles_apis_controllers_files.get_jobId ?

### Additional info:

Output of the commands:

- `python --version` == 3.6
- `pip show connexion | grep "^Version\:"`

python version 3.6
connexion 1.5.3

**Comment by Ishrock** [comment]
The endpoint should not be a string.  It should but the actual function that is used as the endpoint.
