### ISSUE TITLE
Generation of implementation stubs for "operationId"-specified functions

### ISSUE THREAD

**Issue by neubig** [spec-first/connexion#928]
### Description

I'm just starting out with connexion, so please forgive me if this is a naive question, but is there any way to generate server-side implementation stubs for functions defined using "operationId" in the yaml OpenAPI spec?

### Expected behaviour

Ideally, if there is a function specified by operationId, it would be possible to generate a function definition including:
* the correct input arguments
* return values/logic
* docstrings

### Actual behaviour

As far as I can tell this is not implemented.

I see there is "mocking" behavior implemented (https://github.com/zalando/connexion/blob/master/connexion/mock.py), but this doesn't seem to be what I want.

**Comment by hubertgrzeskowiak** [comment]
There is https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#python-flask-connexion but the code is very clumsy and not extendible.

I think a better way would be having an abstract base class with some static abstract functions. This class can then be inherited in a separate file and the IDE would tell you which methods you need to implement. A good IDE will also generate a stub from that for you.
