### ISSUE TITLE
Use jsonschema for validation

### ISSUE THREAD

**Issue by patrickkwang** [spec-first/connexion#930]
A JSON version of the OpenAPI 3.0 specification is now available:
https://github.com/OAI/OpenAPI-Specification/commit/6d17b631fff35186c495b9e7d340222e19d60a71
One can validate against this using jsonschema instead of using openapi_spec_validator, here:
https://github.com/zalando/connexion/blob/master/connexion/spec.py#L227
In my experience, both work but jsonschema produces more useful error messages.

**Comment by rafaelcaricio** [comment]
Hi @patrickkwang,

This seems like an interesting idea since we would possibly be able to remove one dependency. Would you be interested in baking a PR with this change?
