### ISSUE TITLE
Add a SnakeCaseResolver

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [spec-first/connexion#939]
### Description
Swagger is usually using camelCase for describing operations. This doesn't map well to popular Python style guides where functions are supposed to be snake_case.

Here's my hacky way to do it, but I'd be happier if Connexion had a built-in way to achieve this:
```
class SnakeCaseResolver(resolver.Resolver):
  """Resolver that translates Swagger camelCase operations to Pythonic snake_case."""
  def resolve_operation_id(self, operation) -> str:
    op = super(SnakeCaseResolver, self).resolve_operation_id(operation)
    module, function = op.rsplit(".", 1)
    return f"{module}.{stringcase.snakecase(function)}"
```

```
app.add_api(pathlib.Path("swagger.yaml"), resolver=SnakeCaseResolver)
```

**Comment by christiansiegel** [comment]
Hi @hubertgrzeskowiak,

There is already an option to achieve this:
```python
app.add_api('api.yaml', ..., pythonic_params=True)
```

Unfortunately it is not documented yet. There is a pending pull request though: #947

**Comment by hubertgrzeskowiak** [comment]
@christiansiegel isn't the `pythonic_params` option just transforming parameters? This issue is about resolving Swagger Operation IDs to Python functions.

**Comment by christiansiegel** [comment]
> @christiansiegel isn't the `pythonic_params` option just transforming parameters? This issue is about resolving Swagger Operation IDs to Python functions.

True. Sorry, my mistake.

**Comment by RobbeSneyders** [comment]
I don't think this is hacky. It's exactly why the resolver is pluggable.
