### ISSUE TITLE
Adding a custom route that is not defined via the openapi spec

### ISSUE THREAD

**Issue by maitham** [spec-first/connexion#940]
### Description
Is it possible to add a custom route not defined via the api spec (swagger.yml) under the same base url. Currently I have my base url as <service_name>/v1/ . I want to add a websocket handler at <service_name>/v1/stream. Currently this does not work and I get a 404. It seems like all routes under <service_name>/v1/ are saved for handlers defined in the swagger.yml file. Is it possible to add a custom route?

**Comment by badcure** [comment]
I would personally lean against this, or at least define the custom URLs outside of the domain of the OpenAPI. Meaning, something like the following would be sufficient instead:
* <service_name>/stream - Custom route
* <service_name>/v1 - Root for all OpenAPI routes. 

Is there a reason that endpoint can't be added to the schema? IMHO adding the ability to customize functionality outside of the OpenAPI schema can get messy long term.

**Comment by RobbeSneyders** [comment]
You can do this via `.add_url_rule()` or `.route()` on the Connexion app.
