### ISSUE TITLE
Debugging in vscode does not work with connexion

### ISSUE THREAD

**Issue by davidnazw** [spec-first/connexion#956]
Following the instructions in (https://code.visualstudio.com/docs/python/tutorial-flask) to run the code in vscode debugger throws the error:
Error: Failed to find Flask application or factory in module "app". Use "FLASK_APP=app:name to specify one.

The reason in that the app is created by:
app = connexion.FlaskApp(__name__)
instead of:
app = Flask(__name__)

So the FLASK_APP could not be recognized.

Is there a workaround for this to enable debugging in vscode?

**Comment by dmenne** [comment]
Same problem for me. Any idea?

**Comment by a-e-benson** [comment]
Can you post the your launch.json file? I suspect your FLASK_APP starts with "{workspaceFolder}...".

NOTE: I've been at this a while and still have not successfully been able to debug a Flask/Connexion app in VSCode, but I have made it past the error you posted.

**Comment by a-e-benson** [comment]
`{
            "name": "Python: Connexion",
            "type": "python",
            "request": "launch",
            "module": "connexion",
            "cwd": "${workspaceFolder}",
            "env": {
                ...
            },
            "args": [
                "run",
                "[SPEC_DIR]/[SPEC_FILE]",
                "--port",
                "[HTTP_PORT]"
            ]
        }`

**Comment by mdwheele** [comment]
That launch config works for me.

**Comment by tuxflo** [comment]
While the app starts with the config above it is not initialized correctly here. For example I'm unable to use a variable which is bound in the `__main__.py` file to the app context:
```
    with current_app.app_context():
       current_app.myvar
    ...
```
Here an error occurs `AttributeError: 'Flask' object has no attribute 'myvar'` which is not the case if I start the program using the commandline `python3 -m my_server`. Any ideas how to fix that?
