### ISSUE TITLE
Unable to add custom error handler for 4xx exceptions

### ISSUE THREAD

**Issue by phillipmadlan** [spec-first/connexion#960]
### Description
I have successfully override the RequestBodyValidator class to do some custom validation and logging. I now want to log and capture all 4xx errors that are not necessarily in the umbrella of RequestBodyValidator. I want to do this because certain 4xx errors we are receiving in production are not being logged to ourElasticSearch logging solution for diagnosing errors. Any sort of validation is logged correctly so we can understand if schema and payloads being sent are incorrect. Basically, there are a class of errors such as ""Request body is not valid JSON" that are not being logged in our ElasticSearch logging solution but are being captured by CloudWatch monitoring in AWS. We want to see the payloads that are causing this error and understand them more.

### Expected behaviour
I have set up this simple code block:

```
@event_api.app.errorhandler(500)
def internal_error(error):
    return error_utils.build_and_log_internal_error(traceback.format_exc())

@event_api.app.errorhandler(Exception)
def internal_error(error):
    return error_utils.build_and_log_internal_error(traceback.format_exc())

@event_api.app.errorhandler(400)
def four_hundred_error(error):
    return error_utils.build_and_log_400_error(error)
```

The `build_and_log_400_error()` function is simply defined as 
```
def build_and_log_400_error(error):
    print("I am in the important function")
    print(error)
    return "{}"
```
right now.

I thus expect when I send a payload that is invalid JSON i.e. missing commas between fields to print to my console the print statements above. I want to see the error statement and the "I am in the important function" in the console. Additionally, the payload I should receive for POSTing this invalid should just be two brackets.

### Actual behaviour
The error handler for the invalid JSON and other 4xx exceptions just doesn't work. I see no print statements in my console even though I've tested the print statements in my other error_handler. The JSON returned by the API is 
```
{
    "detail": "Request body is not valid JSON",
    "status": 400,
    "title": "Bad Request",
    "type": "about:blank"
}
```

### Steps to reproduce
I build my API/Docker container and then I run my Docker container and send payloads. I don't know if this is detailed enough...

### Additional info:
I am using uwsgi as my web server.

My start file is:
```
#!/bin/bash

service nginx start
uwsgi --ini uwsgi.ini
```
and my ini file is:
```
[uwsgi]
module = run_event_api:event_api
master = true

socket = /tmp/uwsgi.socket
chmod-sock = 664
vacuum = true

processes = 4
threads = 2
enable-threads = true

die-on-term = true

log-master = true
disable-logging = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true
```

Output of the commands:

- `python --version`
```
root@22cc081423c1:/# python --version
Python 3.7.3
```
- `pip show connexion | grep "^Version\:"`
```
root@22cc081423c1:/# pip show connexion | grep "^Version\:"
Version: 1.5.3
```

**Comment by phillipmadlan** [comment]
I'm really at my wits end. I've tried everything. I didn't think it'd be so difficult to add logging for all 4xx errors. I read so many issues and tried so many things over the last two days. I use Connexion with uwsgi. 500 errors work well and exceptions work fine but 4xx errors do nothing. What do you all do for this? Any idea why my custom error handler won't work?

**Comment by badcure** [comment]
I think #955 may help you out, though not merged yet. Basically rather than hijacking the response, you can catch the exceptions properly.

**Comment by phillipmadlan** [comment]
Thanks @badcure. I will wait for this to be merged. When it is merged, what version of Connexion will it be included in? We can upgrade then.

**Comment by badcure** [comment]
I am unsure about that unfortunately. Looking at other PRs, it seems it has been almost 3 weeks since someone from zalando has reviewed PRs. 

I just wanted to mention mine depending on your timeframe/priority. At least for me, I can wait for now...

**Comment by phillipmadlan** [comment]
I can wait now but it will be nice when this is merged. We will upgrade after this PR goes into release.

**Comment by phillipmadlan** [comment]
Thanks for your work and reply by the way. Your work is exactly what I am looking for!
