### ISSUE TITLE
Parameter validation bypassed with non-ASCII parameter names

### ISSUE THREAD

**Issue by sochi** [spec-first/connexion#961]
### Description
Parameter validation seem to be bypassed when providing values as "array" using `key[]=value` format in URL.
Hypothetically there might be a possibility that this could be misused if an application would rely on parameter validation (and many applications do, that's why they opt for using a framework in a first place, right?). Or would this be a configuration flaw?

### Expected behaviour
That the parameter value is validated before passed on into the operational code.
For instance, with a parameter `values` defined to accept array of strings defined to match `^[A-Z]*$`, the validation is done against the values correctly.

* `GET /pets?values=AB` -- passed
* `GET /pets?values=ab` -- returns bad request
* `GET /pets?values=AB,ABC` -- passed as expected also
* `GET /pets?values=AB,abc` -- correctly returns bad request

### Actual behaviour
Values are passed directly, thus effectively bypassing any validation specified on those parameters.

And by passing the following, I expect the identical behaviour:
* `GET /pets?values[]=ab` -- passed directly as `['aa']`
* `GET /pets?values[]=AB,ABC` -- passed as `['AB,ABC']`
* `GET /pets?values[]=AB,abc` -- again passed directly `['AB,abc']`

### Steps to reproduce
Can be easily reproduced, copied the output from demo based on Example Pet store with minor modifications.
User API definition:
```
swagger: '2.0'
info:
  title: Pet Shop Example API
  version: "0.1"
  description: Simple example API to store and retrieve pets
consumes:
  - application/json
produces:
  - application/json

paths:
  /pets:
    get:
      security: []  # used for demonstration purpose
      tags: [Pets]
      operationId: app.get_pets
      summary: Get all pets
      parameters:
        - name: enum_values
          in: query
          type: array
          items:
            type: string
            enum:
              - rabbit
              - dog
              - snake
        - name: str_values
          in: query
          type: array
          items:
            type: string
            pattern: "^[A-Z]*$"
      responses:
        200:
          description: Return pets
          schema:
            type: object
```

And code handling it:
```
#!/usr/bin/env python3

import connexion
import logging


def get_pets(str_values=(), enum_values=()):
    enum_repr = repr(enum_values)
    logging.info("REPR {}".format(enum_repr))

    str_types = str(enum_values)
    logging.info("REQUEST WITH enum_types={}".format(str_types))
    logging.info("REQUEST WITH str_values={}".format(str_values))

    return {"pets": {"str_values": str_values, "enum_values": enum_values}}


logging.basicConfig(level=logging.INFO)
app = connexion.App(__name__)
app.add_api("swagger.yaml")

application = app.app

if __name__ == "__main__":
    app.run(port=8080, server="gevent")
```

Any passed value is provided, and correctly URL decoded, for instance:
* `curl '0.0.0.0:8080/pets?str_values[]=or%201%3D1%3B%20drop%20database%20hello_world%3B%20--'` in the example above gets passed into the functions as
```
{
  "pets": {
    "enum_values": [],
    "limit": [
      "or 1=1; drop database hello_world; --"
    ]
  }
}
```
* `curl '0.0.0.0:8080/pets?str_values=AB,CDE&enum_values=rabbit,snake'` -- works fine
* `curl '0.0.0.0:8080/pets?str_values=AB,CDE&enum_values=rabbit,snake2'` -- correctly fails
* `curl '0.0.0.0:8080/pets?str_values=AB,abc'` -- correctly fails
* `curl '0.0.0.0:8080/pets?str_values=AB,ABC'` -- works fine
* `curl '0.0.0.0:8080/pets?str_values[]=AB,abc'` -- works but should not, returning 
```
{
  "pets": {
    "enum_values": [],
    "limit": [
      "AB,abc"
    ]
  }
}
```

### Additional info:

Output of the commands:

- `python --version`
```
$ python --version
Python 3.7.3
```
- `pip show connexion | grep "^Version\:"`
```
pip show connexion | grep "^Version\:"
Version: 2.2.0
```

**Comment by sochi** [comment]
After some time I checked the Connexion implementation more thoroughly and seems that the whole issue is caused by Connexion sanitizing parameter names too late (or incorrectly assigning non-validated values from based on sanitized names).

### More precisely as of now:

1. The Connexion takes the request parameters and passes them through the validation.
However, the validation explicitly takes on those parameters which are defined in Swagger/OpenAPI specs. And so it effectively leaves any undefined request parameters unaffected. Up to this point, it is perfectly fine.

Though to illustrate the "problem" from my original issue I will provide a short example (which continues below): when "`person_id`" is expected then any other parameter like "`person_id[]`" or "`person--_id`" is not checked and still kept in the list of request parameters.

2. Then Connexion sanitizes any present request parameters so that those can be passed as parameters to the handling function (see the `parameter_to_arg` in `decorators/parameter.py`).
This is done effectively by simply removing any non-ASCII characters from the parameter names.

To continue with the example from above, here any "`person_id[]`" or "`person--_id`" parameters become "`person_id`" as unsupported characters are simply removed.

This sanitization itself sounds like an OK thing to do. However it's not as long as you get non-validated parameters in.

3. And finally Connexion calls the function with parameters from the step above. Then boom, a non-validated parameter value is in, and from the handling function itself you have no way to figure out if the value is actually valid unless you do the validation again (thus rendering the original validation fairly useless).

### Mitigation

Connexion offers a `strict_validation` option which performs an additional check in between the steps 1 and 2, and returns status 400 if the request contains any parameter which is not listed in the Swagger/OpenAPI specs (e.g., then requests containing a "`person_id[]`" would be rejected because the specs only contain "`person_id`").

### What could get changed in Connexion:

The sanitization of parameter names could be done before the validation. I.e., to stop passing non-validated values into parameters which expects validated values (from the Swagger/OpenAPI specs).

Or make `strict_validation` enabled by default. (And if the vulnerability is not fixed then the documentation for `strict_validation` should explicitly state that by not using `strict_validation` this vulnerability is introduced.)

### How this can be avoided by users of Connexion:

* Enable `strict_validation` -- This mitigates the problem quite easily.
* Block requests containing unsupported characters -- In case you don't want to enable `strict_validation` for any reason, you can just implement a similar check, for instance as:

```
connexion_app = connexion.FlaskApp(__name__)
app = connexion_app.app
...
@app.before_request
def validate_arg_names():
    for name in request.args:
        if not re.fullmatch('[a-zA-Z_][0-9a-zA-Z_]+', name):
            raise ValueError
```

### Impressions

I personally find it fairly disappointing that none of the maintainers even bothered looking at created issues. Especially if the README actually suggests to use the GitHub issue tracker ("Just follow the usual/standard GitHub practices.")

And with `strict_validation` not enabled by default I am wondering how many services out there (using Connexion) are vulnerable to this.
Should have I filled a CVE (https://cve.mitre.org/) for this?

**Comment by RobbeSneyders** [comment]
This is fixed in Connexion 3.
