### ISSUE TITLE
Return json/application exception

### ISSUE THREAD

**Issue by joe42** [spec-first/connexion#985]
### Description

I need to return an HTTP error with the content type application/json to integrate with a thrid-party service. But connexion converts HTTPException's content type, and json body into the application/problem+json format.

Is there a nice way of doing that for individual endpoints? 

I tried specifying the content type in the OpenApi specification, but that did not help.
Currently, I am  circumventing the conversion by using an HTTPException with status code of None:

`HTTPException(response=Response(
        json.dumps({'message': 'custom format'}),
        status=401,
        mimetype='application/json',
))`

This works fine for the consumer, but inside the application I cannot use the subclasses like Unauthorized to handle the exception.

### Additional info:
Python 3.7.2
Version: 2.2.0

**Comment by RobbeSneyders** [comment]
If you're using Flask, the easiest way is probably to overwrite [`FlaskApp.common_error_handler`](https://connexion.readthedocs.io/en/latest/autoapi/connexion/apps/flask_app/index.html#connexion.apps.flask_app.FlaskApp.common_error_handler).
