### ISSUE TITLE
Generate a Flask blueprint from an OpenAPI spec

### ISSUE THREAD

**Issue by NoiseByNorthwest** [spec-first/connexion#986]
Is there a way to only generate a Flask blueprint from an OpenAPI spec file ? And not pull all routing / viewing unrelated stuffs as promoted by the doc ?

While digging a bit into the source code I've found this simple workaround:

```python
import connexion

...

app.register_blueprint(
    connexion.Api(os.path.dirname(__file__) + "/../api-v1.yaml", ...).blueprint
)
```

Do you validate it ?
What about covering this use case in the documentation ?

**Comment by RobbeSneyders** [comment]
We don't document this, because this is not an interface we want to support.
